* 국민은행 앱 사욛자 리뷰 데이터 JSON 파일을 읽어와서 csv 파일로 변환하기

In [26]:
import json
import pandas as pd

In [3]:
with open("./data/com_kbstar_kbbank.json", 'r', encoding="utf-8") as file :
    data = file.read()
print(data[:20])

[
    {
        "사용자

In [4]:
data[:100]

'[\n    {\n        "사용자": "박성진 (홀리진)",\n        "별점": "4",\n        "리뷰": "리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면'

In [5]:
reviews = json.loads(data)
len(reviews)

2223

In [6]:
reviews[0]

{'사용자': '박성진 (홀리진)',
 '별점': '4',
 '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
 '날짜': '2025년 3월 2일',
 '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}

In [8]:
users=[]
points=[]
rev=[]
year_m=[]
recomd=[]

for i in reviews :
    users.append(i['사용자'])
    points.append(i['별점'])
    rev.append(i['리뷰'])
    year_m.append(i['날짜'])
    recomd.append(i['개발자 응답'])
    
review_info = dict(사용자=users, 별점=points, 리뷰=rev, 날짜=year_m, 개발자응답=recomd)
review_info

TypeError: unhashable type: 'slice'

In [11]:
df = pd.DataFrame(review_info)
df

,사용자,별점,리뷰,날짜,개발자응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

In [27]:
result={}
for key in reviews[0] :
    value_list = []
    for item in reviews[:2]:
        value_list.append(item[key])
    print(key, value_list)
    result[key] = value_list

사용자 ['박성진 (홀리진)', '윤태경']
별점 ['4', '5']
리뷰 ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.', 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.']
날짜 ['2025년 3월 2일', '2025년 1월 20일']
개발자 응답 ['고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.', "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"]

* 풀이

In [31]:
result = {}
for key in reviews[0]:
    temp = []
    for review in reviews:
        temp.append(review[key])
    result[key] = temp
len(result['별점'])

2223

In [32]:
df = pd.DataFrame(result)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

* 별점은 숫자로 변환해서 넣기, 나머지 특문은 제거

In [ ]:
result = {}
for key in reviews[0]:
    temp = []
    for review in reviews:
        if key == '별점':
            temp.append(int(review[key]))
        else :
            temp.append(review[key].apepnd)
        temp.append(review[key])
    result[key] = temp
len(result['별점'])

In [33]:
result2 = {}
for review in reviews[:2]:
    for key, value in review.items():
        result2.setdefault(key, []).append(value)
result2_df=pd.DataFrame(result2)
result2_df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...

In [10]:
import json

In [36]:
with open ("./data/전국치킨집리스트.json",  'r', encoding="utf-8") as file3 :
    chicken = json.load(file3)
print(type(chicken))

<class 'list'>

In [37]:
len(chicken)

37

In [95]:
c_item=chicken[0]['body']['items']
c_item[0]

{'bizesId': '10027626',
 'bizesNm': '장모님치킨가창점',
 'brchNm': '가창점',
 'indsLclsCd': 'Q',
 'indsLclsNm': '음식',
 'indsMclsCd': 'Q05',
 'indsMclsNm': '닭/오리요리',
 'indsSclsCd': 'Q05A08',
 'indsSclsNm': '후라이드/양념치킨',
 'ksicCd': 'I56193',
 'ksicNm': '치킨 전문점',
 'ctprvnCd': '27',
 'ctprvnNm': '대구광역시',
 'signguCd': '27710',
 'signguNm': '달성군',
 'adongCd': '2771031000',
 'adongNm': '가창면',
 'ldongCd': '2771031024',
 'ldongNm': '가창면',
 'lnoCd': '2771031024101200001',
 'plotSctCd': '1',
 'plotSctNm': '대지',
 'lnoMnno': 120,
 'lnoSlno': 1,
 'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
 'rdnmCd': '277103148001',
 'rdnm': '대구광역시 달성군 가창면 가창동로',
 'bldMnno': 6,
 'bldSlno': '',
 'bldMngNo': '2771031024101200004036858',
 'bldNm': '',
 'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
 'oldZipcd': '711861',
 'newZipcd': '42938',
 'dongNo': '',
 'flrNo': '1',
 'hoNo': '',
 'lon': 128.644458591419,
 'lat': 35.7826625402814}

In [97]:
result2={}
for key in c_item[0]:
    v_list=[]
    for i in c_item[:1]:
        v_list.append(i[key])
    print(key, v_list)
    result2[key]=v_list

bizesId ['10027626']
bizesNm ['장모님치킨가창점']
brchNm ['가창점']
indsLclsCd ['Q']
indsLclsNm ['음식']
indsMclsCd ['Q05']
indsMclsNm ['닭/오리요리']
indsSclsCd ['Q05A08']
indsSclsNm ['후라이드/양념치킨']
ksicCd ['I56193']
ksicNm ['치킨 전문점']
ctprvnCd ['27']
ctprvnNm ['대구광역시']
signguCd ['27710']
signguNm ['달성군']
adongCd ['2771031000']
adongNm ['가창면']
ldongCd ['2771031024']
ldongNm ['가창면']
lnoCd ['2771031024101200001']
plotSctCd ['1']
plotSctNm ['대지']
lnoMnno [120]
lnoSlno [1]
lnoAdr ['대구광역시 달성군 가창면 냉천리 120-1']
rdnmCd ['277103148001']
rdnm ['대구광역시 달성군 가창면 가창동로']
bldMnno [6]
bldSlno ['']
bldMngNo ['2771031024101200004036858']
bldNm ['']
rdnmAdr ['대구광역시 달성군 가창면 가창동로 6']
oldZipcd ['711861']
newZipcd ['42938']
dongNo ['']
flrNo ['1']
hoNo ['']
lon [128.644458591419]
lat [35.7826625402814]

In [98]:
chikkey={}
for key in c_item[0]:
    temp2 = []
    for dicts in c_item:
        temp2.append(dicts[key])
    chikkey[key] = temp2 
len(chikkey['flrNo'])

1000

In [99]:
result_ch = pd.DataFrame(chikkey)
result_ch

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,11927120,두두두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4719034028104640013062144,,경상북도 구미시 해평면 강동로 1671,730873,39154,,1,,128.390989,36.199637
996,11927310,호식이두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4272025029104520007040192,,강원도 홍천군 홍천읍 남산강변로 32,250930,25149,,1,,127.882012,37.685865
997,11927491,또봉이치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2820010200100690027020930,,인천광역시 남동구 풀무로 9-2,405230,21510,,1,,126.709187,37.469419
998,11927616,투마리치킨하늘도시점,하늘도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2811014600100330008000001,,인천광역시 중구 운중로 85-1,400811,22359,,1,,126.542880,37.493596
999,11927757,노랑통닭,구리수택점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4131010500104480006008791,구리신성미소지움,경기도 구리시 이문안로 81,471030,11941,101,1,,127.140380,37.592408

* data에는 리스트 요소가 37개 존재
* 리스트 요소 1개에는 1000개의 딕셔너리가 있고 그 안에 1000개의 가게 정보가 있음
* 가게정보는 data[0]['body']['items']
* 가게정보를 구성하는 key는 39개

# pandas의 json_normalize를 이용해서 쉽게 json에서 DataFrame으로 만들기

In [105]:
pd.json_normalize(c_item)

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,11927120,두두두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4719034028104640013062144,,경상북도 구미시 해평면 강동로 1671,730873,39154,,1,,128.390989,36.199637
996,11927310,호식이두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4272025029104520007040192,,강원도 홍천군 홍천읍 남산강변로 32,250930,25149,,1,,127.882012,37.685865
997,11927491,또봉이치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2820010200100690027020930,,인천광역시 남동구 풀무로 9-2,405230,21510,,1,,126.709187,37.469419
998,11927616,투마리치킨하늘도시점,하늘도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2811014600100330008000001,,인천광역시 중구 운중로 85-1,400811,22359,,1,,126.542880,37.493596
999,11927757,노랑통닭,구리수택점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4131010500104480006008791,구리신성미소지움,경기도 구리시 이문안로 81,471030,11941,101,1,,127.140380,37.592408

In [104]:
import pandas as pd
pd.__version__
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.9.21
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.19045
machine               : AMD64
processor             : AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : Korean_Korea.949

pandas                : 2.2.3
numpy                 : 2.0.2
pytz                  : 2024.1
dateutil              : 2.9.0.post0
pip                   : 25.0.1
Cython                : None
sphinx                : None
IPython               : 8.18.1
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.3
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.6
lxml.etree            : None
matplotlib            : 3.9.4
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2025.1
qtpy                  : None
pyqt5                 : None