In [1]:
import pandas as pd

In [2]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [3]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Belgium to United Kingdom
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  5 non-null      float64
 1   area        5 non-null      int64
 2   capital     5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

---

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

<div class="alert alert-success">
    <b>EXERCISE</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(title)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

403

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(title)이 "Treasure Island"인 영화를 제작년도(year)의 오름차순에 따라 표시하세요
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

In [8]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [9]:
engine = create_engine("mysql+pymysql://kict05:kict05@221.155.18.165:3306/titanic")
conn = engine.connect()
passenger = pd.read_sql("p_info", con=conn)
conn.close()
passenger

,PassengerId,Name,Sex,Age,SibSp,Parch
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0

In [ ]:
engine = create_engine("mysql+pymysql://kict05:kict05@221.155.18.165:3306/titanic")
conn = engine.connect()
sur = pd.read_sql("survived", con=conn)
conn.close()
sur

In [ ]:
engine = create_engine("mysql+pymysql://kict05:kict05@221.155.18.165:3306/titanic")
conn = engine.connect()
tickets = pd.read_sql("t_info", con=conn)
conn.close()
tickets

In [29]:
titanic_res = pd.concat([passenger,tickets,sur], axis=1)
titanic_res.head()

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,None,S,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0

In [27]:
passenger

,PassengerId,Name,Sex,Age,SibSp,Parch
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0

In [25]:
tickets

     PassengerId            Ticket  Pclass     Fare Cabin Embarked
0              1         A/5 21171       3   7.2500  None        S
1              2          PC 17599       1  71.2833   C85        C
2              3  STON/O2. 3101282       3   7.9250  None        S
3              4            113803       1  53.1000  C123        S
4              5            373450       3   8.0500  None        S
..           ...               ...     ...      ...   ...      ...
886          887            211536       2  13.0000  None        S
887          888            112053       1  30.0000   B42        S
888          889        W./C. 6607       3  23.4500  None        S
889          890            111369       1  30.0000  C148        C
890          891            370376       3   7.7500  None        Q

[891 rows x 6 columns]

In [24]:
sur

     PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 정보(info)를 출력하세요.
</div>

In [30]:
titanic_res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    object
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   PassengerId  891 non-null    int64
 7   Ticket       891 non-null    object
 8   Pclass       891 non-null    int64
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  PassengerId  891 non-null    int64
 13  Survived     891 non-null    int64
dtypes: float64(2), int64(7), object(5)
memory usage: 97.6+ KB

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

In [31]:
titanic_res.describe()

,PassengerId,Age,SibSp,Parch,PassengerId,Pclass,Fare,PassengerId,Survived
count,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,29.699118,0.523008,0.381594,446.000000,2.308642,32.204208,446.000000,0.383838
std,257.353842,14.526497,1.102743,0.806057,257.353842,0.836071,49.693429,257.353842,0.486592
min,1.000000,0.420000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000
25%,223.500000,20.125000,0.000000,0.000000,223.500000,2.000000,7.910400,223.500000,0.000000
50%,446.000000,28.000000,0.000000,0.000000,446.000000,3.000000,14.454200,446.000000,0.000000
75%,668.500000,38.000000,1.000000,0.000000,668.500000,3.000000,31.000000,668.500000,1.000000
max,891.000000,80.000000,8.000000,6.000000,891.000000,3.000000,512.329200,891.000000,1.000000

<div class="alert alert-success">
    <b>EXERCISE</b>: 처음 100명의 데이터를 출력하세요.
</div>

In [32]:
titanic_res.head(100)

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,None,S,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,"Shorney, Mr. Charles Joseph",male,NaN,0,0,96,374910,3,8.0500,None,S,96,0
96,97,"Goldschmidt, Mr. George B",male,71.0,0,0,97,PC 17754,1,34.6542,A5,C,97,0
97,98,"Greenfield, Mr. William Bertram",male,23.0,0,1,98,PC 17759,1,63.3583,D10 D12,C,98,1
98,99,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,99,231919,2,23.0000,None,S,99,1
99,100,"Kantor, Mr. Sinai",male,34.0,1,0,100,244367,2,26.0000,None,S,100,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

In [40]:
titanic_res.iloc[10:21]

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,11,PP 9549,3,16.7000,G6,S,11,1
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,12,113783,1,26.5500,C103,S,12,1
12,13,"Saundercock, Mr. William Henry",male,20.0,0,0,13,A/5. 2151,3,8.0500,None,S,13,0
13,14,"Andersson, Mr. Anders Johan",male,39.0,1,5,14,347082,3,31.2750,None,S,14,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,15,350406,3,7.8542,None,S,15,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,16,248706,2,16.0000,None,S,16,1
16,17,"Rice, Master. Eugene",male,2.0,4,1,17,382652,3,29.1250,None,Q,17,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,18,244373,2,13.0000,None,S,18,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,19,345763,3,18.0000,None,S,19,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,20,2649,3,7.2250,None,C,20,1
20,21,"Fynney, Mr. Joseph J",male,35.0,0,0,21,239865,2,26.0000,None,S,21,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

In [44]:
titanic_res.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'PassengerId',
       'Ticket', 'Pclass', 'Fare', 'Cabin', 'Embarked', 'PassengerId',
       'Survived'],
      dtype='object')

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 shape를 확인하세요.
</div>

In [45]:
titanic_res.shape

(891, 14)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

In [51]:
titanic_res["Age"].mean()

np.float64(29.69911764705882)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

In [53]:
titanic_res["Survived"].unique()

array([0, 1])

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

In [54]:
titanic_res[titanic_res['Age'] >= 30]

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,0,7,17463,1,51.8625,E46,S,7,0
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,12,113783,1,26.5500,C103,S,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,874,345765,3,9.0000,None,S,874,0
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,880,11767,1,83.1583,C50,C,880,1
881,882,"Markun, Mr. Johann",male,33.0,0,0,882,349257,3,7.8958,None,S,882,0
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,886,382652,3,29.1250,None,Q,886,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,891,370376,3,7.7500,None,Q,891,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

In [60]:
titanic_res[(titanic_res['Sex'] == 'female') & (titanic_res['Survived'] == 1)]

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,9,347742,3,11.1333,None,S,9,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,10,237736,2,30.0708,None,C,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,875,P/PP 3381,2,24.0000,None,C,875,1
875,876,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,876,2667,3,7.2250,None,C,876,1
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,880,11767,1,83.1583,C50,C,880,1
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,881,230433,2,26.0000,None,S,881,1
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,888,112053,1,30.0000,B42,S,888,1

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

In [62]:
titanic_res[(titanic_res['Age'] <= 10) & (titanic_res['Fare'] >= 20)]

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
7,8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,8,349909,3,21.0750,None,S,8,0
16,17,"Rice, Master. Eugene",male,2.00,4,1,17,382652,3,29.1250,None,Q,17,0
24,25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,25,349909,3,21.0750,None,S,25,0
43,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,44,SC/Paris 2123,2,41.5792,None,C,44,1
50,51,"Panula, Master. Juha Niilo",male,7.00,4,1,51,3101295,3,39.6875,None,S,51,0
58,59,"West, Miss. Constance Mirium",female,5.00,1,2,59,C.A. 34651,2,27.7500,None,S,59,1
63,64,"Skoog, Master. Harald",male,4.00,3,2,64,347088,3,27.9000,None,S,64,0
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,79,248738,2,29.0000,None,S,79,1
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,120,347082,3,31.2750,None,S,120,0
147,148,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,148,W./C. 6608,3,34.3750,None,S,148,0
164,165,"Panula, Master. Eino Viljami",male,1.00,4,1,165,3101295,3,39.6875,None,S,165,0
165,166,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,166,363291,3,20.5250,None,S,166,1
171,172,"Rice, Master. Arthur",male,4.00,4,1,172,382652,3,29.1250,None,Q,172,0
182,183,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,183,347077,3,31.3875,None,S,183,0
183,184,"Becker, Master. Richard F",male,1.00,2,1,184,230136,2,39.0000,F4,S,184,1
184,185,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,185,315153,3,22.0250,None,S,185,1
193,194,"Navratil, Master. Michel M",male,3.00,1,1,194,230080,2,26.0000,F2,S,194,1
233,234,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,234,347077,3,31.3875,None,S,234,1
237,238,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,238,C.A. 31921,2,26.2500,None,S,238,1
261,262,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,262,347077,3,31.3875,None,S,262,1
278,279,"Rice, Master. Eric",male,7.00,4,1,279,382652,3,29.1250,None,Q,279,0
297,298,"Allison, Miss. Helen Loraine",female,2.00,1,2,298,113781,1,151.5500,C22 C26,S,298,0
305,306,"Allison, Master. Hudson Trevor",male,0.92,1,2,306,113781,1,151.5500,C22 C26,S,306,1
340,341,"Navratil, Master. Edmond Roger",male,2.00,1,1,341,230080,2,26.0000,F2,S,341,1
374,375,"Palsson, Miss. Stina Viola",female,3.00,3,1,375,349909,3,21.0750,None,S,375,0
386,387,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,387,CA 2144,3,46.9000,None,S,387,0
419,420,"Van Impe, Miss. Catharina",female,10.00,0,2,420,345773,3,24.1500,None,S,420,0
445,446,"Dodge, Master. Washington",male,4.00,0,2,446,33638,1,81.8583,A34,S,446,1
480,481,"Goodwin, Master. Harold Victor",male,9.00,5,2,481,CA 2144,3,46.9000,None,S,481,0
530,531,"Quick, Miss. Phyllis May",female,2.00,1,1,531,26360,2,26.0000,None,S,531,1
535,536,"Hart, Miss. Eva Miriam",female,7.00,0,2,536,F.C.C. 13529,2,26.2500,None,S,536,1
541,542,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,542,347082,3,31.2750,None,S,542,0
549,550,"Davies, Master. John Morgan Jr",male,8.00,1,1,550,C.A. 33112,2,36.7500,None,S,550,1
618,619,"Becker, Miss. Marion Louise",female,4.00,2,1,619,230136,2,39.0000,F4,S,619,1
634,635,"Skoog, Miss. Mabel",female,9.00,3,2,635,347088,3,27.9000,None,S,635,0
642,643,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,643,347088,3,27.9000,None,S,643,0
720,721,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,721,248727,2,33.0000,None,S,721,1
750,751,"Wells, Miss. Joan",female,4.00,1,1,751,29103,2,23.0000,None,S,751,1
787,788,"Rice, Master. George Hugh",male,8.00,4,1,788,382652,3,29.1250,None,Q,788,0
788,789,"Dean, Master. Bertram Vere",male,1.00,1,2,789,C.A. 2315,3,20.5750,None,S,789,1
813,814,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,814,347082,3,31.2750,None,S,814,0
819,820,"Skoog, Master. Karl Thorsten",male,10.00,3,2,820,347088,3,27.9000,None,S,820,0
824,825,"Panula, Master. Urho Abraham",male,2.00,4,1,825,3101295,3,39.6875,None,S,825,0
827,828,"Mallet, Master. Andre",male,1.00,0,2,828,S.C./PARIS 2079,2,37.0042,None,C,828,1
850,851,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,851,347082,3,31.2750,None,S,851,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

In [63]:
titanic_res.isnull()

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False,False,False

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

In [64]:
titanic_res.sort_values('Age')

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
803,804,"Thomas, Master. Assad Alexander",male,0.42,0,1,804,2625,3,8.5167,None,C,804,1
755,756,"Hamalainen, Master. Viljo",male,0.67,1,1,756,250649,2,14.5000,None,S,756,1
644,645,"Baclini, Miss. Eugenie",female,0.75,2,1,645,2666,3,19.2583,None,C,645,1
469,470,"Baclini, Miss. Helene Barbara",female,0.75,2,1,470,2666,3,19.2583,None,C,470,1
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,79,248738,2,29.0000,None,S,79,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,860,2629,3,7.2292,None,C,860,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,864,CA. 2343,3,69.5500,None,S,864,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,869,345777,3,9.5000,None,S,869,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,879,349217,3,7.8958,None,S,879,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,889,W./C. 6607,3,23.4500,None,S,889,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

In [65]:
titanic_res.sort_values('Fare', ascending=False).head()

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
679,680,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,680,PC 17755,1,512.3292,B51 B53 B55,C,680,1
258,259,"Ward, Miss. Anna",female,35.0,0,0,259,PC 17755,1,512.3292,None,C,259,1
737,738,"Lesurer, Mr. Gustave J",male,35.0,0,0,738,PC 17755,1,512.3292,B101,C,738,1
88,89,"Fortune, Miss. Mabel Helen",female,23.0,3,2,89,19950,1,263.0000,C23 C25 C27,S,89,1
438,439,"Fortune, Mr. Mark",male,64.0,1,4,439,19950,1,263.0000,C23 C25 C27,S,439,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

In [66]:
titanic_res.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

<div class="alert alert-success">
    <b>EXERCISE</b>: Pclass별 평균 나이를 구하세요.
</div>

In [67]:
titanic_res.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

In [68]:
titanic_res['Age_plus_10']=titanic_res['Age']+10
titanic_res
# 차원문제?

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived,Age_plus_10
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,None,S,1,0,32.0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1,48.0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1,36.0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1,45.0
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,887,211536,2,13.0000,None,S,887,0,37.0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,888,112053,1,30.0000,B42,S,888,1,29.0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,889,W./C. 6607,3,23.4500,None,S,889,0,NaN
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,890,111369,1,30.0000,C148,C,890,1,36.0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,891,370376,3,7.7500,None,Q,891,0,42.0

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

In [69]:
titanic_res['isAge']=titanic_res['Age'].apply(lambda x : "성인" if x >= 19 else "미성년")

In [70]:
titanic_res

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived,Age_plus_10,isAge
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,None,S,1,0,32.0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1,48.0,성인
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1,36.0,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1,45.0,성인
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,887,211536,2,13.0000,None,S,887,0,37.0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,888,112053,1,30.0000,B42,S,888,1,29.0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,889,W./C. 6607,3,23.4500,None,S,889,0,NaN,미성년
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,890,111369,1,30.0000,C148,C,890,1,36.0,성인
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,891,370376,3,7.7500,None,Q,891,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

In [80]:
t_avg = titanic_res['Age'].mean()
t_avg

np.float64(29.69911764705882)

In [81]:
titanic_res['Age'] = titanic_res['Age'].fillna(t_avg)

In [82]:
titanic_res

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived,Age_plus_10,isAge
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,1,A/5 21171,3,7.2500,None,S,1,0,32.0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,2,PC 17599,1,71.2833,C85,C,2,1,48.0,성인
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1,36.0,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,4,113803,1,53.1000,C123,S,4,1,45.0,성인
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,5,373450,3,8.0500,None,S,5,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,887,211536,2,13.0000,None,S,887,0,37.0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,888,112053,1,30.0000,B42,S,888,1,29.0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,889,W./C. 6607,3,23.4500,None,S,889,0,NaN,미성년
889,890,"Behr, Mr. Karl Howell",male,26.000000,0,0,890,111369,1,30.0000,C148,C,890,1,36.0,성인
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,891,370376,3,7.7500,None,Q,891,0,42.0,성인

In [93]:
list(titanic_res['Age'].isnull()).count(True)

0

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

In [95]:
titanic_res['Cabin'] = titanic_res['Cabin'].fillna("Unknown")
titanic_res

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived,Age_plus_10,isAge
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,1,A/5 21171,3,7.2500,Unknown,S,1,0,32.0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,2,PC 17599,1,71.2833,C85,C,2,1,48.0,성인
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,3,STON/O2. 3101282,3,7.9250,Unknown,S,3,1,36.0,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,4,113803,1,53.1000,C123,S,4,1,45.0,성인
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,5,373450,3,8.0500,Unknown,S,5,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,887,211536,2,13.0000,Unknown,S,887,0,37.0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,888,112053,1,30.0000,B42,S,888,1,29.0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,889,W./C. 6607,3,23.4500,Unknown,S,889,0,NaN,미성년
889,890,"Behr, Mr. Karl Howell",male,26.000000,0,0,890,111369,1,30.0000,C148,C,890,1,36.0,성인
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,891,370376,3,7.7500,Unknown,Q,891,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 초기화하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구하기 위해 ?부분을 알맞게 채워주세요.
</div>

In [49]:
def survival_ratio(survived):
    return survived.sum() / len(survived)