# 중요 컬럼 선택하기
* 1) EDA를 통해서 종속변수(target)와 중요한 관계가 있는 변수들만 선택
* 2) 수치형 변수는 상관분석 결과를 통해, 범주형 변수는 카이제곱 통계량(통계학적 방법)
* 3) 머신러닝 알고리즘을 통한 1차 분석 후 중요하게 사용된 변수만 선택

# TREE 계열 모델의 feature_importance로 선택하기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns

In [2]:
data = pd.read_csv("./data/salary2.csv")
data.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

In [3]:
data2=data.copy()

In [4]:
data=data.drop_duplicates()

In [5]:
data=data.dropna()
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
5,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48835,53,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
48836,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
48837,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48839,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48841,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [6]:
data = data.reset_index(drop=True)
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39235,53,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
39236,22,Private,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
39237,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
39238,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
39239,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [9]:
data['class'] = data['class'].apply(lambda x : 1 if x == ' >50K' else 0)

In [11]:
data = pd.get_dummies(data, drop_first=True)

In [12]:
X = data.drop('class', axis = 1)
y = data['class']

In [13]:
X

,age,education-num,capital-gain,capital-loss,hours-per-week,workclass_ Local-gov,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,...,native-country_ Portugal,native-country_ Puerto-Rico,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ United-States,native-country_ Vietnam,native-country_ Yugoslavia
0,25,7,0,0,40,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,38,9,0,0,50,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,28,12,0,0,40,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,44,10,7688,0,40,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,34,6,0,0,30,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39235,53,14,0,0,40,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39236,22,10,0,0,40,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39237,27,12,0,0,38,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39238,58,9,0,0,40,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39239,52,9,15024,0,40,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [14]:
y

0        0
1        0
2        1
3        1
4        0
        ..
39235    1
39236    0
39237    0
39238    0
39239    1
Name: class, Length: 39240, dtype: int64

In [16]:
y.value_counts()

class
0    29265
1     9975
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, stratify=y, random_state=10)

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [21]:
dtc = DecisionTreeClassifier(max_depth=9, random_state=10)
dtc.fit(X_train, y_train)
pred = dtc.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.87      0.94      0.90     11706
           1       0.77      0.58      0.66      3990

    accuracy                           0.85     15696
   macro avg       0.82      0.76      0.78     15696
weighted avg       0.84      0.85      0.84     15696

# feature_importance 출력하기

In [25]:
importance = pd.DataFrame(dtc.feature_importances_)

In [26]:
cols = pd.DataFrame(dtc.feature_names_in_)

In [35]:
important_cols = pd.concat([cols, importance], axis=1)

In [36]:
important_cols.columns = ['column', 'importance']

In [40]:
important_cols.sort_values(by='importance', ascending = False)

                                column  importance
27  marital-status_ Married-civ-spouse    0.400573
2                         capital-gain    0.216183
1                        education-num    0.194695
3                         capital-loss    0.078845
0                                  age    0.038730
..                                 ...         ...
90            native-country_ Thailand    0.000000
91     native-country_ Trinadad&Tobago    0.000000
92       native-country_ United-States    0.000000
93             native-country_ Vietnam    0.000000
94          native-country_ Yugoslavia    0.000000

[95 rows x 2 columns]

In [41]:
important_cols[important_cols['importance'] > 0]

                                column  importance
0                                  age    0.038730
1                        education-num    0.194695
2                         capital-gain    0.216183
3                         capital-loss    0.078845
4                       hours-per-week    0.031110
5                 workclass_ Local-gov    0.000786
6                   workclass_ Private    0.000301
7              workclass_ Self-emp-inc    0.001322
8          workclass_ Self-emp-not-inc    0.006948
9                 workclass_ State-gov    0.000301
11                     education_ 11th    0.000155
15                  education_ 7th-8th    0.000301
21                  education_ HS-grad    0.001777
26   marital-status_ Married-AF-spouse    0.000487
27  marital-status_ Married-civ-spouse    0.400573
29       marital-status_ Never-married    0.000906
33            occupation_ Craft-repair    0.000385
34         occupation_ Exec-managerial    0.011520
35         occupation_ Farming-fishing    0.004866
36       occupation_ Handlers-cleaners    0.000164
38           occupation_ Other-service    0.000504
40          occupation_ Prof-specialty    0.000222
41         occupation_ Protective-serv    0.000514
42                   occupation_ Sales    0.000075
44        occupation_ Transport-moving    0.000444
45         relationship_ Not-in-family    0.000225
47             relationship_ Own-child    0.000312
49                  relationship_ Wife    0.000987
54                           sex_ Male    0.003542
55              native-country_ Canada    0.000553
60             native-country_ Ecuador    0.000301
62             native-country_ England    0.000401
65              native-country_ Greece    0.000403
83         native-country_ Philippines    0.000427
85            native-country_ Portugal    0.000734

# random_forest

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
rfc = RandomForestClassifier(random_state=10)
rfc.fit(X_train, y_train)
pred = rfc.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.87      0.90      0.89     11706
           1       0.68      0.60      0.64      3990

    accuracy                           0.83     15696
   macro avg       0.77      0.75      0.76     15696
weighted avg       0.82      0.83      0.82     15696

In [47]:
importance2 = pd.DataFrame(rfc.feature_importances_, columns=['importance'])
column2 = pd.DataFrame(rfc.feature_names_in_, columns=['column'])
rfc_importance = pd.concat([column2, importance2], axis=1)
rfc_importance

                             column  importance
0                               age    0.229726
1                     education-num    0.060181
2                      capital-gain    0.122142
3                      capital-loss    0.041190
4                    hours-per-week    0.117826
..                              ...         ...
90         native-country_ Thailand    0.000140
91  native-country_ Trinadad&Tobago    0.000107
92    native-country_ United-States    0.006653
93          native-country_ Vietnam    0.000283
94       native-country_ Yugoslavia    0.000381

[95 rows x 2 columns]

In [52]:
rfc_importance[rfc_importance['importance'] > 0.01].sort_values(by="importance", ascending=False)

                                column  importance
0                                  age    0.229726
2                         capital-gain    0.122142
4                       hours-per-week    0.117826
27  marital-status_ Married-civ-spouse    0.083482
1                        education-num    0.060181
3                         capital-loss    0.041190
29       marital-status_ Never-married    0.034063
34         occupation_ Exec-managerial    0.019778
54                           sex_ Male    0.019321
45         relationship_ Not-in-family    0.017576
40          occupation_ Prof-specialty    0.015555
6                   workclass_ Private    0.013842
19                education_ Bachelors    0.010689
47             relationship_ Own-child    0.010049

In [53]:
from xgboost import XGBClassifier

In [55]:
xgb = XGBClassifier(random_state=10)
xgb.fit(X_train, y_train)
pred = xgb.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91     11706
           1       0.77      0.67      0.71      3990

    accuracy                           0.86     15696
   macro avg       0.83      0.80      0.81     15696
weighted avg       0.86      0.86      0.86     15696

In [61]:
importance3 = pd.DataFrame(xgb.feature_importances_, columns=['importance'])
column3 = pd.DataFrame(xgb.feature_names_in_, columns=['column'])
importance3 = pd.concat([column3, importance3], axis=1)
importance3=importance3[importance3['importance'] > 0.01].sort_values(by='importance', ascending=False)
importance3

                                column  importance
27  marital-status_ Married-civ-spouse    0.413689
2                         capital-gain    0.058502
1                        education-num    0.046971
38           occupation_ Other-service    0.033853
3                         capital-loss    0.024621
35         occupation_ Farming-fishing    0.023159
34         occupation_ Exec-managerial    0.021343
47             relationship_ Own-child    0.015753
40          occupation_ Prof-specialty    0.013670
79              native-country_ Mexico    0.013073
8          workclass_ Self-emp-not-inc    0.011670
49                  relationship_ Wife    0.011557
36       occupation_ Handlers-cleaners    0.011540
26   marital-status_ Married-AF-spouse    0.010706
29       marital-status_ Never-married    0.010705
37       occupation_ Machine-op-inspct    0.010180

In [122]:
data2.columns

Index(['age', 'workclass', 'education', 'education-num', 'marital-status',
       'occupation', 'relationship', 'race', 'sex', 'capital-gain',
       'capital-loss', 'hours-per-week', 'native-country', 'class'],
      dtype='object')

In [148]:
data2 = data2.drop_duplicates()
data2 = data2.dropna()
data3 = data2[['age', 'marital-status','capital-gain','capital-loss', 'sex', 'education-num', 'occupation','class']]

In [149]:
data3 = data3.reset_index(drop=True)
data3

,age,marital-status,capital-gain,capital-loss,sex,education-num,occupation,class
0,25,Never-married,0,0,Male,7,Machine-op-inspct,<=50K
1,38,Married-civ-spouse,0,0,Male,9,Farming-fishing,<=50K
2,28,Married-civ-spouse,0,0,Male,12,Protective-serv,>50K
3,44,Married-civ-spouse,7688,0,Male,10,Machine-op-inspct,>50K
4,34,Never-married,0,0,Male,6,Other-service,<=50K
...,...,...,...,...,...,...,...,...
39235,53,Married-civ-spouse,0,0,Male,14,Exec-managerial,>50K
39236,22,Never-married,0,0,Male,10,Protective-serv,<=50K
39237,27,Married-civ-spouse,0,0,Female,12,Tech-support,<=50K
39238,58,Widowed,0,0,Female,9,Adm-clerical,<=50K
39239,52,Married-civ-spouse,15024,0,Female,9,Exec-managerial,>50K

In [150]:
data3 = pd.get_dummies(data3, drop_first=True)
data3

,age,capital-gain,capital-loss,education-num,marital-status_ Married-AF-spouse,marital-status_ Married-civ-spouse,marital-status_ Married-spouse-absent,marital-status_ Never-married,marital-status_ Separated,marital-status_ Widowed,...,occupation_ Handlers-cleaners,occupation_ Machine-op-inspct,occupation_ Other-service,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving,class_ >50K
0,25,0,0,7,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
1,38,0,0,9,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,28,0,0,12,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
3,44,7688,0,10,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
4,34,0,0,6,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39235,53,0,0,14,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
39236,22,0,0,10,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
39237,27,0,0,12,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
39238,58,0,0,9,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
39239,52,15024,0,9,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [151]:
X = data3.drop('class_ >50K', axis=1)
y = data3['class_ >50K']

In [152]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, stratify=y, random_state=10)

In [153]:
xgb = XGBClassifier(random_state=10)
xgb.fit(X_train, y_train)
pred = xgb.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

       False       0.89      0.93      0.91     11706
        True       0.77      0.65      0.70      3990

    accuracy                           0.86     15696
   macro avg       0.83      0.79      0.81     15696
weighted avg       0.86      0.86      0.86     15696

In [154]:
importance3 = pd.DataFrame(xgb.feature_importances_, columns=['importance'])
column3 = pd.DataFrame(xgb.feature_names_in_, columns=['column'])
importance3 = pd.concat([column3, importance3], axis=1)
importance3=importance3[importance3['importance'] > 0.01].sort_values(by='importance', ascending=False)
importance3

                                column  importance
5   marital-status_ Married-civ-spouse    0.473459
1                         capital-gain    0.090947
3                        education-num    0.057546
17           occupation_ Other-service    0.056346
14         occupation_ Farming-fishing    0.047047
13         occupation_ Exec-managerial    0.039511
2                         capital-loss    0.035579
19          occupation_ Prof-specialty    0.028145
22            occupation_ Tech-support    0.021765
15       occupation_ Handlers-cleaners    0.017977
16       occupation_ Machine-op-inspct    0.015357
0                                  age    0.014199
18         occupation_ Priv-house-serv    0.014141
7        marital-status_ Never-married    0.013379
4    marital-status_ Married-AF-spouse    0.013300
10                           sex_ Male    0.012126

# 클래스 불균형을 처리하는 방법
* 클래스불균형 : 종속변수(target)의 클래스(값, 요소)의 비율이 일치하지 않는 경우
* 연봉데이터의 경우 >50K가 1, <=50K가 3의 비율을 가지고 있음
* train_test_split시 stratify = 옵션을 반드시 포함
* 머신러닝 알고리즘에 있는 소수 클래스에 가중치를 주는 옵션을 키기

decisionTree 모델의 경우

In [159]:
for i in range(1, 20) :
    dtc = DecisionTreeClassifier(max_depth=i, class_weight="balanced",random_state = 10)
    dtc.fit(X_train, y_train)
    pred = dtc.predict(X_test)
    print(i)
    print(classification_report(y_test, pred))
    print()

1
              precision    recall  f1-score   support

       False       0.92      0.67      0.78     11706
        True       0.47      0.83      0.60      3990

    accuracy                           0.71     15696
   macro avg       0.69      0.75      0.69     15696
weighted avg       0.81      0.71      0.73     15696


2
              precision    recall  f1-score   support

       False       0.94      0.67      0.78     11706
        True       0.48      0.88      0.62      3990

    accuracy                           0.72     15696
   macro avg       0.71      0.77      0.70     15696
weighted avg       0.82      0.72      0.74     15696


3
              precision    recall  f1-score   support

       False       0.89      0.85      0.87     11706
        True       0.62      0.70      0.66      3990

    accuracy                           0.81     15696
   macro avg       0.76      0.78      0.76     15696
weighted avg       0.82      0.81      0.82     15696


4
              precision    recall  f1-score   support

       False       0.94      0.73      0.82     11706
        True       0.52      0.86      0.65      3990

    accuracy                           0.76     15696
   macro avg       0.73      0.80      0.74     15696
weighted avg       0.83      0.76      0.78     15696


5
              precision    recall  f1-score   support

       False       0.94      0.74      0.83     11706
        True       0.53      0.86      0.66      3990

    accuracy                           0.77     15696
   macro avg       0.74      0.80      0.74     15696
weighted avg       0.84      0.77      0.78     15696


6
              precision    recall  f1-score   support

       False       0.94      0.76      0.84     11706
        True       0.55      0.86      0.67      3990

    accuracy                           0.78     15696
   macro avg       0.74      0.81      0.75     15696
weighted avg       0.84      0.78      0.80     15696


7
              precision    recall  f1-score   support

       False       0.94      0.77      0.84     11706
        True       0.55      0.85      0.67      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.80     15696


8
              precision    recall  f1-score   support

       False       0.94      0.77      0.85     11706
        True       0.56      0.86      0.68      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.82      0.76     15696
weighted avg       0.85      0.79      0.81     15696


9
              precision    recall  f1-score   support

       False       0.94      0.78      0.85     11706
        True       0.56      0.85      0.68      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.80     15696


10
              precision    recall  f1-score   support

       False       0.95      0.76      0.84     11706
        True       0.55      0.87      0.68      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.82      0.76     15696
weighted avg       0.85      0.79      0.80     15696


11
              precision    recall  f1-score   support

       False       0.94      0.78      0.85     11706
        True       0.57      0.86      0.68      3990

    accuracy                           0.80     15696
   macro avg       0.75      0.82      0.77     15696
weighted avg       0.85      0.80      0.81     15696


12
              precision    recall  f1-score   support

       False       0.94      0.77      0.85     11706
        True       0.56      0.86      0.68      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.80     15696


13
              precision    recall  f1-score   support

       False       0.94      0.77      0.85     11706
        True       0.56      0.86      0.68      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.81     15696


14
              precision    recall  f1-score   support

       False       0.94      0.78      0.85     11706
        True       0.56      0.85      0.68      3990

    accuracy                           0.80     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.80      0.81     15696


15
              precision    recall  f1-score   support

       False       0.94      0.77      0.85     11706
        True       0.56      0.85      0.68      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.80     15696


16
              precision    recall  f1-score   support

       False       0.94      0.77      0.85     11706
        True       0.56      0.85      0.68      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.80     15696


17
              precision    recall  f1-score   support

       False       0.94      0.77      0.84     11706
        True       0.56      0.85      0.67      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.80     15696


18
              precision    recall  f1-score   support

       False       0.94      0.78      0.85     11706
        True       0.57      0.84      0.68      3990

    accuracy                           0.80     15696
   macro avg       0.75      0.81      0.77     15696
weighted avg       0.84      0.80      0.81     15696


19
              precision    recall  f1-score   support

       False       0.93      0.78      0.85     11706
        True       0.57      0.83      0.68      3990

    accuracy                           0.80     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.80      0.81     15696

random_forest의 경우 class_weight="balanced"

In [160]:
rfc = RandomForestClassifier(n_estimators=100, n_jobs=-1,class_weight="balanced",random_state = 10)
rfc.fit(X_train, y_train)
pred = rfc.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

       False       0.90      0.85      0.87     11706
        True       0.62      0.71      0.66      3990

    accuracy                           0.82     15696
   macro avg       0.76      0.78      0.77     15696
weighted avg       0.83      0.82      0.82     15696

In [161]:
for i in range(1, 20) :
    rfc = RandomForestClassifier(max_depth=i, n_estimators=100, n_jobs=-1,class_weight="balanced",random_state = 10)
    rfc.fit(X_train, y_train)
    pred = rfc.predict(X_test)
    print(i)
    print(classification_report(y_test, pred))
    print()

1
              precision    recall  f1-score   support

       False       0.94      0.68      0.79     11706
        True       0.48      0.87      0.62      3990

    accuracy                           0.73     15696
   macro avg       0.71      0.77      0.70     15696
weighted avg       0.82      0.73      0.75     15696


2
              precision    recall  f1-score   support

       False       0.94      0.70      0.80     11706
        True       0.50      0.87      0.64      3990

    accuracy                           0.75     15696
   macro avg       0.72      0.79      0.72     15696
weighted avg       0.83      0.75      0.76     15696


3
              precision    recall  f1-score   support

       False       0.94      0.71      0.81     11706
        True       0.50      0.87      0.64      3990

    accuracy                           0.75     15696
   macro avg       0.72      0.79      0.72     15696
weighted avg       0.83      0.75      0.76     15696


4
              precision    recall  f1-score   support

       False       0.94      0.73      0.82     11706
        True       0.52      0.87      0.65      3990

    accuracy                           0.76     15696
   macro avg       0.73      0.80      0.73     15696
weighted avg       0.83      0.76      0.78     15696


5
              precision    recall  f1-score   support

       False       0.94      0.73      0.82     11706
        True       0.52      0.87      0.65      3990

    accuracy                           0.76     15696
   macro avg       0.73      0.80      0.73     15696
weighted avg       0.83      0.76      0.78     15696


6
              precision    recall  f1-score   support

       False       0.94      0.74      0.83     11706
        True       0.53      0.87      0.66      3990

    accuracy                           0.77     15696
   macro avg       0.74      0.80      0.74     15696
weighted avg       0.84      0.77      0.78     15696


7
              precision    recall  f1-score   support

       False       0.94      0.77      0.85     11706
        True       0.56      0.86      0.67      3990

    accuracy                           0.79     15696
   macro avg       0.75      0.81      0.76     15696
weighted avg       0.84      0.79      0.80     15696


8
              precision    recall  f1-score   support

       False       0.94      0.78      0.85     11706
        True       0.57      0.85      0.68      3990

    accuracy                           0.80     15696
   macro avg       0.75      0.82      0.77     15696
weighted avg       0.85      0.80      0.81     15696


9
              precision    recall  f1-score   support

       False       0.94      0.78      0.85     11706
        True       0.57      0.85      0.68      3990

    accuracy                           0.80     15696
   macro avg       0.76      0.82      0.77     15696
weighted avg       0.85      0.80      0.81     15696


10
              precision    recall  f1-score   support

       False       0.94      0.79      0.86     11706
        True       0.58      0.85      0.69      3990

    accuracy                           0.80     15696
   macro avg       0.76      0.82      0.77     15696
weighted avg       0.85      0.80      0.81     15696


11
              precision    recall  f1-score   support

       False       0.94      0.79      0.86     11706
        True       0.58      0.85      0.69      3990

    accuracy                           0.81     15696
   macro avg       0.76      0.82      0.78     15696
weighted avg       0.85      0.81      0.82     15696


12
              precision    recall  f1-score   support

       False       0.94      0.80      0.86     11706
        True       0.59      0.85      0.69      3990

    accuracy                           0.81     15696
   macro avg       0.76      0.82      0.78     15696
weighted avg       0.85      0.81      0.82     15696


13
              precision    recall  f1-score   support

       False       0.94      0.80      0.87     11706
        True       0.59      0.85      0.70      3990

    accuracy                           0.81     15696
   macro avg       0.77      0.82      0.78     15696
weighted avg       0.85      0.81      0.82     15696


14
              precision    recall  f1-score   support

       False       0.94      0.81      0.87     11706
        True       0.60      0.84      0.70      3990

    accuracy                           0.82     15696
   macro avg       0.77      0.82      0.78     15696
weighted avg       0.85      0.82      0.82     15696


15
              precision    recall  f1-score   support

       False       0.94      0.81      0.87     11706
        True       0.60      0.84      0.70      3990

    accuracy                           0.82     15696
   macro avg       0.77      0.82      0.78     15696
weighted avg       0.85      0.82      0.82     15696


16
              precision    recall  f1-score   support

       False       0.93      0.81      0.87     11706
        True       0.60      0.83      0.70      3990

    accuracy                           0.82     15696
   macro avg       0.77      0.82      0.78     15696
weighted avg       0.85      0.82      0.83     15696


17
              precision    recall  f1-score   support

       False       0.93      0.82      0.87     11706
        True       0.61      0.82      0.70      3990

    accuracy                           0.82     15696
   macro avg       0.77      0.82      0.78     15696
weighted avg       0.85      0.82      0.83     15696


18
              precision    recall  f1-score   support

       False       0.93      0.82      0.87     11706
        True       0.61      0.82      0.70      3990

    accuracy                           0.82     15696
   macro avg       0.77      0.82      0.78     15696
weighted avg       0.85      0.82      0.83     15696


19
              precision    recall  f1-score   support

       False       0.93      0.82      0.87     11706
        True       0.61      0.81      0.70      3990

    accuracy                           0.82     15696
   macro avg       0.77      0.82      0.78     15696
weighted avg       0.85      0.82      0.83     15696

In [ ]:
xgboost

# 데이터를 증폭/축소해서 class 불균형 해소
* imbalanced-learn, smote/cluster-centroids
* 머신러닝 알고리즘을 통해 비슷한 데이터를 생성 / 축소
* **반드시 train 데이터에만 적용할 것**

In [167]:
X_train.value_counts()

age  capital-gain  capital-loss  education-num  marital-status_ Married-AF-spouse  marital-status_ Married-civ-spouse  marital-status_ Married-spouse-absent  marital-status_ Never-married  marital-status_ Separated  marital-status_ Widowed  sex_ Male  occupation_ Armed-Forces  occupation_ Craft-repair  occupation_ Exec-managerial  occupation_ Farming-fishing  occupation_ Handlers-cleaners  occupation_ Machine-op-inspct  occupation_ Other-service  occupation_ Priv-house-serv  occupation_ Prof-specialty  occupation_ Protective-serv  occupation_ Sales  occupation_ Tech-support  occupation_ Transport-moving
20   0             0             10             False                              False                               False                                  True                           False                      False                    False      False                     False                     False                        False                        False                          False                          False                      False                        False                       False                        False              False                     False                           28
21   0             0             10             False                              False                               False                                  True                           False                      False                    False      False                     False                     False                        False                        False                          False                          False                      False                        False                       False                        False              False                     False                           25
                                                                                                                                                                                                                                                                                                                                                                                                                                        True                       False                        False                       False                        False              False                     False                           24
                                 9              False                              False                               False                                  True                           False                      False                    False      False                     False                     False                        False                        False                          False                          True                       False                        False                       False                        False              False                     False                           21
36   0             0             9              False                              True                                False                                  False                          False                      False                    True       False                     True                      False                        False                        False                          False                          False                      False                        False                       False                        False              False                     False                           21
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ..
17   0             0             5              False                              False                               False                                  True                           False                      False                    True       False                     False                     False                        False                        False                          False                          False                      False                        False                       False                        False              False                     True                             1
                                 4              False                              False                               False                                  True                           False                      False                    True       False                     True                      False                        False                        False                          False                          False                      False                        False                       False                        False              False                     False                            1
                                                                                                                                                                                                                                                                                      False                     False                        True                         False                          False                          False                      False                        False                       False                        False              False                     False                            1
                                                                                                                                                                                                                                                                                                                                             False                        False                          False                          True                       False                        False                       False                        False              False                     False                            1
                                 3              False                              False                               False                                  True                           False                      False                    True       False                     False                     False                        False                        False                          False                          True                       False                        False                       False                        False              False                     False                            1
Name: count, Length: 13198, dtype: int64

In [165]:
from imblearn.over_sampling import SMOTENC

In [169]:
smt = SMOTENC(categorical_features=[4:], k_neighbors=5, random_state=10, n_jobs=-1)
smt_X, smt_y = smt.fit_resampe(X_train, y_train)

SyntaxError: invalid syntax (2983025405.py, line 1)

# K-FOLD, 하이퍼파라미터 튜닝
* K-FOLD 교차검증: 훈련에 사용할 데이터를 여러가지로 나누어서 편향을 줄이고 모델을 균형잡히게 하는 방법
* 하이퍼파라미터튜닝 : 머신러닝 알고리즘에 있는 여러 파라미터를 조정해서 최고의 성능을 내는 모델을 만드는것.
* max_depth, n_estimators, learning_rate
* gridsearch, randomsearch

gridSearch에서 score 기준 변경하기
* scoring=[accuracy, precision , recall, f1, roc_auc]

In [ ]:
grid_cv = GridSearchCV(model, param_)

# randomSearch

In [ ]:
rand_cv = RandomizedSearchCV(xgb, paramdistributions=xgb_params,
                            cv=3, scoring='roc')