# KNN_SVM_프로모션_효율예측분석

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [3]:
mem = pd.read_csv("./data/member.csv")
tran = pd.read_csv("./data/transaction.csv")

* 쇼핑몰 고객 데이터, 프로모션 쿠폰을 발행하고 사용 여부 데이터 수집
* mem : 고객id, 최근방문일, 사는지역, 추천여부, 주요접속채널, 쿠폰사용여부(target의)
* tran : 고객id, 구매수량, 총 구매금액
* 전통적 마케팅 분석 방법 RFM 기법을 활용해 고객 데이터에서 파생변수 생성 후 분석
* R : Recency. 현재일 - 최근 구매일
* F : Frequency. 구매빈도
* M : Monetary. 구매금액
* 종속변수 : conversion => 고객이 프로모션에 반응했는지의 여부. 1: yes, 0: no

In [4]:
mem.head(2)

       id  recency   zip_code  is_referral channel  conversion
0  906145       10  Surburban            0   Phone           0
1  184478        6      Rural            1     Web           0

In [5]:
tran.head(2)

       id  num_item  total_amount
0  906145         5         34000
1  906145         1         27000

# KNN, SVM

In [2]:
max_X_train.columns

NameError: name 'max_X_train' is not defined

In [1]:
from imblearn.over_sampling import SMOTENC

In [ ]:
smotenc = SMOTENC(categorical_features=)

In [3]:
from sklearn.svm import SVC

In [4]:
svc = SVC()