In [3]:
from konlpy.tag import Mecab
mecab = Mecab()
print(mecab.morphs(u'영등포구청역에 있는 맛집 좀 알려주세요.'))
print(mecab.nouns(u'영등포구청역에 있는 맛집 좀 알려주세요.'))
print(mecab.pos(u'영등포구청역에 있는 맛집 좀 알려주세요.'))

['영등포구청역', '에', '있', '는', '맛집', '좀', '알려', '주', '세요', '.']
['영등포구청역', '맛집']
[('영등포구청역', 'NNP'), ('에', 'JKB'), ('있', 'VV'), ('는', 'ETM'), ('맛집', 'NNG'), ('좀', 'MAG'), ('알려', 'VV+EC'), ('주', 'VX'), ('세요', 'EP+EF'), ('.', 'SF')]

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [36]:
train_df = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/ratings_train.txt", sep="\t")

In [37]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [38]:
test_df = pd.read_csv("./data/ratings_test.csv.txt", sep="\t")
test_df.head()

        id                                           document  label
0  6270596                                                굳 ㅋ      1
1  9274899                               GDNTOPCLASSINTHECLUB      0
2  8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3  6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4  6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0

In [39]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        50000 non-null  int64
 1   document  49997 non-null  object
 2   label     50000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

In [40]:
test_df['label'].value_counts()

label
1    25173
0    24827
Name: count, dtype: int64

In [41]:
test_df = test_df.dropna()
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49997 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        49997 non-null  int64
 1   document  49997 non-null  object
 2   label     49997 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.5+ MB

In [42]:
train_df = test_df.dropna()
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49997 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        49997 non-null  int64
 1   document  49997 non-null  object
 2   label     49997 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.5+ MB

In [43]:
train_df['document']

0                                                      굳 ㅋ
1                                     GDNTOPCLASSINTHECLUB
2                   뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아
3                         지루하지는 않은데 완전 막장임... 돈주고 보기에는....
4        3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??
                               ...
49995            오랜만에 평점 로긴했네ㅋㅋ 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함
49996         의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO
49997                   그림도 좋고 완성도도 높았지만... 보는 내내 불안하게 만든다
49998       절대 봐서는 안 될 영화.. 재미도 없고 기분만 잡치고.. 한 세트장에서 다 해먹네
49999                                           마무리는 또 왜이래
Name: document, Length: 49997, dtype: object

* 정규표현식을 이용한 텍스트 정리

In [44]:
import re

In [45]:
def text_clean(x):
    pattern = r'[가-힣0-9a-zA-Z]+'
    matches = re.findall(pattern, x)
    matches = " ".join(matches)
    return matches

In [46]:
train_df['document'] = train_df['document'].apply(text_clean)

In [47]:
train_df

            id                                       document  label
0      6270596                                              굳      1
1      9274899                           GDNTOPCLASSINTHECLUB      0
2      8544678             뭐야 이 평점들은 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3      6825595                      지루하지는 않은데 완전 막장임 돈주고 보기에는      0
4      6723715  3D만 아니었어도 별 다섯 개 줬을텐데 왜 3D로 나와서 제 심기를 불편하게 하죠      0
...        ...                                            ...    ...
49995  4608761        오랜만에 평점 로긴했네 킹왕짱 쌈뽕한 영화를 만났습니다 강렬하게 육쾌함      1
49996  5308387   의지 박약들이나 하는거다 탈영은 일단 주인공 김대희 닮았고 이등병 찐따 OOOO      0
49997  9072549                그림도 좋고 완성도도 높았지만 보는 내내 불안하게 만든다      0
49998  5802125     절대 봐서는 안 될 영화 재미도 없고 기분만 잡치고 한 세트장에서 다 해먹네      0
49999  6070594                                     마무리는 또 왜이래      0

[49997 rows x 3 columns]

In [48]:
X = train_df['document']
y = train_df['label']

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state=10)

* document에 있는 문자를 숫자로 변환
* 문자를 벡터화
* CountVectorizer()

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
cv = CountVectorizer() # 토크나이저가 공백을 기준으로 토큰화

In [54]:
cv.fit(X_train)
X_train = cv.transform(X_train)
X_valid = cv.transform(X_valid)

* 독립변수가 문자로 되어 있는 데이터의 경우 MultinominalNB

In [55]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [56]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
pred = mnb.predict(X_valid)
print(classification_report(y_valid, pred))

              precision    recall  f1-score   support

           0       0.84      0.74      0.79      7439
           1       0.77      0.86      0.81      7561

    accuracy                           0.80     15000
   macro avg       0.81      0.80      0.80     15000
weighted avg       0.80      0.80      0.80     15000

* test 데이터 불러와서 검증

In [58]:
X_test = test_df['document']
y_test = test_df['label']

In [59]:
X_test = cv.transform(X_test)

In [60]:
test_pred = mnb.predict(X_test)
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.93      0.88      0.90     24826
           1       0.89      0.94      0.91     25171

    accuracy                           0.91     49997
   macro avg       0.91      0.91      0.91     49997
weighted avg       0.91      0.91      0.91     49997