# 딥러닝 라이브러리 2가지
## 텐서플로우(google) - 산업용
* 이미지 관련 라이브러리
* keras를 이용해 코딩이 쉬움
* 순차적, 함수적, 클래스

## 파이토치(meta) - 연구용
* 자연어 관련 라이브러리
* 허깅페이스, 랭체인
* 클래스

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [22]:
data = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/Taitanic_train.csv")
data.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [23]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [24]:
data = data[['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked']]

In [25]:
data.head(2)

   Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C

In [26]:
data['family'] = data["SibSp"] + data['Parch']
data

     Survived  Pclass     Sex   Age  SibSp  Parch Embarked  family
0           0       3    male  22.0      1      0        S       1
1           1       1  female  38.0      1      0        C       1
2           1       3  female  26.0      0      0        S       0
3           1       1  female  35.0      1      0        S       1
4           0       3    male  35.0      0      0        S       0
..        ...     ...     ...   ...    ...    ...      ...     ...
886         0       2    male  27.0      0      0        S       0
887         1       1  female  19.0      0      0        S       0
888         0       3  female   NaN      1      2        S       3
889         1       1    male  26.0      0      0        C       0
890         0       3    male  32.0      0      0        Q       0

[891 rows x 8 columns]

In [27]:
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [28]:
data.loc[:, 'Age'] = data['Age'].fillna(data['Age'].mean())
data

     Survived  Pclass     Sex        Age  SibSp  Parch Embarked  family
0           0       3    male  22.000000      1      0        S       1
1           1       1  female  38.000000      1      0        C       1
2           1       3  female  26.000000      0      0        S       0
3           1       1  female  35.000000      1      0        S       1
4           0       3    male  35.000000      0      0        S       0
..        ...     ...     ...        ...    ...    ...      ...     ...
886         0       2    male  27.000000      0      0        S       0
887         1       1  female  19.000000      0      0        S       0
888         0       3  female  29.699118      1      2        S       3
889         1       1    male  26.000000      0      0        C       0
890         0       3    male  32.000000      0      0        Q       0

[891 rows x 8 columns]

In [29]:
data['Embarked'].mode()[0]

'S'

In [30]:
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Embarked  891 non-null    object
 7   family    891 non-null    int64
dtypes: float64(1), int64(5), object(2)
memory usage: 55.8+ KB

In [32]:
data = data.drop(['SibSp', 'Parch'], axis=1)
data

     Survived  Pclass     Sex        Age Embarked  family
0           0       3    male  22.000000        S       1
1           1       1  female  38.000000        C       1
2           1       3  female  26.000000        S       0
3           1       1  female  35.000000        S       1
4           0       3    male  35.000000        S       0
..        ...     ...     ...        ...      ...     ...
886         0       2    male  27.000000        S       0
887         1       1  female  19.000000        S       0
888         0       3  female  29.699118        S       3
889         1       1    male  26.000000        C       0
890         0       3    male  32.000000        Q       0

[891 rows x 6 columns]

In [33]:
data = pd.get_dummies(data, drop_first=True)
data

     Survived  Pclass        Age  family  Sex_male  Embarked_Q  Embarked_S
0           0       3  22.000000       1      True       False        True
1           1       1  38.000000       1     False       False       False
2           1       3  26.000000       0     False       False        True
3           1       1  35.000000       1     False       False        True
4           0       3  35.000000       0      True       False        True
..        ...     ...        ...     ...       ...         ...         ...
886         0       2  27.000000       0      True       False        True
887         1       1  19.000000       0     False       False        True
888         0       3  29.699118       3     False       False        True
889         1       1  26.000000       0      True       False       False
890         0       3  32.000000       0      True        True       False

[891 rows x 7 columns]

In [34]:
X = data.drop('Survived', axis=1)
y = data['Survived']

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# 딥러닝시에도 데이터의 스케일을 맞춰 주는것이 좋다.
* StandardScaler, MinMaxScaler를 주로 사용, 이상값이 많을 경우 RobustScaler를 사용
* 이진분류(0,1): MinMaxScaler
* 연속값예측: StandardScaler

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
mms = MinMaxScaler()
mms_X_train = mms.fit_transform(X_train)
mms_X_test = mms.transform(X_test)
mms_X_train = pd.DataFrame(mms_X_train, columns=X_train.columns, index=X_train.index)
mms_X_test = pd.DataFrame(mms_X_test, columns=X_test.columns, index=X_test.index)
display(mms_X_train)
display(mms_X_test)

     Pclass       Age  family  Sex_male  Embarked_Q  Embarked_S
748     0.0  0.233476     0.1       1.0         0.0         1.0
45      1.0  0.367921     0.0       1.0         0.0         1.0
28      1.0  0.367921     0.0       0.0         1.0         0.0
633     0.0  0.367921     0.0       1.0         0.0         1.0
403     1.0  0.346569     0.1       1.0         0.0         1.0
..      ...       ...     ...       ...         ...         ...
476     0.5  0.421965     0.1       1.0         0.0         1.0
190     0.5  0.396833     0.0       0.0         0.0         1.0
736     1.0  0.597889     0.4       0.0         0.0         1.0
462     0.0  0.585323     0.0       1.0         0.0         1.0
136     0.0  0.233476     0.2       0.0         0.0         1.0

[623 rows x 6 columns]

     Pclass       Age  family  Sex_male  Embarked_Q  Embarked_S
625     0.0  0.761247     0.0       1.0         0.0         1.0
566     1.0  0.233476     0.0       1.0         0.0         1.0
459     1.0  0.367921     0.0       1.0         1.0         0.0
804     1.0  0.334004     0.0       1.0         0.0         1.0
338     1.0  0.560191     0.0       1.0         0.0         1.0
..      ...       ...     ...       ...         ...         ...
184     1.0  0.044986     0.2       0.0         0.0         1.0
607     0.0  0.334004     0.0       1.0         0.0         1.0
624     1.0  0.258608     0.0       1.0         0.0         1.0
103     1.0  0.409399     0.0       1.0         0.0         1.0
387     0.5  0.447097     0.0       0.0         0.0         1.0

[268 rows x 6 columns]

# Tensorflow Sequential API를 사용한 순차적 모델 생성 및 분석
* Sequential: 인공신경망을 순차적으로 작성할 때 사용
* Dense: 층, 레이어

In [43]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# 신경망 모델 정의