# 가상환경 tf에서 진행중임

# 04_다중클래스분류_callback사용해서_과적합막고_최고성능모델_저장하기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [2]:
data = pd.read_csv("./data/winequality-white.csv", sep=";")
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [3]:
data['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

In [5]:
X = data.drop('quality', axis=1)
y = data['quality']

In [6]:
X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9
...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8

In [7]:
y = pd.get_dummies(y)
y

          3      4      5      6      7      8      9
0     False  False  False   True  False  False  False
1     False  False  False   True  False  False  False
2     False  False  False   True  False  False  False
3     False  False  False   True  False  False  False
4     False  False  False   True  False  False  False
...     ...    ...    ...    ...    ...    ...    ...
4893  False  False  False   True  False  False  False
4894  False  False   True  False  False  False  False
4895  False  False  False   True  False  False  False
4896  False  False  False  False   True  False  False
4897  False  False  False   True  False  False  False

[4898 rows x 7 columns]

In [8]:
data['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [9]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.4, stratify=y, random_state=42)
X_valid, X_test, y_valid, y_test = train_test_split(X_valid, y_valid, test_size=0.5, stratify=y_valid, random_state=42)

In [10]:
rs = RobustScaler()
train_temp = rs.fit_transform(X_train)
valid_temp = rs.transform(X_valid)
test_temp = rs.transform(X_test)
rs_X_train = pd.DataFrame(train_temp, columns=X_train.columns, index=X_train.index)
rs_X_valid = pd.DataFrame(valid_temp, columns=X_valid.columns, index=X_valid.index)
rs_X_test = pd.DataFrame(test_temp, columns=X_test.columns, index=X_test.index)

In [11]:
rs_X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
3940,0.090909,1.272727,0.416667,0.451220,0.714286,0.090909,0.216667,0.507205,-0.05,0.142857,-0.578947
3905,-0.272727,0.636364,-0.166667,-0.170732,-0.500000,0.000000,-0.783333,-0.811527,0.40,1.071429,1.105263
53,-0.363636,-0.727273,0.250000,-0.512195,0.142857,0.227273,-0.450000,-0.622478,0.70,-0.928571,0.263158
2576,-0.272727,0.090909,0.666667,0.585366,-0.285714,1.818182,1.533333,0.465706,0.05,0.142857,-0.526316
1970,1.363636,2.090909,0.916667,-0.329268,-0.500000,-0.090909,-0.316667,0.138329,0.30,-0.071429,0.157895
...,...,...,...,...,...,...,...,...,...,...,...
2609,0.272727,-0.545455,-0.166667,-0.524390,-1.714286,-1.363636,-1.783333,-1.035159,0.15,-0.857143,0.842105
2530,-0.909091,0.363636,-1.666667,-0.439024,-0.500000,1.045455,0.466667,-0.325072,1.05,0.785714,0.052632
1231,1.000000,1.363636,0.416667,-0.085366,-0.928571,0.272727,-0.350000,-0.414986,0.00,0.428571,1.052632
3948,-1.000000,-1.090909,-0.166667,0.024390,0.142857,-0.363636,-0.500000,0.205187,0.75,-0.214286,-0.578947
2460,-0.181818,0.636364,-0.666667,1.323171,0.142857,-0.136364,0.200000,1.019020,-0.45,0.285714,-0.631579

In [12]:
y_train

          3      4      5      6      7      8      9
3940  False  False   True  False  False  False  False
3905  False  False  False  False   True  False  False
53    False  False  False   True  False  False  False
2576  False  False   True  False  False  False  False
1970  False  False  False   True  False  False  False
...     ...    ...    ...    ...    ...    ...    ...
2609  False  False  False   True  False  False  False
2530  False  False  False   True  False  False  False
1231  False  False  False  False   True  False  False
3948  False  False   True  False  False  False  False
2460  False  False   True  False  False  False  False

[2938 rows x 7 columns]

In [13]:
y_train.shape[1]

7

# 모델을 최고 성능에서 저장하고 중지하기

In [41]:
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.callbacks import EarlyStopping, ModelCheckpoint

In [42]:
data['quality'].nunique()

7

In [43]:
n_class = y_train.shape[1]
model = Sequential()
model.add(Input(shape=(rs_X_train.shape[1],)))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(n_class, activation='softmax'))
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 7)              │           119 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,495 (13.65 KB)

 Trainable params: 3,495 (13.65 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
import os

In [46]:
model.compile(loss="categorical_crossentropy", optimizer='adam', metrics=['accuracy'])
early_stop = EarlyStopping(patience=1000)
os.makedirs("./model", exist_ok=True) # 디렉토리자동생성
filepath = "./model/whitewine_loss:{val_loss:04f}_epoch_{epoch:04d}_.keras"
model_save = ModelCheckpoint(filepath=filepath, save_best_only=True)
history = model.fit(rs_X_train, y_train, epochs=10000, batch_size=32, validation_data=(rs_X_valid, y_valid),
                    callbacks=[early_stop, model_save])

plt.figure(figsize=(8,5))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.xlabel("epochs")
plt.ylabel("loss")
plt.legend(['train', 'valid'])
plt.show()

Epoch 1/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.9838 - loss: 0.0540 - val_accuracy: 0.5796 - val_loss: 7.0497
Epoch 2/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9889 - loss: 0.0354 - val_accuracy: 0.5776 - val_loss: 7.0812
Epoch 3/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9840 - loss: 0.0567 - val_accuracy: 0.5867 - val_loss: 7.0660
Epoch 4/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9828 - loss: 0.0627 - val_accuracy: 0.5735 - val_loss: 7.0889
Epoch 5/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9789 - loss: 0.0613 - val_accuracy: 0.5796 - val_loss: 7.1264
Epoch 6/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9946 - loss: 0.0232 - val_accuracy: 0.5878 - val_loss: 7.0598
Epoch 7/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0172 - val_accuracy: 0.5878 - val_loss: 7.0395
Epoch 8/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9971 - loss: 0.0161 - val_accuracy: 0.5878 - val_loss: 7.0796
Epoch 9/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9945 - loss: 0.0272 - val_accuracy: 0.5847 - val_loss: 7.0637
Epoch 10/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0164 - val_accuracy: 0.5745 - val_loss: 7.1130
Epoch 11/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9761 - loss: 0.0724 - val_accuracy: 0.5735 - val_loss: 7.2963
Epoch 12/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9685 - loss: 0.0882 - val_accuracy: 0.5776 - val_loss: 7.2709
Epoch 13/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9440 - loss: 0.1544 - val_accuracy: 0.5837 - val_loss: 7.0489
Epoch 14/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9810 - loss: 0.0592 - val_accuracy: 0.5857 - val_loss: 7.1328
Epoch 15/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9885 - loss: 0.0436 - val_accuracy: 0.5898 - val_loss: 7.1030
Epoch 16/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0178 - val_accuracy: 0.5959 - val_loss: 7.0405
Epoch 17/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0124 - val_accuracy: 0.5786 - val_loss: 7.0777
Epoch 18/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0195 - val_accuracy: 0.5837 - val_loss: 7.0466
Epoch 19/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9955 - loss: 0.0187 - val_accuracy: 0.5857 - val_loss: 7.0000
Epoch 20/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9961 - loss: 0.0202 - val_accuracy: 0.5847 - val_loss: 7.0013
Epoch 21/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9942 - loss: 0.0343 - val_accuracy: 0.5898 - val_loss: 7.0243
Epoch 22/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0218 - val_accuracy: 0.5837 - val_loss: 7.0535
Epoch 23/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9893 - loss: 0.0333 - val_accuracy: 0.5867 - val_loss: 7.1117
Epoch 24/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9909 - loss: 0.0406 - val_accuracy: 0.5755 - val_loss: 7.3074
Epoch 25/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9816 - loss: 0.0536 - val_accuracy: 0.5837 - val_loss: 7.1710
Epoch 26/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9539 - loss: 0.1615 - val_accuracy: 0.5878 - val_loss: 7.2165
Epoch 27/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9655 - loss: 0.1067 - val_accuracy: 0.5735 - val_loss: 7.2625
Epoch 28/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9823 - loss: 0.0612 - val_accuracy: 0.5898 - val_loss: 7.0410
Epoch 29/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9957 - loss: 0.0233 - val_accuracy: 0.5806 - val_loss: 7.1471
Epoch 30/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9925 - loss: 0.0281 - val_accuracy: 0.5847 - val_loss: 7.0831
Epoch 31/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9929 - loss: 0.0331 - val_accuracy: 0.5888 - val_loss: 7.1768
Epoch 32/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0417 - val_accuracy: 0.5939 - val_loss: 7.1306
Epoch 33/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9958 - loss: 0.0288 - val_accuracy: 0.5878 - val_loss: 7.1982
Epoch 34/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0154 - val_accuracy: 0.5857 - val_loss: 7.1693
Epoch 35/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0145 - val_accuracy: 0.5959 - val_loss: 7.1438
Epoch 36/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0222 - val_accuracy: 0.5755 - val_loss: 7.2258
Epoch 37/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0183 - val_accuracy: 0.5867 - val_loss: 7.2088
Epoch 38/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9984 - loss: 0.0112 - val_accuracy: 0.5898 - val_loss: 7.0960
Epoch 39/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9951 - loss: 0.0178 - val_accuracy: 0.5857 - val_loss: 7.1518
Epoch 40/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9931 - loss: 0.0307 - val_accuracy: 0.5714 - val_loss: 7.3862
Epoch 41/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9398 - loss: 0.2210 - val_accuracy: 0.5714 - val_loss: 7.2786
Epoch 42/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9650 - loss: 0.1103 - val_accuracy: 0.5633 - val_loss: 7.3081
Epoch 43/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9699 - loss: 0.0802 - val_accuracy: 0.5949 - val_loss: 7.0282
Epoch 44/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9866 - loss: 0.0420 - val_accuracy: 0.5867 - val_loss: 7.1121
Epoch 45/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0159 - val_accuracy: 0.5827 - val_loss: 7.1940
Epoch 46/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0181 - val_accuracy: 0.5898 - val_loss: 7.1426
Epoch 47/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9961 - loss: 0.0249 - val_accuracy: 0.5867 - val_loss: 7.1832
Epoch 48/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9930 - loss: 0.0371 - val_accuracy: 0.5816 - val_loss: 7.1384
Epoch 49/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9974 - loss: 0.0137 - val_accuracy: 0.5878 - val_loss: 7.1763
Epoch 50/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0110 - val_accuracy: 0.5888 - val_loss: 7.1221
Epoch 51/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9981 - loss: 0.0205 - val_accuracy: 0.5776 - val_loss: 7.2866
Epoch 52/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9916 - loss: 0.0447 - val_accuracy: 0.5857 - val_loss: 7.1352
Epoch 53/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9937 - loss: 0.0365 - val_accuracy: 0.5857 - val_loss: 7.2678
Epoch 54/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9916 - loss: 0.0262 - val_accuracy: 0.5908 - val_loss: 7.2735
Epoch 55/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9869 - loss: 0.0473 - val_accuracy: 0.5878 - val_loss: 7.3397
Epoch 56/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9746 - loss: 0.0865 - val_accuracy: 0.5694 - val_loss: 7.3757
Epoch 57/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9499 - loss: 0.1500 - val_accuracy: 0.5653 - val_loss: 7.5537
Epoch 58/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9490 - loss: 0.1498 - val_accuracy: 0.5898 - val_loss: 7.3429
Epoch 59/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9729 - loss: 0.0882 - val_accuracy: 0.5816 - val_loss: 7.2227
Epoch 60/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9927 - loss: 0.0278 - val_accuracy: 0.5796 - val_loss: 7.4133
Epoch 61/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9925 - loss: 0.0321 - val_accuracy: 0.5908 - val_loss: 7.2491
Epoch 62/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9930 - loss: 0.0277 - val_accuracy: 0.5939 - val_loss: 7.2054
Epoch 63/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9944 - loss: 0.0290 - val_accuracy: 0.5827 - val_loss: 7.2953
Epoch 64/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9954 - loss: 0.0242 - val_accuracy: 0.5908 - val_loss: 7.1521
Epoch 65/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0214 - val_accuracy: 0.5908 - val_loss: 7.3778
Epoch 66/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9893 - loss: 0.0423 - val_accuracy: 0.5929 - val_loss: 7.1643
Epoch 67/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9774 - loss: 0.0828 - val_accuracy: 0.5735 - val_loss: 7.3643
Epoch 68/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9835 - loss: 0.0580 - val_accuracy: 0.5888 - val_loss: 7.3182
Epoch 69/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9866 - loss: 0.0572 - val_accuracy: 0.5806 - val_loss: 7.2770
Epoch 70/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9904 - loss: 0.0314 - val_accuracy: 0.5827 - val_loss: 7.3769
Epoch 71/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9857 - loss: 0.0404 - val_accuracy: 0.5796 - val_loss: 7.2981
Epoch 72/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9954 - loss: 0.0314 - val_accuracy: 0.5827 - val_loss: 7.3400
Epoch 73/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9877 - loss: 0.0452 - val_accuracy: 0.5847 - val_loss: 7.4402
Epoch 74/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9644 - loss: 0.1095 - val_accuracy: 0.5806 - val_loss: 7.2976
Epoch 75/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9701 - loss: 0.1018 - val_accuracy: 0.5796 - val_loss: 7.2914
Epoch 76/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9858 - loss: 0.0481 - val_accuracy: 0.5867 - val_loss: 7.2125
Epoch 77/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0238 - val_accuracy: 0.5724 - val_loss: 7.2973
Epoch 78/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0175 - val_accuracy: 0.5867 - val_loss: 7.2658
Epoch 79/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9915 - loss: 0.0357 - val_accuracy: 0.5765 - val_loss: 7.1759
Epoch 80/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9919 - loss: 0.0317 - val_accuracy: 0.5755 - val_loss: 7.2962
Epoch 81/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9921 - loss: 0.0303 - val_accuracy: 0.5755 - val_loss: 7.2451
Epoch 82/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9889 - loss: 0.0384 - val_accuracy: 0.5786 - val_loss: 7.4730
Epoch 83/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9929 - loss: 0.0255 - val_accuracy: 0.5765 - val_loss: 7.3381
Epoch 84/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0174 - val_accuracy: 0.5827 - val_loss: 7.2252
Epoch 85/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9951 - loss: 0.0321 - val_accuracy: 0.5765 - val_loss: 7.4253
Epoch 86/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9849 - loss: 0.0522 - val_accuracy: 0.5857 - val_loss: 7.3317
Epoch 87/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9930 - loss: 0.0252 - val_accuracy: 0.5867 - val_loss: 7.3797
Epoch 88/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9828 - loss: 0.0568 - val_accuracy: 0.5857 - val_loss: 7.2631
Epoch 89/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9851 - loss: 0.0422 - val_accuracy: 0.5857 - val_loss: 7.2149
Epoch 90/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9749 - loss: 0.0716 - val_accuracy: 0.5704 - val_loss: 7.4729
Epoch 91/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9745 - loss: 0.0888 - val_accuracy: 0.5643 - val_loss: 7.3959
Epoch 92/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9531 - loss: 0.1516 - val_accuracy: 0.5612 - val_loss: 7.5279
Epoch 93/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9416 - loss: 0.1795 - val_accuracy: 0.5878 - val_loss: 7.3291
Epoch 94/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9814 - loss: 0.0533 - val_accuracy: 0.5837 - val_loss: 7.3801
Epoch 95/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9957 - loss: 0.0191 - val_accuracy: 0.5837 - val_loss: 7.3632
Epoch 96/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9978 - loss: 0.0168 - val_accuracy: 0.5837 - val_loss: 7.3803
Epoch 97/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9904 - loss: 0.0439 - val_accuracy: 0.5827 - val_loss: 7.4279
Epoch 98/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0216 - val_accuracy: 0.5857 - val_loss: 7.3267
Epoch 99/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0156 - val_accuracy: 0.5827 - val_loss: 7.4414
Epoch 100/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0202 - val_accuracy: 0.5857 - val_loss: 7.3610
Epoch 101/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0108 - val_accuracy: 0.5796 - val_loss: 7.4173
Epoch 102/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0236 - val_accuracy: 0.5776 - val_loss: 7.4605
Epoch 103/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9942 - loss: 0.0355 - val_accuracy: 0.5806 - val_loss: 7.4454
Epoch 104/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0143 - val_accuracy: 0.5857 - val_loss: 7.3825
Epoch 105/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9878 - loss: 0.0398 - val_accuracy: 0.5827 - val_loss: 7.4802
Epoch 106/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9698 - loss: 0.0978 - val_accuracy: 0.5673 - val_loss: 7.4836
Epoch 107/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9832 - loss: 0.0514 - val_accuracy: 0.5673 - val_loss: 7.5708
Epoch 108/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9792 - loss: 0.0654 - val_accuracy: 0.5867 - val_loss: 7.4670
Epoch 109/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9867 - loss: 0.0478 - val_accuracy: 0.5857 - val_loss: 7.5108
Epoch 110/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9820 - loss: 0.0545 - val_accuracy: 0.5765 - val_loss: 7.4569
Epoch 111/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9862 - loss: 0.0514 - val_accuracy: 0.5827 - val_loss: 7.3238
Epoch 112/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9899 - loss: 0.0357 - val_accuracy: 0.5867 - val_loss: 7.3134
Epoch 113/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9961 - loss: 0.0274 - val_accuracy: 0.5816 - val_loss: 7.3840
Epoch 114/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9957 - loss: 0.0243 - val_accuracy: 0.5816 - val_loss: 7.3479
Epoch 115/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9919 - loss: 0.0269 - val_accuracy: 0.5959 - val_loss: 7.4153
Epoch 116/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9948 - loss: 0.0311 - val_accuracy: 0.5908 - val_loss: 7.3680
Epoch 117/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0181 - val_accuracy: 0.5776 - val_loss: 7.4653
Epoch 118/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0183 - val_accuracy: 0.5827 - val_loss: 7.4984
Epoch 119/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0254 - val_accuracy: 0.5908 - val_loss: 7.4585
Epoch 120/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0157 - val_accuracy: 0.5959 - val_loss: 7.4817
Epoch 121/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9919 - loss: 0.0393 - val_accuracy: 0.5929 - val_loss: 7.3659
Epoch 122/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9810 - loss: 0.0603 - val_accuracy: 0.5918 - val_loss: 7.3794
Epoch 123/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9501 - loss: 0.1688 - val_accuracy: 0.5571 - val_loss: 7.6863
Epoch 124/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9571 - loss: 0.1180 - val_accuracy: 0.5745 - val_loss: 7.6035
Epoch 125/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9688 - loss: 0.1012 - val_accuracy: 0.5684 - val_loss: 7.4988
Epoch 126/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9876 - loss: 0.0482 - val_accuracy: 0.5806 - val_loss: 7.4074
Epoch 127/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9922 - loss: 0.0358 - val_accuracy: 0.5724 - val_loss: 7.5001
Epoch 128/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0172 - val_accuracy: 0.5857 - val_loss: 7.4439
Epoch 129/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0108 - val_accuracy: 0.5776 - val_loss: 7.4824
Epoch 130/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0125 - val_accuracy: 0.5898 - val_loss: 7.4566
Epoch 131/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0185 - val_accuracy: 0.5745 - val_loss: 7.4258
Epoch 132/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0144 - val_accuracy: 0.5806 - val_loss: 7.5099
Epoch 133/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0187 - val_accuracy: 0.5796 - val_loss: 7.4800
Epoch 134/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9931 - loss: 0.0262 - val_accuracy: 0.5776 - val_loss: 7.6582
Epoch 135/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9963 - loss: 0.0190 - val_accuracy: 0.5735 - val_loss: 7.5491
Epoch 136/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9930 - loss: 0.0414 - val_accuracy: 0.5786 - val_loss: 7.8849
Epoch 137/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9506 - loss: 0.1984 - val_accuracy: 0.5796 - val_loss: 7.9106
Epoch 138/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9533 - loss: 0.1753 - val_accuracy: 0.5918 - val_loss: 7.6129
Epoch 139/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9865 - loss: 0.0381 - val_accuracy: 0.5796 - val_loss: 7.5207
Epoch 140/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0145 - val_accuracy: 0.5888 - val_loss: 7.5604
Epoch 141/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9915 - loss: 0.0321 - val_accuracy: 0.5806 - val_loss: 7.5489
Epoch 142/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0142 - val_accuracy: 0.5806 - val_loss: 7.5139
Epoch 143/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9992 - loss: 0.0085 - val_accuracy: 0.5867 - val_loss: 7.5080
Epoch 144/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9952 - loss: 0.0230 - val_accuracy: 0.5847 - val_loss: 7.5072
Epoch 145/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0148 - val_accuracy: 0.5786 - val_loss: 7.5953
Epoch 146/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9890 - loss: 0.0361 - val_accuracy: 0.5806 - val_loss: 7.5590
Epoch 147/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9954 - loss: 0.0162 - val_accuracy: 0.5847 - val_loss: 7.5840
Epoch 148/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9847 - loss: 0.0575 - val_accuracy: 0.5755 - val_loss: 7.7854
Epoch 149/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9738 - loss: 0.0872 - val_accuracy: 0.5663 - val_loss: 7.5756
Epoch 150/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9523 - loss: 0.1663 - val_accuracy: 0.5786 - val_loss: 7.6433

Epoch 151/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9633 - loss: 0.1034 - val_accuracy: 0.5592 - val_loss: 7.8865
Epoch 152/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9665 - loss: 0.0911 - val_accuracy: 0.5633 - val_loss: 7.7031
Epoch 153/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9798 - loss: 0.0612 - val_accuracy: 0.5918 - val_loss: 7.5712
Epoch 154/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9921 - loss: 0.0282 - val_accuracy: 0.5959 - val_loss: 7.5166
Epoch 155/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0100 - val_accuracy: 0.5898 - val_loss: 7.5139
Epoch 156/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0111 - val_accuracy: 0.5857 - val_loss: 7.5343
Epoch 157/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0173 - val_accuracy: 0.5847 - val_loss: 7.5169
Epoch 158/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0156 - val_accuracy: 0.5939 - val_loss: 7.5390
Epoch 159/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0106 - val_accuracy: 0.5867 - val_loss: 7.5600
Epoch 160/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0352 - val_accuracy: 0.5898 - val_loss: 7.5407
Epoch 161/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9971 - loss: 0.0124 - val_accuracy: 0.5949 - val_loss: 7.5188
Epoch 162/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0089 - val_accuracy: 0.5918 - val_loss: 7.5652
Epoch 163/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0135 - val_accuracy: 0.5980 - val_loss: 7.4415
Epoch 164/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9910 - loss: 0.0495 - val_accuracy: 0.5663 - val_loss: 7.7412
Epoch 165/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9482 - loss: 0.1716 - val_accuracy: 0.5673 - val_loss: 7.7919
Epoch 166/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9447 - loss: 0.1822 - val_accuracy: 0.5776 - val_loss: 7.6124
Epoch 167/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9701 - loss: 0.1048 - val_accuracy: 0.5837 - val_loss: 7.5828
Epoch 168/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9779 - loss: 0.0642 - val_accuracy: 0.5745 - val_loss: 7.5354
Epoch 169/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9875 - loss: 0.0458 - val_accuracy: 0.5724 - val_loss: 7.6924
Epoch 170/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0298 - val_accuracy: 0.5806 - val_loss: 7.5684
Epoch 171/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9961 - loss: 0.0164 - val_accuracy: 0.5837 - val_loss: 7.5707
Epoch 172/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0118 - val_accuracy: 0.5827 - val_loss: 7.6121
Epoch 173/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0272 - val_accuracy: 0.5847 - val_loss: 7.5784
Epoch 174/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9976 - loss: 0.0155 - val_accuracy: 0.5837 - val_loss: 7.6147
Epoch 175/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9977 - loss: 0.0123 - val_accuracy: 0.5776 - val_loss: 7.6000
Epoch 176/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9963 - loss: 0.0147 - val_accuracy: 0.5755 - val_loss: 7.6333
Epoch 177/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9977 - loss: 0.0148 - val_accuracy: 0.5796 - val_loss: 7.6217
Epoch 178/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0178 - val_accuracy: 0.5786 - val_loss: 7.6178
Epoch 179/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0114 - val_accuracy: 0.5816 - val_loss: 7.6530
Epoch 180/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0179 - val_accuracy: 0.5755 - val_loss: 7.6053
Epoch 181/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9937 - loss: 0.0274 - val_accuracy: 0.5847 - val_loss: 7.6383
Epoch 182/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0222 - val_accuracy: 0.5847 - val_loss: 7.6926
Epoch 183/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0134 - val_accuracy: 0.5765 - val_loss: 7.6921
Epoch 184/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9923 - loss: 0.0289 - val_accuracy: 0.5694 - val_loss: 7.8381
Epoch 185/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9624 - loss: 0.1193 - val_accuracy: 0.5531 - val_loss: 8.0751
Epoch 186/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9351 - loss: 0.2456 - val_accuracy: 0.5500 - val_loss: 8.1307
Epoch 187/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9629 - loss: 0.1099 - val_accuracy: 0.5714 - val_loss: 7.7837
Epoch 188/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9871 - loss: 0.0412 - val_accuracy: 0.5837 - val_loss: 7.6288
Epoch 189/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0261 - val_accuracy: 0.5827 - val_loss: 7.7186
Epoch 190/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9904 - loss: 0.0347 - val_accuracy: 0.5898 - val_loss: 7.6448
Epoch 191/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0181 - val_accuracy: 0.5827 - val_loss: 7.7865
Epoch 192/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0134 - val_accuracy: 0.5786 - val_loss: 7.6871
Epoch 193/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0153 - val_accuracy: 0.5765 - val_loss: 7.6404
Epoch 194/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0077 - val_accuracy: 0.5796 - val_loss: 7.6599
Epoch 195/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9997 - loss: 0.0082 - val_accuracy: 0.5816 - val_loss: 7.6447
Epoch 196/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9969 - loss: 0.0123 - val_accuracy: 0.5888 - val_loss: 7.6301
Epoch 197/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0175 - val_accuracy: 0.5918 - val_loss: 7.5992
Epoch 198/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0166 - val_accuracy: 0.5796 - val_loss: 7.8673
Epoch 199/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9701 - loss: 0.0811 - val_accuracy: 0.5796 - val_loss: 7.7997
Epoch 200/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9671 - loss: 0.1204 - val_accuracy: 0.5724 - val_loss: 7.7231
Epoch 201/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9628 - loss: 0.1042 - val_accuracy: 0.5827 - val_loss: 7.7145
Epoch 202/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9840 - loss: 0.0459 - val_accuracy: 0.5908 - val_loss: 7.5806
Epoch 203/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9841 - loss: 0.0585 - val_accuracy: 0.5867 - val_loss: 7.6146
Epoch 204/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9964 - loss: 0.0174 - val_accuracy: 0.5898 - val_loss: 7.6266
Epoch 205/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0189 - val_accuracy: 0.5816 - val_loss: 7.6960
Epoch 206/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9957 - loss: 0.0311 - val_accuracy: 0.5867 - val_loss: 7.6201
Epoch 207/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9971 - loss: 0.0130 - val_accuracy: 0.5857 - val_loss: 7.7461
Epoch 208/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0214 - val_accuracy: 0.5786 - val_loss: 7.7264
Epoch 209/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0098 - val_accuracy: 0.5857 - val_loss: 7.6753
Epoch 210/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0121 - val_accuracy: 0.5878 - val_loss: 7.6697
Epoch 211/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9980 - loss: 0.0111 - val_accuracy: 0.5796 - val_loss: 7.7059
Epoch 212/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9909 - loss: 0.0450 - val_accuracy: 0.5765 - val_loss: 7.6619
Epoch 213/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0141 - val_accuracy: 0.5867 - val_loss: 7.7727
Epoch 214/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0141 - val_accuracy: 0.5888 - val_loss: 7.6519
Epoch 215/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0146 - val_accuracy: 0.5888 - val_loss: 7.6643
Epoch 216/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0147 - val_accuracy: 0.5827 - val_loss: 7.7476
Epoch 217/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9745 - loss: 0.0772 - val_accuracy: 0.5745 - val_loss: 8.0424
Epoch 218/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9540 - loss: 0.1532 - val_accuracy: 0.5796 - val_loss: 7.6482
Epoch 219/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9468 - loss: 0.1693 - val_accuracy: 0.5827 - val_loss: 7.6297
Epoch 220/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9803 - loss: 0.0704 - val_accuracy: 0.5786 - val_loss: 7.5379
Epoch 221/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9826 - loss: 0.0558 - val_accuracy: 0.5857 - val_loss: 7.7258
Epoch 222/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9956 - loss: 0.0225 - val_accuracy: 0.5878 - val_loss: 7.6028
Epoch 223/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9940 - loss: 0.0175 - val_accuracy: 0.5827 - val_loss: 7.6187
Epoch 224/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9936 - loss: 0.0174 - val_accuracy: 0.5867 - val_loss: 7.7030
Epoch 225/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0143 - val_accuracy: 0.5847 - val_loss: 7.7167
Epoch 226/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9988 - loss: 0.0098 - val_accuracy: 0.5857 - val_loss: 7.7246
Epoch 227/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9974 - loss: 0.0197 - val_accuracy: 0.5786 - val_loss: 7.7381
Epoch 228/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9936 - loss: 0.0269 - val_accuracy: 0.5888 - val_loss: 7.7186
Epoch 229/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9833 - loss: 0.0606 - val_accuracy: 0.5888 - val_loss: 7.6426
Epoch 230/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9885 - loss: 0.0349 - val_accuracy: 0.5745 - val_loss: 7.9057
Epoch 231/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9814 - loss: 0.0537 - val_accuracy: 0.5796 - val_loss: 7.7507
Epoch 232/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0249 - val_accuracy: 0.5837 - val_loss: 7.6603
Epoch 233/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9849 - loss: 0.0509 - val_accuracy: 0.5806 - val_loss: 7.8095
Epoch 234/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9799 - loss: 0.0781 - val_accuracy: 0.5857 - val_loss: 7.8041
Epoch 235/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9814 - loss: 0.0577 - val_accuracy: 0.5837 - val_loss: 7.8294
Epoch 236/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9832 - loss: 0.0715 - val_accuracy: 0.5837 - val_loss: 7.8739
Epoch 237/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9896 - loss: 0.0269 - val_accuracy: 0.5837 - val_loss: 7.6715
Epoch 238/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0122 - val_accuracy: 0.5959 - val_loss: 7.7120
Epoch 239/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0159 - val_accuracy: 0.5837 - val_loss: 7.7172
Epoch 240/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9990 - loss: 0.0086 - val_accuracy: 0.5867 - val_loss: 7.7904
Epoch 241/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0153 - val_accuracy: 0.5827 - val_loss: 7.7982
Epoch 242/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9856 - loss: 0.0555 - val_accuracy: 0.5745 - val_loss: 7.8478
Epoch 243/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9904 - loss: 0.0341 - val_accuracy: 0.5867 - val_loss: 7.9163
Epoch 244/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9769 - loss: 0.0728 - val_accuracy: 0.5480 - val_loss: 8.0884
Epoch 245/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9500 - loss: 0.1475 - val_accuracy: 0.5755 - val_loss: 8.0861
Epoch 246/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9672 - loss: 0.0923 - val_accuracy: 0.5806 - val_loss: 7.8452
Epoch 247/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9828 - loss: 0.0524 - val_accuracy: 0.5724 - val_loss: 7.7819
Epoch 248/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9860 - loss: 0.0555 - val_accuracy: 0.5714 - val_loss: 7.8822
Epoch 249/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9914 - loss: 0.0388 - val_accuracy: 0.5796 - val_loss: 7.8553

Epoch 250/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0287 - val_accuracy: 0.5786 - val_loss: 7.7938
Epoch 251/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9963 - loss: 0.0155 - val_accuracy: 0.5806 - val_loss: 7.7774
Epoch 252/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0096 - val_accuracy: 0.5765 - val_loss: 7.8239
Epoch 253/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0143 - val_accuracy: 0.5908 - val_loss: 7.8187
Epoch 254/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9974 - loss: 0.0127 - val_accuracy: 0.5847 - val_loss: 7.7713
Epoch 255/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0122 - val_accuracy: 0.5786 - val_loss: 7.8578
Epoch 256/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9993 - loss: 0.0099 - val_accuracy: 0.5867 - val_loss: 7.8360
Epoch 257/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0152 - val_accuracy: 0.5837 - val_loss: 7.8192
Epoch 258/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9960 - loss: 0.0154 - val_accuracy: 0.5694 - val_loss: 7.9224
Epoch 259/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9753 - loss: 0.0792 - val_accuracy: 0.5592 - val_loss: 8.1556
Epoch 260/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9488 - loss: 0.1564 - val_accuracy: 0.5551 - val_loss: 7.9297
Epoch 261/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9705 - loss: 0.1084 - val_accuracy: 0.5673 - val_loss: 7.7925
Epoch 262/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9869 - loss: 0.0467 - val_accuracy: 0.5857 - val_loss: 7.8492
Epoch 263/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9917 - loss: 0.0488 - val_accuracy: 0.5867 - val_loss: 7.8734
Epoch 264/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9928 - loss: 0.0381 - val_accuracy: 0.5837 - val_loss: 7.9256
Epoch 265/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9956 - loss: 0.0185 - val_accuracy: 0.5888 - val_loss: 7.7932
Epoch 266/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9953 - loss: 0.0257 - val_accuracy: 0.5898 - val_loss: 7.7816
Epoch 267/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9992 - loss: 0.0117 - val_accuracy: 0.5918 - val_loss: 7.7512
Epoch 268/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0145 - val_accuracy: 0.5949 - val_loss: 7.7339
Epoch 269/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0103 - val_accuracy: 0.5918 - val_loss: 7.7335
Epoch 270/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9964 - loss: 0.0194 - val_accuracy: 0.5888 - val_loss: 7.8612
Epoch 271/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9926 - loss: 0.0242 - val_accuracy: 0.5980 - val_loss: 7.7142
Epoch 272/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9994 - loss: 0.0073 - val_accuracy: 0.5878 - val_loss: 7.7487
Epoch 273/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0118 - val_accuracy: 0.5990 - val_loss: 7.7514
Epoch 274/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9953 - loss: 0.0136 - val_accuracy: 0.5898 - val_loss: 7.7945
Epoch 275/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0108 - val_accuracy: 0.5878 - val_loss: 7.8137
Epoch 276/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0077 - val_accuracy: 0.5908 - val_loss: 7.7977
Epoch 277/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9994 - loss: 0.0077 - val_accuracy: 0.5867 - val_loss: 7.7710
Epoch 278/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9750 - loss: 0.0986 - val_accuracy: 0.5765 - val_loss: 8.1734
Epoch 279/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9337 - loss: 0.2374 - val_accuracy: 0.5776 - val_loss: 7.7991
Epoch 280/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9513 - loss: 0.1867 - val_accuracy: 0.5765 - val_loss: 7.8981
Epoch 281/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9715 - loss: 0.0952 - val_accuracy: 0.5847 - val_loss: 7.8779
Epoch 282/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9887 - loss: 0.0349 - val_accuracy: 0.5776 - val_loss: 7.9046
Epoch 283/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9888 - loss: 0.0373 - val_accuracy: 0.5847 - val_loss: 7.8303
Epoch 284/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9951 - loss: 0.0199 - val_accuracy: 0.5837 - val_loss: 7.8152
Epoch 285/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0264 - val_accuracy: 0.5857 - val_loss: 7.8548
Epoch 286/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0136 - val_accuracy: 0.5939 - val_loss: 7.8394
Epoch 287/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0135 - val_accuracy: 0.5888 - val_loss: 7.8085
Epoch 288/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0231 - val_accuracy: 0.5827 - val_loss: 7.8148
Epoch 289/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0093 - val_accuracy: 0.5837 - val_loss: 7.8690
Epoch 290/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0119 - val_accuracy: 0.5796 - val_loss: 7.8231
Epoch 291/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0134 - val_accuracy: 0.5888 - val_loss: 7.8442
Epoch 292/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0166 - val_accuracy: 0.5837 - val_loss: 7.8348
Epoch 293/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0142 - val_accuracy: 0.5816 - val_loss: 7.8359
Epoch 294/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9778 - loss: 0.0847 - val_accuracy: 0.5755 - val_loss: 7.9269
Epoch 295/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9263 - loss: 0.2685 - val_accuracy: 0.5776 - val_loss: 8.0385
Epoch 296/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9568 - loss: 0.1286 - val_accuracy: 0.5847 - val_loss: 7.9421
Epoch 297/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9840 - loss: 0.0533 - val_accuracy: 0.5837 - val_loss: 7.8853
Epoch 298/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9937 - loss: 0.0186 - val_accuracy: 0.5888 - val_loss: 7.7909
Epoch 299/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0179 - val_accuracy: 0.5847 - val_loss: 7.8160
Epoch 300/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0212 - val_accuracy: 0.5847 - val_loss: 7.7861
Epoch 301/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0113 - val_accuracy: 0.5857 - val_loss: 7.8133
Epoch 302/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0102 - val_accuracy: 0.5755 - val_loss: 7.8471
Epoch 303/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0116 - val_accuracy: 0.5827 - val_loss: 7.8156
Epoch 304/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0105 - val_accuracy: 0.5806 - val_loss: 7.8053
Epoch 305/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9993 - loss: 0.0086 - val_accuracy: 0.5827 - val_loss: 7.9280
Epoch 306/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9940 - loss: 0.0299 - val_accuracy: 0.5867 - val_loss: 7.8084
Epoch 307/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9961 - loss: 0.0173 - val_accuracy: 0.5867 - val_loss: 7.8260
Epoch 308/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0144 - val_accuracy: 0.5837 - val_loss: 7.8564
Epoch 309/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0204 - val_accuracy: 0.5816 - val_loss: 7.8243
Epoch 310/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9919 - loss: 0.0314 - val_accuracy: 0.5878 - val_loss: 7.9093
Epoch 311/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9886 - loss: 0.0403 - val_accuracy: 0.5684 - val_loss: 8.0917
Epoch 312/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9693 - loss: 0.0992 - val_accuracy: 0.5735 - val_loss: 8.0426
Epoch 313/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9409 - loss: 0.2299 - val_accuracy: 0.5663 - val_loss: 8.1016
Epoch 314/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9596 - loss: 0.1446 - val_accuracy: 0.5837 - val_loss: 7.9516
Epoch 315/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9881 - loss: 0.0451 - val_accuracy: 0.5898 - val_loss: 7.8391
Epoch 316/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9961 - loss: 0.0164 - val_accuracy: 0.5857 - val_loss: 7.7260
Epoch 317/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9957 - loss: 0.0243 - val_accuracy: 0.5837 - val_loss: 7.8499
Epoch 318/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9978 - loss: 0.0115 - val_accuracy: 0.5816 - val_loss: 7.8007
Epoch 319/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9961 - loss: 0.0135 - val_accuracy: 0.5888 - val_loss: 7.7797
Epoch 320/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9968 - loss: 0.0095 - val_accuracy: 0.5847 - val_loss: 7.8516
Epoch 321/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9981 - loss: 0.0125 - val_accuracy: 0.5816 - val_loss: 7.8399
Epoch 322/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9983 - loss: 0.0096 - val_accuracy: 0.5847 - val_loss: 7.8199
Epoch 323/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9968 - loss: 0.0160 - val_accuracy: 0.5837 - val_loss: 7.7580
Epoch 324/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9958 - loss: 0.0311 - val_accuracy: 0.5816 - val_loss: 7.9743
Epoch 325/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9910 - loss: 0.0389 - val_accuracy: 0.5755 - val_loss: 7.9259
Epoch 326/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9853 - loss: 0.0504 - val_accuracy: 0.5796 - val_loss: 7.9655
Epoch 327/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9857 - loss: 0.0404 - val_accuracy: 0.5878 - val_loss: 7.8571
Epoch 328/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9824 - loss: 0.0657 - val_accuracy: 0.5653 - val_loss: 8.1934
Epoch 329/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9578 - loss: 0.1498 - val_accuracy: 0.5867 - val_loss: 7.9032
Epoch 330/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9766 - loss: 0.0602 - val_accuracy: 0.5918 - val_loss: 7.9197
Epoch 331/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9829 - loss: 0.0614 - val_accuracy: 0.5908 - val_loss: 7.9405
Epoch 332/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9918 - loss: 0.0298 - val_accuracy: 0.5918 - val_loss: 7.7975
Epoch 333/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9988 - loss: 0.0087 - val_accuracy: 0.5847 - val_loss: 7.9066
Epoch 334/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0088 - val_accuracy: 0.5878 - val_loss: 7.8420
Epoch 335/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9986 - loss: 0.0092 - val_accuracy: 0.5929 - val_loss: 7.8707
Epoch 336/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0133 - val_accuracy: 0.5888 - val_loss: 7.8428
Epoch 337/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0239 - val_accuracy: 0.5888 - val_loss: 7.8603
Epoch 338/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9961 - loss: 0.0328 - val_accuracy: 0.5867 - val_loss: 7.9094
Epoch 339/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9938 - loss: 0.0244 - val_accuracy: 0.5847 - val_loss: 7.8721
Epoch 340/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9993 - loss: 0.0073 - val_accuracy: 0.5918 - val_loss: 7.8312
Epoch 341/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0236 - val_accuracy: 0.5908 - val_loss: 7.8342
Epoch 342/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0091 - val_accuracy: 0.5878 - val_loss: 7.9323
Epoch 343/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9943 - loss: 0.0237 - val_accuracy: 0.5806 - val_loss: 7.8777
Epoch 344/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9841 - loss: 0.0544 - val_accuracy: 0.5786 - val_loss: 8.2043
Epoch 345/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9553 - loss: 0.1548 - val_accuracy: 0.5745 - val_loss: 8.0449
Epoch 346/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9472 - loss: 0.1911 - val_accuracy: 0.5612 - val_loss: 8.2467
Epoch 347/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9378 - loss: 0.2782 - val_accuracy: 0.5806 - val_loss: 7.9810
Epoch 348/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9806 - loss: 0.0530 - val_accuracy: 0.5806 - val_loss: 7.9228

Epoch 349/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0252 - val_accuracy: 0.5837 - val_loss: 7.8786
Epoch 350/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0113 - val_accuracy: 0.5867 - val_loss: 7.8999
Epoch 351/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0102 - val_accuracy: 0.5918 - val_loss: 7.8863
Epoch 352/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0131 - val_accuracy: 0.5765 - val_loss: 7.8559
Epoch 353/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9976 - loss: 0.0163 - val_accuracy: 0.5816 - val_loss: 7.8615
Epoch 354/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0141 - val_accuracy: 0.5816 - val_loss: 7.8892
Epoch 355/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0109 - val_accuracy: 0.5867 - val_loss: 7.8550
Epoch 356/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0107 - val_accuracy: 0.5867 - val_loss: 7.8599
Epoch 357/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0123 - val_accuracy: 0.5929 - val_loss: 7.9161
Epoch 358/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9957 - loss: 0.0232 - val_accuracy: 0.5878 - val_loss: 7.9033
Epoch 359/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0086 - val_accuracy: 0.5867 - val_loss: 7.9523
Epoch 360/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9945 - loss: 0.0207 - val_accuracy: 0.5847 - val_loss: 7.9857
Epoch 361/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9888 - loss: 0.0425 - val_accuracy: 0.5776 - val_loss: 7.9739
Epoch 362/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9905 - loss: 0.0354 - val_accuracy: 0.5837 - val_loss: 7.9636
Epoch 363/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9828 - loss: 0.0551 - val_accuracy: 0.5847 - val_loss: 8.2263
Epoch 364/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9543 - loss: 0.1490 - val_accuracy: 0.5694 - val_loss: 8.2637
Epoch 365/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9590 - loss: 0.1436 - val_accuracy: 0.5837 - val_loss: 8.3361
Epoch 366/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9712 - loss: 0.1128 - val_accuracy: 0.5755 - val_loss: 8.0792
Epoch 367/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9903 - loss: 0.0316 - val_accuracy: 0.5949 - val_loss: 7.9800
Epoch 368/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9934 - loss: 0.0219 - val_accuracy: 0.5786 - val_loss: 8.0961
Epoch 369/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9974 - loss: 0.0119 - val_accuracy: 0.5908 - val_loss: 8.0246
Epoch 370/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0095 - val_accuracy: 0.5867 - val_loss: 8.0426
Epoch 371/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9998 - loss: 0.0057 - val_accuracy: 0.5878 - val_loss: 8.0653
Epoch 372/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9993 - loss: 0.0083 - val_accuracy: 0.5878 - val_loss: 8.0332
Epoch 373/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0082 - val_accuracy: 0.5776 - val_loss: 8.1334
Epoch 374/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0169 - val_accuracy: 0.5857 - val_loss: 8.1058
Epoch 375/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0128 - val_accuracy: 0.5908 - val_loss: 7.9952
Epoch 376/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0145 - val_accuracy: 0.5837 - val_loss: 8.0698
Epoch 377/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0128 - val_accuracy: 0.5847 - val_loss: 8.0190
Epoch 378/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0134 - val_accuracy: 0.5888 - val_loss: 8.0441
Epoch 379/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0125 - val_accuracy: 0.5898 - val_loss: 8.0076
Epoch 380/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9883 - loss: 0.0429 - val_accuracy: 0.5745 - val_loss: 8.1753
Epoch 381/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9198 - loss: 0.3062 - val_accuracy: 0.5684 - val_loss: 8.2394
Epoch 382/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9472 - loss: 0.1997 - val_accuracy: 0.5684 - val_loss: 8.0077
Epoch 383/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9730 - loss: 0.0759 - val_accuracy: 0.5724 - val_loss: 8.1516
Epoch 384/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9841 - loss: 0.0580 - val_accuracy: 0.5786 - val_loss: 8.0722
Epoch 385/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0180 - val_accuracy: 0.5786 - val_loss: 8.0921
Epoch 386/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9963 - loss: 0.0144 - val_accuracy: 0.5796 - val_loss: 8.0362
Epoch 387/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0152 - val_accuracy: 0.5867 - val_loss: 8.0804
Epoch 388/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0154 - val_accuracy: 0.5857 - val_loss: 8.0363
Epoch 389/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0090 - val_accuracy: 0.5888 - val_loss: 8.0312
Epoch 390/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0090 - val_accuracy: 0.5888 - val_loss: 8.0285
Epoch 391/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9961 - loss: 0.0212 - val_accuracy: 0.5806 - val_loss: 8.0488
Epoch 392/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0137 - val_accuracy: 0.5908 - val_loss: 8.0325
Epoch 393/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0129 - val_accuracy: 0.5929 - val_loss: 8.0258
Epoch 394/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0074 - val_accuracy: 0.5939 - val_loss: 8.0795
Epoch 395/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9937 - loss: 0.0248 - val_accuracy: 0.5847 - val_loss: 8.0794
Epoch 396/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9992 - loss: 0.0058 - val_accuracy: 0.5878 - val_loss: 8.0366
Epoch 397/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0117 - val_accuracy: 0.5857 - val_loss: 8.0692
Epoch 398/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0174 - val_accuracy: 0.5878 - val_loss: 8.1064
Epoch 399/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0065 - val_accuracy: 0.5878 - val_loss: 8.1091
Epoch 400/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9961 - loss: 0.0157 - val_accuracy: 0.5888 - val_loss: 8.0713
Epoch 401/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9994 - loss: 0.0063 - val_accuracy: 0.5827 - val_loss: 8.1345
Epoch 402/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0173 - val_accuracy: 0.5622 - val_loss: 8.1989
Epoch 403/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9650 - loss: 0.1120 - val_accuracy: 0.5398 - val_loss: 8.4272
Epoch 404/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9256 - loss: 0.2873 - val_accuracy: 0.5776 - val_loss: 7.9838
Epoch 405/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9565 - loss: 0.1383 - val_accuracy: 0.5816 - val_loss: 8.1434
Epoch 406/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9829 - loss: 0.0656 - val_accuracy: 0.5867 - val_loss: 8.0346
Epoch 407/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9953 - loss: 0.0194 - val_accuracy: 0.5816 - val_loss: 8.0734
Epoch 408/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0167 - val_accuracy: 0.5878 - val_loss: 8.0609
Epoch 409/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9942 - loss: 0.0182 - val_accuracy: 0.5796 - val_loss: 8.0531
Epoch 410/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0146 - val_accuracy: 0.5786 - val_loss: 8.0763
Epoch 411/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0121 - val_accuracy: 0.5786 - val_loss: 8.0840
Epoch 412/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0137 - val_accuracy: 0.5827 - val_loss: 8.1045
Epoch 413/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0116 - val_accuracy: 0.5786 - val_loss: 8.0815
Epoch 414/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9986 - loss: 0.0094 - val_accuracy: 0.5837 - val_loss: 8.0979
Epoch 415/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0129 - val_accuracy: 0.5908 - val_loss: 8.0302
Epoch 416/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9959 - loss: 0.0263 - val_accuracy: 0.5724 - val_loss: 8.0483
Epoch 417/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9938 - loss: 0.0302 - val_accuracy: 0.5898 - val_loss: 7.9969
Epoch 418/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9940 - loss: 0.0219 - val_accuracy: 0.5796 - val_loss: 8.0586
Epoch 419/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9975 - loss: 0.0142 - val_accuracy: 0.5765 - val_loss: 8.1408
Epoch 420/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9913 - loss: 0.0316 - val_accuracy: 0.5745 - val_loss: 8.2326
Epoch 421/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9850 - loss: 0.0587 - val_accuracy: 0.5673 - val_loss: 8.2360
Epoch 422/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9608 - loss: 0.1359 - val_accuracy: 0.5653 - val_loss: 8.2922
Epoch 423/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9666 - loss: 0.0912 - val_accuracy: 0.5571 - val_loss: 8.2625
Epoch 424/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9707 - loss: 0.0855 - val_accuracy: 0.5806 - val_loss: 8.0843
Epoch 425/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9664 - loss: 0.1204 - val_accuracy: 0.5827 - val_loss: 8.1551
Epoch 426/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9945 - loss: 0.0202 - val_accuracy: 0.5786 - val_loss: 8.0269
Epoch 427/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9924 - loss: 0.0323 - val_accuracy: 0.5704 - val_loss: 8.1565
Epoch 428/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9933 - loss: 0.0283 - val_accuracy: 0.5816 - val_loss: 8.1441
Epoch 429/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0169 - val_accuracy: 0.5837 - val_loss: 8.0871
Epoch 430/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9994 - loss: 0.0066 - val_accuracy: 0.5837 - val_loss: 8.1059
Epoch 431/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0096 - val_accuracy: 0.5837 - val_loss: 8.0960
Epoch 432/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0119 - val_accuracy: 0.5857 - val_loss: 8.0531
Epoch 433/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0122 - val_accuracy: 0.5806 - val_loss: 8.1666
Epoch 434/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9948 - loss: 0.0170 - val_accuracy: 0.5755 - val_loss: 8.2031
Epoch 435/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0146 - val_accuracy: 0.5755 - val_loss: 8.0982
Epoch 436/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0103 - val_accuracy: 0.5796 - val_loss: 8.1406
Epoch 437/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9926 - loss: 0.0237 - val_accuracy: 0.5765 - val_loss: 8.1717
Epoch 438/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9914 - loss: 0.0308 - val_accuracy: 0.5796 - val_loss: 8.1121
Epoch 439/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0080 - val_accuracy: 0.5796 - val_loss: 8.1664
Epoch 440/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0098 - val_accuracy: 0.5755 - val_loss: 8.1172
Epoch 441/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0128 - val_accuracy: 0.5755 - val_loss: 8.2113
Epoch 442/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9944 - loss: 0.0303 - val_accuracy: 0.5796 - val_loss: 8.1819
Epoch 443/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0115 - val_accuracy: 0.5847 - val_loss: 8.1650
Epoch 444/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9941 - loss: 0.0222 - val_accuracy: 0.5888 - val_loss: 8.1399
Epoch 445/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9941 - loss: 0.0220 - val_accuracy: 0.5745 - val_loss: 8.2485
Epoch 446/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9590 - loss: 0.1311 - val_accuracy: 0.5735 - val_loss: 8.6292
Epoch 447/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9415 - loss: 0.1926 - val_accuracy: 0.5776 - val_loss: 8.3095

Epoch 448/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9543 - loss: 0.1425 - val_accuracy: 0.5837 - val_loss: 8.4204
Epoch 449/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9745 - loss: 0.0919 - val_accuracy: 0.5745 - val_loss: 8.1676
Epoch 450/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0189 - val_accuracy: 0.5827 - val_loss: 8.1587
Epoch 451/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9897 - loss: 0.0276 - val_accuracy: 0.5837 - val_loss: 8.1377
Epoch 452/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0088 - val_accuracy: 0.5939 - val_loss: 8.1115
Epoch 453/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0179 - val_accuracy: 0.5827 - val_loss: 8.1594
Epoch 454/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0100 - val_accuracy: 0.5847 - val_loss: 8.1359
Epoch 455/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0099 - val_accuracy: 0.5857 - val_loss: 8.1453
Epoch 456/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0122 - val_accuracy: 0.5898 - val_loss: 8.1766
Epoch 457/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0137 - val_accuracy: 0.5847 - val_loss: 8.1217
Epoch 458/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0074 - val_accuracy: 0.5786 - val_loss: 8.2058
Epoch 459/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9893 - loss: 0.0394 - val_accuracy: 0.5816 - val_loss: 8.2275
Epoch 460/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0247 - val_accuracy: 0.5816 - val_loss: 8.3227
Epoch 461/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9837 - loss: 0.0544 - val_accuracy: 0.5776 - val_loss: 8.3061
Epoch 462/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9883 - loss: 0.0284 - val_accuracy: 0.5847 - val_loss: 8.3008
Epoch 463/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0139 - val_accuracy: 0.5796 - val_loss: 8.2195
Epoch 464/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0100 - val_accuracy: 0.5878 - val_loss: 8.1928
Epoch 465/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9995 - loss: 0.0056 - val_accuracy: 0.5786 - val_loss: 8.2554
Epoch 466/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9917 - loss: 0.0416 - val_accuracy: 0.5796 - val_loss: 8.1658
Epoch 467/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9841 - loss: 0.0512 - val_accuracy: 0.5755 - val_loss: 8.1999
Epoch 468/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9635 - loss: 0.1042 - val_accuracy: 0.5643 - val_loss: 8.3963
Epoch 469/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9654 - loss: 0.0938 - val_accuracy: 0.5633 - val_loss: 8.3703
Epoch 470/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9756 - loss: 0.0580 - val_accuracy: 0.5806 - val_loss: 8.1746
Epoch 471/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9959 - loss: 0.0190 - val_accuracy: 0.5867 - val_loss: 8.2039
Epoch 472/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0140 - val_accuracy: 0.5827 - val_loss: 8.2319
Epoch 473/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9959 - loss: 0.0154 - val_accuracy: 0.5796 - val_loss: 8.2226
Epoch 474/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0109 - val_accuracy: 0.5837 - val_loss: 8.2132
Epoch 475/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9953 - loss: 0.0123 - val_accuracy: 0.5765 - val_loss: 8.2517
Epoch 476/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0135 - val_accuracy: 0.5847 - val_loss: 8.1973
Epoch 477/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0199 - val_accuracy: 0.5837 - val_loss: 8.1741
Epoch 478/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0084 - val_accuracy: 0.5816 - val_loss: 8.3247
Epoch 479/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0118 - val_accuracy: 0.5786 - val_loss: 8.2296
Epoch 480/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0144 - val_accuracy: 0.5827 - val_loss: 8.2386
Epoch 481/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0121 - val_accuracy: 0.5837 - val_loss: 8.3082
Epoch 482/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9964 - loss: 0.0179 - val_accuracy: 0.5786 - val_loss: 8.1985
Epoch 483/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9995 - loss: 0.0062 - val_accuracy: 0.5847 - val_loss: 8.2471
Epoch 484/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9937 - loss: 0.0304 - val_accuracy: 0.5765 - val_loss: 8.4901
Epoch 485/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9411 - loss: 0.2499 - val_accuracy: 0.5908 - val_loss: 8.4388
Epoch 486/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9207 - loss: 0.2990 - val_accuracy: 0.5827 - val_loss: 8.3935
Epoch 487/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9746 - loss: 0.0795 - val_accuracy: 0.5816 - val_loss: 8.1485
Epoch 488/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9883 - loss: 0.0422 - val_accuracy: 0.5765 - val_loss: 8.3254
Epoch 489/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0174 - val_accuracy: 0.5755 - val_loss: 8.2362
Epoch 490/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0120 - val_accuracy: 0.5776 - val_loss: 8.2025
Epoch 491/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9998 - loss: 0.0067 - val_accuracy: 0.5806 - val_loss: 8.2076
Epoch 492/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0124 - val_accuracy: 0.5745 - val_loss: 8.1854
Epoch 493/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0137 - val_accuracy: 0.5806 - val_loss: 8.2582
Epoch 494/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0116 - val_accuracy: 0.5806 - val_loss: 8.2110
Epoch 495/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0095 - val_accuracy: 0.5827 - val_loss: 8.2371
Epoch 496/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0172 - val_accuracy: 0.5816 - val_loss: 8.3232
Epoch 497/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0107 - val_accuracy: 0.5755 - val_loss: 8.3066
Epoch 498/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9940 - loss: 0.0252 - val_accuracy: 0.5806 - val_loss: 8.3690
Epoch 499/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9926 - loss: 0.0419 - val_accuracy: 0.5796 - val_loss: 8.3392
Epoch 500/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0184 - val_accuracy: 0.5704 - val_loss: 8.3332
Epoch 501/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0123 - val_accuracy: 0.5714 - val_loss: 8.2630
Epoch 502/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0138 - val_accuracy: 0.5735 - val_loss: 8.2794
Epoch 503/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9974 - loss: 0.0120 - val_accuracy: 0.5837 - val_loss: 8.3096
Epoch 504/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9768 - loss: 0.1042 - val_accuracy: 0.5776 - val_loss: 8.5432
Epoch 505/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9338 - loss: 0.2434 - val_accuracy: 0.5847 - val_loss: 8.2823
Epoch 506/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9835 - loss: 0.0483 - val_accuracy: 0.5776 - val_loss: 8.2845
Epoch 507/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9933 - loss: 0.0276 - val_accuracy: 0.5908 - val_loss: 8.1885
Epoch 508/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9986 - loss: 0.0119 - val_accuracy: 0.5847 - val_loss: 8.1728
Epoch 509/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0109 - val_accuracy: 0.5918 - val_loss: 8.1936
Epoch 510/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9973 - loss: 0.0081 - val_accuracy: 0.5837 - val_loss: 8.2365
Epoch 511/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9960 - loss: 0.0177 - val_accuracy: 0.5827 - val_loss: 8.2355
Epoch 512/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9921 - loss: 0.0362 - val_accuracy: 0.5888 - val_loss: 8.2595
Epoch 513/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0089 - val_accuracy: 0.5765 - val_loss: 8.1862
Epoch 514/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0115 - val_accuracy: 0.5816 - val_loss: 8.2258
Epoch 515/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0111 - val_accuracy: 0.5867 - val_loss: 8.2051
Epoch 516/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9978 - loss: 0.0066 - val_accuracy: 0.5847 - val_loss: 8.2315
Epoch 517/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0166 - val_accuracy: 0.5837 - val_loss: 8.2056
Epoch 518/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0065 - val_accuracy: 0.5857 - val_loss: 8.2539
Epoch 519/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9956 - loss: 0.0214 - val_accuracy: 0.5908 - val_loss: 8.2877
Epoch 520/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0134 - val_accuracy: 0.5847 - val_loss: 8.2882
Epoch 521/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9975 - loss: 0.0163 - val_accuracy: 0.5949 - val_loss: 8.2601
Epoch 522/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9963 - loss: 0.0127 - val_accuracy: 0.5837 - val_loss: 8.2741
Epoch 523/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9967 - loss: 0.0120 - val_accuracy: 0.5837 - val_loss: 8.2608
Epoch 524/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0169 - val_accuracy: 0.5857 - val_loss: 8.4919
Epoch 525/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9315 - loss: 0.3220 - val_accuracy: 0.5704 - val_loss: 8.2123
Epoch 526/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9530 - loss: 0.1419 - val_accuracy: 0.5867 - val_loss: 8.4070
Epoch 527/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9711 - loss: 0.0878 - val_accuracy: 0.5755 - val_loss: 8.4770
Epoch 528/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9913 - loss: 0.0259 - val_accuracy: 0.5796 - val_loss: 8.3717
Epoch 529/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9981 - loss: 0.0148 - val_accuracy: 0.5837 - val_loss: 8.3908
Epoch 530/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9964 - loss: 0.0140 - val_accuracy: 0.5857 - val_loss: 8.4039
Epoch 531/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0080 - val_accuracy: 0.5816 - val_loss: 8.3431
Epoch 532/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9948 - loss: 0.0176 - val_accuracy: 0.5949 - val_loss: 8.4267
Epoch 533/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9940 - loss: 0.0236 - val_accuracy: 0.5806 - val_loss: 8.3842
Epoch 534/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9955 - loss: 0.0196 - val_accuracy: 0.5857 - val_loss: 8.4542
Epoch 535/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9897 - loss: 0.0391 - val_accuracy: 0.5694 - val_loss: 8.4310
Epoch 536/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9863 - loss: 0.0523 - val_accuracy: 0.5735 - val_loss: 8.5947
Epoch 537/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9915 - loss: 0.0303 - val_accuracy: 0.5837 - val_loss: 8.3710
Epoch 538/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9958 - loss: 0.0159 - val_accuracy: 0.5847 - val_loss: 8.3310
Epoch 539/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9852 - loss: 0.0479 - val_accuracy: 0.5796 - val_loss: 8.6842
Epoch 540/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9765 - loss: 0.0743 - val_accuracy: 0.5745 - val_loss: 8.3825
Epoch 541/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9713 - loss: 0.1001 - val_accuracy: 0.5990 - val_loss: 8.5128
Epoch 542/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9726 - loss: 0.0624 - val_accuracy: 0.5724 - val_loss: 8.5177
Epoch 543/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9832 - loss: 0.0452 - val_accuracy: 0.5878 - val_loss: 8.4210
Epoch 544/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9960 - loss: 0.0169 - val_accuracy: 0.5888 - val_loss: 8.4388
Epoch 545/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9920 - loss: 0.0321 - val_accuracy: 0.5816 - val_loss: 8.4057
Epoch 546/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0105 - val_accuracy: 0.5908 - val_loss: 8.3673

Epoch 547/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0144 - val_accuracy: 0.5898 - val_loss: 8.3838
Epoch 548/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0219 - val_accuracy: 0.5908 - val_loss: 8.3846
Epoch 549/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0098 - val_accuracy: 0.5898 - val_loss: 8.4168
Epoch 550/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0162 - val_accuracy: 0.5837 - val_loss: 8.4607
Epoch 551/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0308 - val_accuracy: 0.5704 - val_loss: 8.4714
Epoch 552/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9915 - loss: 0.0275 - val_accuracy: 0.5796 - val_loss: 8.4786
Epoch 553/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9886 - loss: 0.0419 - val_accuracy: 0.5694 - val_loss: 8.4072
Epoch 554/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9907 - loss: 0.0271 - val_accuracy: 0.5786 - val_loss: 8.5748
Epoch 555/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9846 - loss: 0.0503 - val_accuracy: 0.5735 - val_loss: 8.4991
Epoch 556/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9512 - loss: 0.1612 - val_accuracy: 0.5684 - val_loss: 8.5544
Epoch 557/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9297 - loss: 0.2794 - val_accuracy: 0.5806 - val_loss: 8.3422
Epoch 558/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9670 - loss: 0.0959 - val_accuracy: 0.5684 - val_loss: 8.4194
Epoch 559/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9921 - loss: 0.0295 - val_accuracy: 0.5724 - val_loss: 8.4493
Epoch 560/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0167 - val_accuracy: 0.5755 - val_loss: 8.4113
Epoch 561/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9959 - loss: 0.0173 - val_accuracy: 0.5847 - val_loss: 8.4218
Epoch 562/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0152 - val_accuracy: 0.5714 - val_loss: 8.4375
Epoch 563/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9996 - loss: 0.0063 - val_accuracy: 0.5816 - val_loss: 8.4098
Epoch 564/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0106 - val_accuracy: 0.5765 - val_loss: 8.4236
Epoch 565/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0117 - val_accuracy: 0.5765 - val_loss: 8.4082
Epoch 566/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0186 - val_accuracy: 0.5776 - val_loss: 8.4267
Epoch 567/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0089 - val_accuracy: 0.5786 - val_loss: 8.4361
Epoch 568/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0109 - val_accuracy: 0.5796 - val_loss: 8.4269
Epoch 569/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0203 - val_accuracy: 0.5827 - val_loss: 8.3467
Epoch 570/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0084 - val_accuracy: 0.5888 - val_loss: 8.3567
Epoch 571/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0097 - val_accuracy: 0.5796 - val_loss: 8.3285
Epoch 572/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0262 - val_accuracy: 0.5745 - val_loss: 8.4161
Epoch 573/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0159 - val_accuracy: 0.5847 - val_loss: 8.4002
Epoch 574/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0156 - val_accuracy: 0.5673 - val_loss: 8.4482
Epoch 575/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9957 - loss: 0.0157 - val_accuracy: 0.5786 - val_loss: 8.6068
Epoch 576/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9886 - loss: 0.0548 - val_accuracy: 0.5847 - val_loss: 8.4297
Epoch 577/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9870 - loss: 0.0495 - val_accuracy: 0.5704 - val_loss: 8.6921
Epoch 578/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9653 - loss: 0.1262 - val_accuracy: 0.5704 - val_loss: 8.5249
Epoch 579/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9368 - loss: 0.2195 - val_accuracy: 0.5673 - val_loss: 8.6650
Epoch 580/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9691 - loss: 0.1127 - val_accuracy: 0.5847 - val_loss: 8.5189
Epoch 581/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9799 - loss: 0.0469 - val_accuracy: 0.5735 - val_loss: 8.4901
Epoch 582/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9909 - loss: 0.0413 - val_accuracy: 0.5806 - val_loss: 8.4838
Epoch 583/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0156 - val_accuracy: 0.5776 - val_loss: 8.4796
Epoch 584/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0076 - val_accuracy: 0.5806 - val_loss: 8.4772
Epoch 585/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0079 - val_accuracy: 0.5806 - val_loss: 8.4886
Epoch 586/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0057 - val_accuracy: 0.5847 - val_loss: 8.5308
Epoch 587/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0187 - val_accuracy: 0.5837 - val_loss: 8.4814
Epoch 588/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9995 - loss: 0.0052 - val_accuracy: 0.5847 - val_loss: 8.4602
Epoch 589/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0206 - val_accuracy: 0.5765 - val_loss: 8.5404
Epoch 590/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9995 - loss: 0.0051 - val_accuracy: 0.5857 - val_loss: 8.5065
Epoch 591/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0104 - val_accuracy: 0.5806 - val_loss: 8.4889
Epoch 592/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0070 - val_accuracy: 0.5755 - val_loss: 8.5027
Epoch 593/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0087 - val_accuracy: 0.5837 - val_loss: 8.5044
Epoch 594/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0064 - val_accuracy: 0.5837 - val_loss: 8.5782
Epoch 595/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9967 - loss: 0.0211 - val_accuracy: 0.5827 - val_loss: 8.4805
Epoch 596/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0095 - val_accuracy: 0.5796 - val_loss: 8.4212
Epoch 597/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0152 - val_accuracy: 0.5643 - val_loss: 8.6497
Epoch 598/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9720 - loss: 0.0930 - val_accuracy: 0.5633 - val_loss: 9.0885
Epoch 599/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9265 - loss: 0.3274 - val_accuracy: 0.5694 - val_loss: 8.6138
Epoch 600/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9623 - loss: 0.1127 - val_accuracy: 0.5745 - val_loss: 8.7203
Epoch 601/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9819 - loss: 0.0490 - val_accuracy: 0.5745 - val_loss: 8.5394
Epoch 602/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9914 - loss: 0.0329 - val_accuracy: 0.5745 - val_loss: 8.4876
Epoch 603/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9939 - loss: 0.0245 - val_accuracy: 0.5745 - val_loss: 8.4638
Epoch 604/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0117 - val_accuracy: 0.5806 - val_loss: 8.4689
Epoch 605/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0085 - val_accuracy: 0.5735 - val_loss: 8.5187
Epoch 606/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0176 - val_accuracy: 0.5755 - val_loss: 8.4952
Epoch 607/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9989 - loss: 0.0091 - val_accuracy: 0.5867 - val_loss: 8.4958
Epoch 608/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0201 - val_accuracy: 0.5847 - val_loss: 8.5281
Epoch 609/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0098 - val_accuracy: 0.5755 - val_loss: 8.5537
Epoch 610/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9959 - loss: 0.0160 - val_accuracy: 0.5714 - val_loss: 8.6495
Epoch 611/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9835 - loss: 0.0592 - val_accuracy: 0.5847 - val_loss: 8.6166
Epoch 612/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9814 - loss: 0.0668 - val_accuracy: 0.5847 - val_loss: 8.5920
Epoch 613/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9599 - loss: 0.1582 - val_accuracy: 0.5745 - val_loss: 8.5627
Epoch 614/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9813 - loss: 0.0512 - val_accuracy: 0.5816 - val_loss: 8.3776
Epoch 615/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9918 - loss: 0.0307 - val_accuracy: 0.5888 - val_loss: 8.3884
Epoch 616/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0248 - val_accuracy: 0.5898 - val_loss: 8.4504
Epoch 617/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9949 - loss: 0.0176 - val_accuracy: 0.5898 - val_loss: 8.4983
Epoch 618/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9957 - loss: 0.0164 - val_accuracy: 0.5796 - val_loss: 8.3973
Epoch 619/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9929 - loss: 0.0273 - val_accuracy: 0.5786 - val_loss: 8.5594
Epoch 620/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9826 - loss: 0.0585 - val_accuracy: 0.5918 - val_loss: 8.4503
Epoch 621/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0121 - val_accuracy: 0.5878 - val_loss: 8.4012
Epoch 622/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0076 - val_accuracy: 0.5867 - val_loss: 8.4261
Epoch 623/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0140 - val_accuracy: 0.5827 - val_loss: 8.4345
Epoch 624/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0144 - val_accuracy: 0.5827 - val_loss: 8.5099
Epoch 625/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0110 - val_accuracy: 0.5898 - val_loss: 8.4478
Epoch 626/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9885 - loss: 0.0384 - val_accuracy: 0.5878 - val_loss: 8.6047
Epoch 627/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9522 - loss: 0.1817 - val_accuracy: 0.5786 - val_loss: 8.5426
Epoch 628/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9786 - loss: 0.0605 - val_accuracy: 0.5837 - val_loss: 8.6146
Epoch 629/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0270 - val_accuracy: 0.5969 - val_loss: 8.8833
Epoch 630/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9702 - loss: 0.1112 - val_accuracy: 0.5796 - val_loss: 8.5842
Epoch 631/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9753 - loss: 0.0633 - val_accuracy: 0.5827 - val_loss: 8.5996
Epoch 632/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9860 - loss: 0.0539 - val_accuracy: 0.5898 - val_loss: 8.4704
Epoch 633/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9843 - loss: 0.0470 - val_accuracy: 0.5827 - val_loss: 8.5621
Epoch 634/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0247 - val_accuracy: 0.5847 - val_loss: 8.5611
Epoch 635/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0137 - val_accuracy: 0.5888 - val_loss: 8.4992
Epoch 636/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0114 - val_accuracy: 0.5847 - val_loss: 8.4646
Epoch 637/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0068 - val_accuracy: 0.5898 - val_loss: 8.4870
Epoch 638/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9996 - loss: 0.0039 - val_accuracy: 0.5816 - val_loss: 8.6048
Epoch 639/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9990 - loss: 0.0085 - val_accuracy: 0.5939 - val_loss: 8.5304
Epoch 640/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0089 - val_accuracy: 0.5857 - val_loss: 8.4838
Epoch 641/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0107 - val_accuracy: 0.5867 - val_loss: 8.5132
Epoch 642/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0110 - val_accuracy: 0.5837 - val_loss: 8.5247
Epoch 643/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0096 - val_accuracy: 0.5816 - val_loss: 8.6299
Epoch 644/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9955 - loss: 0.0137 - val_accuracy: 0.5796 - val_loss: 8.5742
Epoch 645/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0079 - val_accuracy: 0.5816 - val_loss: 8.5646

Epoch 646/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0141 - val_accuracy: 0.5908 - val_loss: 8.4460
Epoch 647/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9906 - loss: 0.0300 - val_accuracy: 0.5847 - val_loss: 8.6107
Epoch 648/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9549 - loss: 0.1836 - val_accuracy: 0.5867 - val_loss: 8.6817
Epoch 649/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9401 - loss: 0.2126 - val_accuracy: 0.5673 - val_loss: 8.6756
Epoch 650/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9849 - loss: 0.0566 - val_accuracy: 0.5776 - val_loss: 8.4833
Epoch 651/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9914 - loss: 0.0355 - val_accuracy: 0.5867 - val_loss: 8.5341
Epoch 652/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9930 - loss: 0.0196 - val_accuracy: 0.5949 - val_loss: 8.4964
Epoch 653/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0139 - val_accuracy: 0.5918 - val_loss: 8.4871
Epoch 654/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0079 - val_accuracy: 0.5959 - val_loss: 8.4737
Epoch 655/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9992 - loss: 0.0086 - val_accuracy: 0.5867 - val_loss: 8.4891
Epoch 656/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9985 - loss: 0.0054 - val_accuracy: 0.5867 - val_loss: 8.4948
Epoch 657/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0073 - val_accuracy: 0.5939 - val_loss: 8.5186
Epoch 658/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0059 - val_accuracy: 0.5898 - val_loss: 8.5875
Epoch 659/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0164 - val_accuracy: 0.5878 - val_loss: 8.5803
Epoch 660/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9992 - loss: 0.0076 - val_accuracy: 0.5847 - val_loss: 8.5230
Epoch 661/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9992 - loss: 0.0051 - val_accuracy: 0.5796 - val_loss: 8.6618
Epoch 662/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9941 - loss: 0.0243 - val_accuracy: 0.5888 - val_loss: 8.6148
Epoch 663/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9869 - loss: 0.0479 - val_accuracy: 0.5827 - val_loss: 8.6944
Epoch 664/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9516 - loss: 0.1758 - val_accuracy: 0.5796 - val_loss: 8.5417
Epoch 665/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9562 - loss: 0.1543 - val_accuracy: 0.5704 - val_loss: 8.6908
Epoch 666/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9779 - loss: 0.0680 - val_accuracy: 0.5837 - val_loss: 8.5440
Epoch 667/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9907 - loss: 0.0338 - val_accuracy: 0.5929 - val_loss: 8.4988
Epoch 668/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9912 - loss: 0.0266 - val_accuracy: 0.5878 - val_loss: 8.5035
Epoch 669/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9961 - loss: 0.0199 - val_accuracy: 0.5888 - val_loss: 8.5222
Epoch 670/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0091 - val_accuracy: 0.5796 - val_loss: 8.5067
Epoch 671/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9991 - loss: 0.0063 - val_accuracy: 0.5776 - val_loss: 8.5403
Epoch 672/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9958 - loss: 0.0147 - val_accuracy: 0.5847 - val_loss: 8.5390
Epoch 673/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0112 - val_accuracy: 0.5765 - val_loss: 8.5950
Epoch 674/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9951 - loss: 0.0140 - val_accuracy: 0.5857 - val_loss: 8.6714
Epoch 675/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9911 - loss: 0.0283 - val_accuracy: 0.5888 - val_loss: 8.5775
Epoch 676/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9953 - loss: 0.0181 - val_accuracy: 0.5867 - val_loss: 8.6095
Epoch 677/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9764 - loss: 0.0950 - val_accuracy: 0.5592 - val_loss: 8.7375
Epoch 678/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9669 - loss: 0.1142 - val_accuracy: 0.5806 - val_loss: 8.7034
Epoch 679/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9586 - loss: 0.1469 - val_accuracy: 0.5898 - val_loss: 8.6973
Epoch 680/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9779 - loss: 0.0609 - val_accuracy: 0.5959 - val_loss: 8.4878
Epoch 681/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0180 - val_accuracy: 0.5878 - val_loss: 8.5735
Epoch 682/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9962 - loss: 0.0138 - val_accuracy: 0.5959 - val_loss: 8.5454
Epoch 683/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9969 - loss: 0.0154 - val_accuracy: 0.5918 - val_loss: 8.5462
Epoch 684/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9984 - loss: 0.0078 - val_accuracy: 0.5908 - val_loss: 8.5708
Epoch 685/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9988 - loss: 0.0060 - val_accuracy: 0.5959 - val_loss: 8.5670
Epoch 686/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0151 - val_accuracy: 0.5847 - val_loss: 8.6207
Epoch 687/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9987 - loss: 0.0061 - val_accuracy: 0.5786 - val_loss: 8.6327
Epoch 688/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9970 - loss: 0.0137 - val_accuracy: 0.5918 - val_loss: 8.6470
Epoch 689/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0122 - val_accuracy: 0.5888 - val_loss: 8.5606
Epoch 690/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9984 - loss: 0.0060 - val_accuracy: 0.5816 - val_loss: 8.5797
Epoch 691/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9905 - loss: 0.0274 - val_accuracy: 0.5827 - val_loss: 8.6448
Epoch 692/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9820 - loss: 0.0537 - val_accuracy: 0.5918 - val_loss: 8.5840
Epoch 693/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9696 - loss: 0.0857 - val_accuracy: 0.5531 - val_loss: 8.7691
Epoch 694/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9773 - loss: 0.0777 - val_accuracy: 0.5878 - val_loss: 8.5768
Epoch 695/10000

92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9854 - loss: 0.0460 - val_accuracy: 0.5776 - val_loss: 8.6495
Epoch 696/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9925 - loss: 0.0271 - val_accuracy: 0.5816 - val_loss: 8.7150
Epoch 697/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0253 - val_accuracy: 0.5714 - val_loss: 8.8033
Epoch 698/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9922 - loss: 0.0340 - val_accuracy: 0.5735 - val_loss: 8.7855
Epoch 699/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9949 - loss: 0.0189 - val_accuracy: 0.5816 - val_loss: 8.7243
Epoch 700/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0094 - val_accuracy: 0.5796 - val_loss: 8.6911
Epoch 701/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0093 - val_accuracy: 0.5847 - val_loss: 8.6540
Epoch 702/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0068 - val_accuracy: 0.5765 - val_loss: 8.7076
Epoch 703/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9979 - loss: 0.0101 - val_accuracy: 0.5806 - val_loss: 8.7055
Epoch 704/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0179 - val_accuracy: 0.5847 - val_loss: 8.7297
Epoch 705/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9966 - loss: 0.0166 - val_accuracy: 0.5796 - val_loss: 8.6846
Epoch 706/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9950 - loss: 0.0215 - val_accuracy: 0.5827 - val_loss: 8.6239
Epoch 707/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9934 - loss: 0.0257 - val_accuracy: 0.5704 - val_loss: 8.9147
Epoch 708/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9723 - loss: 0.0903 - val_accuracy: 0.5612 - val_loss: 8.9721
Epoch 709/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9308 - loss: 0.2468 - val_accuracy: 0.5898 - val_loss: 8.7292
Epoch 710/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9793 - loss: 0.0740 - val_accuracy: 0.5959 - val_loss: 8.6384
Epoch 711/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9924 - loss: 0.0228 - val_accuracy: 0.5888 - val_loss: 8.6073
Epoch 712/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0135 - val_accuracy: 0.5837 - val_loss: 8.5506
Epoch 713/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0118 - val_accuracy: 0.5827 - val_loss: 8.5264
Epoch 714/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9983 - loss: 0.0083 - val_accuracy: 0.5857 - val_loss: 8.5834
Epoch 715/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0074 - val_accuracy: 0.5898 - val_loss: 8.5815
Epoch 716/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0134 - val_accuracy: 0.5898 - val_loss: 8.6139
Epoch 717/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9987 - loss: 0.0079 - val_accuracy: 0.5837 - val_loss: 8.5529
Epoch 718/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9986 - loss: 0.0078 - val_accuracy: 0.5898 - val_loss: 8.5607
Epoch 719/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9964 - loss: 0.0125 - val_accuracy: 0.5857 - val_loss: 8.6455
Epoch 720/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9993 - loss: 0.0086 - val_accuracy: 0.5898 - val_loss: 8.6511
Epoch 721/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9968 - loss: 0.0117 - val_accuracy: 0.5806 - val_loss: 8.5828
Epoch 722/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9966 - loss: 0.0156 - val_accuracy: 0.5857 - val_loss: 8.6570
Epoch 723/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0113 - val_accuracy: 0.5776 - val_loss: 8.5582
Epoch 724/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9972 - loss: 0.0127 - val_accuracy: 0.5898 - val_loss: 8.6166
Epoch 725/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9965 - loss: 0.0126 - val_accuracy: 0.5786 - val_loss: 8.6031
Epoch 726/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9980 - loss: 0.0133 - val_accuracy: 0.5939 - val_loss: 8.5605
Epoch 727/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9978 - loss: 0.0158 - val_accuracy: 0.5847 - val_loss: 8.6035
Epoch 728/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9981 - loss: 0.0079 - val_accuracy: 0.5816 - val_loss: 8.5803
Epoch 729/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9971 - loss: 0.0133 - val_accuracy: 0.5827 - val_loss: 8.6102
Epoch 730/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9985 - loss: 0.0095 - val_accuracy: 0.5806 - val_loss: 8.6290
Epoch 731/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9952 - loss: 0.0269 - val_accuracy: 0.5878 - val_loss: 8.6571
Epoch 732/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9870 - loss: 0.0491 - val_accuracy: 0.5622 - val_loss: 8.6599
Epoch 733/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9196 - loss: 0.3644 - val_accuracy: 0.5694 - val_loss: 8.5535
Epoch 734/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9696 - loss: 0.1007 - val_accuracy: 0.5827 - val_loss: 8.9396
Epoch 735/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9805 - loss: 0.0525 - val_accuracy: 0.5867 - val_loss: 8.6573
Epoch 736/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9936 - loss: 0.0257 - val_accuracy: 0.5857 - val_loss: 8.4162
Epoch 737/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0120 - val_accuracy: 0.5867 - val_loss: 8.5231
Epoch 738/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9976 - loss: 0.0127 - val_accuracy: 0.5796 - val_loss: 8.5636
Epoch 739/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9973 - loss: 0.0111 - val_accuracy: 0.5867 - val_loss: 8.5366
Epoch 740/10000
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9977 - loss: 0.0090 - val_accuracy: 0.5918 - val_loss: 8.5575
Epoch 741/10000
 1/92 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 1.0000 - loss: 0.0045

KeyboardInterrupt:

# 데이터 증폭 후 분석
* 데이터 증폭 + 스케일러 사용 시에는 :
* 데이터 증폭 후 스케일러로 스케일링 하기

In [50]:
from imblearn.over_sampling import SMOTE

In [54]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [55]:
X = data.drop('quality', axis=1)
y = data['quality']

In [56]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.4, stratify=y, random_state=42)
X_valid, X_test, y_valid, y_test = train_test_split(X_valid, y_valid, test_size=0.5, stratify=y_valid, random_state=42)

In [57]:
smt = SMOTE(n_jobs=-1, random_state=42)
smt_X_trian, smt_y_train = smt.fit_resample(X_train, y_train)
smt_X_trian = pd.DataFrame(smt_X_trian, columns=X_train.columns, index=X_train.index)
smt_y_train = pd.DataFrame(smt_y_train, columns=y_train.columns, index=y_train.index)

/home/fintech_ubuntu/miniforge3/envs/tf/lib/python3.9/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
/home/fintech_ubuntu/miniforge3/envs/tf/lib/python3.9/site-packages/imblearn/over_sampling/_smote/base.py:370: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

ValueError: Expected n_neighbors <= n_samples_fit, but n_neighbors = 6, n_samples_fit = 3, n_samples = 3

In [58]:
rs = RobustScaler()
train_temp = rs.fit_transform(X_train)
valid_temp = rs.transform(X_valid)
test_temp = rs.transform(X_test)
rs_X_train = pd.DataFrame(train_temp, columns=X_train.columns, index=X_train.index)
rs_X_valid = pd.DataFrame(valid_temp, columns=X_valid.columns, index=X_valid.index)
rs_X_test = pd.DataFrame(test_temp, columns=X_test.columns, index=X_test.index)