# 1.requrests 모듈 : HTTP 프로토콜을 사용할 수 있게 해주는 모듈
* [requests](https://requests.readthedocs.io/en/latest/user/quickstart/)

# 2 requests 모듈 설치
* conda install requests
* pip install requests

# 3. requests 모듈 사용법
* 1) 모듈 불러오기 : import requests
* 2) url 변수에 저장
* 3) url 파라미터
    * payload = {파라미터1 : value1, 파라미터2 : value2
* 4) header
    * headers = {key : value}
* 5) HTTP 요청 보내기 : get,post
    * get : r = requests.get(url, params = payload, headers = headers)
    * post : r = requests.post(url, data={key:valu})
* 6) 만들어진 url 확인
    * print(r.url)
* 7) 응답 코드 확인 : print(r.status_code)
* 8) 응답 요소 출력 : r.text, r.json, r.content, r.json()

In [ ]:
import pandas as pd

In [ ]:
start_num2 = 1
for s_num in range(11):
    start_num2 += 100
    print(start_num2)

In [ ]:
import requests
url = "https://openapi.naver.com/v1/search/blog.json"
Cliend_Id = "TaVTw3HnrpVGJDDGj3ym"
Cliend_Pw = "46NsuGC17a"
payload = dict(query = '핀테크1', display = 10, start= 1, sort ="sim")
headers = {"X-Naver-Client-Id" : Cliend_Id, "X-Naver-Client-Secret" : Cliend_Pw }
r = requests.get(url, params=payload, headers = headers)
print(r.url)
print(r.status_code)
response = r.json()
response
r_response = pd.DataFrame(response)
r_response

 * 모든 검색결과를 가져오기 위해서는 여러페이지 정보를 수집
 * 전체결과 / 1페이지 표시 개수 = 전체 페이지 수
 * start 부분 + 1페이지 표지 개수 = 다음 페이지 데이터 수집 가능
 * 반복문을 이용해서 start에 100씩 더해서 최대 100이 되도록 하면 최대한 많은 데이터 수집 가능

In [ ]:
import requests

In [ ]:
url = "https://openapi.naver.com/v1/search/blog"

In [50]:
payload = {'query': '핀테크1', 'display' : 100, 'start': 1, 'sort':"sim" }
headers = {"X-Naver-Client-Id" : "TaVTw3HnrpVGJDDGj3ym", "X-Naver-Client-Secret" : "46NsuGC17a"}
r = requests.get(url, params=payload, headers = headers)
print(r.url)
print(r.status_code)
# status code : Informational responses (100 – 199)
# Successful responses (200 – 299)
# Redirection messages (300 – 399)
# Client error responses (400 – 499)
# Server error responses (500 – 599)
# 200번이 올바른 결과(OK)
data = r.json()
data
# r.text

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC1&display=100&start=1&sort=sim
200

{'lastBuildDate': 'Tue, 01 Apr 2025 13:24:07 +0900',
 'total': 299627,
 'start': 1,
 'display': 100,
 'items': [{'title': '이것도 <b>핀테크</b>? 운전 습관에 따라 보험료가... ',
   'link': 'https://blog.naver.com/koreafintech/223803803517',
   'description': '이것도 <b>핀테크</b>? #<b>1</b>편 운전 습관에 따라 보험료가 달라지는 BBI (Behavior-Based Insurance) 인슈어테크로... 오늘은 보험의 핀테크인 인슈어테크(InsureTech) 중 “운전행태 기반 자동차 보험 (BBI, Behavior-Based Insurance)... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20250321'},
  {'title': '[진로체험] 제물포중학교 <b>핀테크</b> 금융 IT 전문가 진로프로그램',
   'link': 'https://blog.naver.com/sys1748/223743582618',
   'description': '2024년 한 해 학생들이 선정한 최고의 과목이에요^^ 제물포중학교 진로 체험 학습 제물포중학교 직업 체험은 6개 학급 대상 1개 과목 2차시 진로교육으로 진행했어요 ㅎㅎ 차례 강의 명 <b>1</b> <b>핀테크</b> 금융 IT 전문가... ',
   'bloggername': '한국융합과학교육원',
   'bloggerlink': 'blog.naver.com/sys1748',
   'postdate': '20250210'},
  {'title': '<b>핀테크</b> 뜻 기업 종류 산업 사례 장단점 알아보자',
   'link': 'https://blog.naver.com/franksong0030/223776691078',
   'description': '<b>1</b>. <b>핀테크</b>(FinTech)란? <b>핀테크</b>(FinTech)는 금융(Finance)과 기술(Technology)의 합성어로, IT 기술을 금융 서비스에 접목해 새로운 가치를 창출하는 산업을 의미한다. 간단히 말해, 기존의 은행이나 금융 기관이 하던... ',
   'bloggername': 'Franky, IT Story',
   'bloggerlink': 'blog.naver.com/franksong0030',
   'postdate': '20250303'},
  {'title': '미래 금융을 이끌 ‘<b>핀테크</b> 전문가’와 금융 산업의 진화',
   'link': 'https://blog.naver.com/wisetipsnow/223759655860',
   'description': '<b>1</b>. <b>핀테크</b> 전문가: 금융의 기술 혁신을 이끄는 인재 <b>핀테크</b> 전문가란 금융과 기술을 융합한 전문가로, 금융 거래 시스템을 구축하거나 시스템 개발 및 보안을 담당하는 사람들을 말합니다. 특히, 스마트폰을... ',
   'bloggername': '생활 속 유용한 정보를 모아놓은 창고',
   'bloggerlink': 'blog.naver.com/wisetipsnow',
   'postdate': '20250222'},
  {'title': '미국 <b>핀테크</b> 암호화폐 관련주 로빈후드(HOOD) 주가와 기업분석',
   'link': 'https://blog.naver.com/publiceffect/223806052098',
   'description': '본 게시물이 흥미로웠다면, 바로 아래 미국 <b>핀테크 1</b>탄 소파이 기업 분석 게시물도 만나보세요. 다들 각자의 방법으로 성투하시기 바랍니다. · [미국 핀테크 분석 1탄] 소파이(SoFi), 천 만 사용자 돌파... ',
   'bloggername': '상상한 대로 이뤄지는 투자이야기',
   'bloggerlink': 'blog.naver.com/publiceffect',
   'postdate': '20250322'},
  {'title': '카카오페이 주가 주식 현황 알아볼까 - <b>핀테크</b> 간편 전자결제... ',
   'link': 'https://blog.naver.com/the_hye_jin/223668334410',
   'description': '목차 <b>1</b>. <b>핀테크</b> 간편 전자결제 관련주 카카오페이 2. 카카오페이 주식 분석 3. 카카오페이 주가 현황 4. 열달로그 분석노트 <b>1</b>. <b>핀테크</b> 간편 전자결제 관련주 카카오페이 <b>핀테크</b> 간편 전자결제 관련주... ',
   'bloggername': '열달로그의 국내주식 분석노트',
   'bloggerlink': 'blog.naver.com/the_hye_jin',
   'postdate': '20241121'},
  {'title': '싱가포르 <b>핀테크</b> 사업 진출',
   'link': 'https://blog.naver.com/premia_tnc/223103330644',
   'description': '지난 몇 년 동안 싱가포르에는 많은 다국적 핀테크 혁신 연구소와 연구 센터가 설립되었고 1,500개 이상의 핀테크 스타트업이 설립되었습니다. 싱가포르가 아시아 국가 중 ‘<b>핀테크 1</b>위’ 국가라고 해도 과언이... ',
   'bloggername': '프레미아 티엔씨 (PREMIA TNC) 공식 블로그',
   'bloggerlink': 'blog.naver.com/premia_tnc',
   'postdate': '20230516'},
  {'title': '<b>핀테크</b> 뜻 투자방법 알아봐요',
   'link': 'https://blog.naver.com/jungmk1570/223602309573',
   'description': '<b>1</b>. <b>핀테크</b>란? <b>핀테크</b>(Financial Technology)는 금융(Finance)과 기술(Technology)의 합성어로, 디지털 기술을 활용한 금융 서비스를 의미합니다. <b>핀테크</b>를 통해 누구나 쉽게 투자할 수 있는 다양한 플랫폼들이 등장했죠.... ',
   'bloggername': '재테크 허니',
   'bloggerlink': 'blog.naver.com/jungmk1570',
   'postdate': '20241001'},
  {'title': '올라<b>핀테크 1</b>년 사용후기! (추천인코드 3423201302)',
   'link': 'https://blog.naver.com/jwj0025/223521830754',
   'description': '처음 보는 쇼핑몰도 있고, 종류가 정말 많긴 많다 :) 올라<b>핀테크</b>는 수수료도 <b>1</b>.2%로 저렴한 편이고, 오후 5시 이전 신청하면 당일 지급된다. (단 선정산 금액이 20만원 이상이여야한다) 그래서 쇼핑몰 시작... ',
   'bloggername': 'swandiary',
   'bloggerlink': 'blog.naver.com/jwj0025',
   'postdate': '20240722'},
  {'title': '<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기',
   'link': 'https://blog.naver.com/haseobang83/223657527445',
   'description': '<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <b>핀테크</b>(Fintech)는 ‘금융(Finance)’과 ‘기술(Technology)’의 결합으로, 첨단 기술을 활용해 금융 서비스를 혁신하는 모든 활동을 뜻해요. 말 그대로 금융과 기술이 만난... ',
   'bloggername': '더하임(The HEIM)',
   'bloggerlink': 'blog.naver.com/haseobang83',
   'postdate': '20241112'},
  {'title': '<b>핀테크</b> 혁신 – 금융의 새로운 패러다임',
   'link': 'https://blog.naver.com/altnr3875/223798337783',
   'description': '--- <b>1</b>. <b>핀테크</b> 혁신이란? <b>핀테크</b>는 기존 금융 서비스가 가진 불편함을 기술을 활용하여 해결하고, 새로운 금융 모델을 창출하는 분야입니다. 대표적인 <b>핀테크</b> 혁신에는 다음과 같은 요소들이 포함됩니다.... ',
   'bloggername': '서울에서 부산',
   'bloggerlink': 'blog.naver.com/altnr3875',
   'postdate': '20250321'},
  {'title': '[정책현장] <b>핀테크</b> 혁신펀드 5,000억원 규모로 추가 조성합니다',
   'link': 'https://blog.naver.com/blogfsc/223413132334',
   'description': '<b>1</b>. <b>핀테크</b> 혁신펀드를 확대·개편하겠습니다. 올해부터 2027년까지 5,000억 규모로 2호 펀드 추가 조성 운용 방식을 고도화하여 투자대상을 세분화·체계화하고 성장주기에 따라 투자자금 공급 및 후속투자... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20240412'},
  {'title': '[3/26까지][금융위원회]2025년 제1차 <b>핀테크</b> 해외진출 컨설팅... ',
   'link': 'https://blog.naver.com/ilsinbc/223788341613',
   'description': '<b>1</b>:<b>1</b> 매칭을 통해 파트너사가 <b>핀테크</b>기업에게 제공하고 센터에서 서비스 대금의 일부를 지원 사업신청 방법 온라인 접수 (<b>핀테크</b>포털) 사업신청 사이트 문의처 한국<b>핀테크</b>지원센터 금융혁신부 02-6375-1519... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250308'},
  {'title': '[기자단 뉴스] 글로벌 <b>핀테크</b> 동향 알아보기',
   'link': 'https://blog.naver.com/koreafintech/223631935495',
   'description': '글로벌 <b>핀테크</b> 동향 알아보기 제12기 대학생 기자단 이유진 <b>1</b>. 멕시코 <b>핀테크</b> ▶ 2022년 기준 <b>핀테크</b> 거래 규모는 860억 달러로, 전년 동기 대비 23%의 성장률을 보임 ▶ 멕시코 소비자들의 <b>핀테크</b>에 대한... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241024'},
  {'title': '[진로체험] 창원 경상고등학교 IoT, <b>핀테크</b>, <b>1</b>인 미디어... ',
   'link': 'https://blog.naver.com/sys1748/223362907793',
   'description': '23.12.12 창원 경상고등학교 IoT, <b>핀테크</b>, <b>1</b>인 미디어, 반도체 등 미래신산업 진로체험 학습 안녕하세요... 약 180명(8학급)을 대상으로 IoT, <b>핀테크</b>, <b>1</b>인 미디어, 반도체 등 수업을 운영했습니다. 창원 경상고등학교... ',
   'bloggername': '한국융합과학교육원',
   'bloggerlink': 'blog.naver.com/sys1748',
   'postdate': '20240224'},
  {'title': '<b>핀테크</b> 전문가 취업 풀스택 개발자 국비지원 과정',
   'link': 'https://blog.naver.com/kgitdream/223767432006',
   'description': '<b>1</b>) <b>핀테크</b> 개발자 : 금융 관련 소프트웨어, 애플리케이션 및 플랫폼을 개발하는 역할을 해요. 프론트엔드, 백엔드, 데이터베이스 관리까지 다양한 기술이 필요하답니다. 2) 데이터 분석가 : 데이터를 분석하고... ',
   'bloggername': '우리를 잇(IT)는 메타버스',
   'bloggerlink': 'blog.naver.com/kgitdream',
   'postdate': '20250220'},
  {'title': '<b>핀테크</b>로 진출하는 맨틀 네트워크(MNT)',
   'link': 'https://blog.naver.com/rusiper1000/223781111719',
   'description': '<b>1</b>. 한국 <b>핀테크</b> 시장, 4년 뒤 84조로 성장 예상 한국경제 <b>핀테크</b>, 테크핀이라는 용어를 많이 들어보셨을텐데요. 국내 대표 <b>핀테크</b> 기업 토스의 창업자는 2024년에 한국의 <b>핀테크</b> 시장은 4년 뒤 84조로 성장할... ',
   'bloggername': '타락천사의 블로그',
   'bloggerlink': 'blog.naver.com/rusiper1000',
   'postdate': '20250303'},
  {'title': '<b>핀테크</b> 뜻 유래 기업 사례',
   'link': 'https://blog.naver.com/toresi/223471507785',
   'description': '<b>핀테크</b> 하루 1분 금융경제용어 안녕하세요. ^^ 오늘의 경제용어입니다. <b>핀테크</b> 뜻은 무엇인가? <b>핀테크</b>(FinTech) 금융(Finance)과 기술(Technology)의 합성어로, 금융 서비스를 기술적으로 혁신하여 융합하는 것을... ',
   'bloggername': '은행원쀼에게 금융 묻고 더블로',
   'bloggerlink': 'blog.naver.com/toresi',
   'postdate': '20240607'},
  {'title': '<b>핀테크</b> 뜻 : 금융의 새로운 패러다임',
   'link': 'https://blog.naver.com/muse0481/223795946786',
   'description': '<b>핀테크</b> 뜻 : 금융의 새로운 패러다임 <b>1</b>. <b>핀테크</b> 뜻? : 금융의 새로운 패러다임 안녕! 요즘 주변에서 <b>핀테크</b> 얘기를 심심치 않게 들어봤을 거야. <b>핀테크</b>의 뜻은 금융(Finance)과 기술(Technology)이 합쳐진 말로, 쉽게... ',
   'bloggername': 'MUSE',
   'bloggerlink': 'blog.naver.com/muse0481',
   'postdate': '20250314'},
  {'title': '서울 <b>핀테크</b> 위크 2023 컨퍼런스 - 동대문 DDP',
   'link': 'https://blog.naver.com/joo1609/223232228599',
   'description': '세션 <b>1</b> <b>핀테크</b> 허브 전략과 감독 방안: 금융기관 협업 지속가능성에 대한 내용을 주제로 한국<b>핀테크</b>산업협회 회장인 이근주님이 진행해주셨습니다. ◆김부곤 금융감독원 디지털금융혁신국장 -<b>핀테크</b> 생태계... ',
   'bloggername': '✨️뚜벅이주주 문화여행맛집 이야기',
   'bloggerlink': 'blog.naver.com/joo1609',
   'postdate': '20231009'},
  {'title': '2025년 1차 <b>핀테크</b> 해외진출 컨설팅 참여기업 모집공고 안내',
   'link': 'https://blog.naver.com/premia_tnc/223801004378',
   'description': '한국<b>핀테크</b>지원센터는 <b>핀테크</b> 기업의 해외시장 진출을 효과적으로 지원하기 위하여 해외진출을 희망하는 국내<b>핀테크</b> 기업에게 전문컨설팅을 지원하오니 관심 있는 <b>핀테크</b>기업의 참조 바랍니다. <b>1</b>.... ',
   'bloggername': '프레미아 티엔씨 (PREMIA TNC) 공식 블로그',
   'bloggerlink': 'blog.naver.com/premia_tnc',
   'postdate': '20250318'},
  {'title': '소셜 <b>핀테크</b>, 왜 사람들이 계속 이용할까?',
   'link': 'https://blog.naver.com/flyfirst0101/223789749173',
   'description': '<b>1</b>.그렇다면 소셜 <b>핀테크</b>란 무엇일까요? 소셜 <b>핀테크</b>는 개인이 아닌 여러 사람이 함께 자금을 모으고 운용하는 방식입니다. 협력과 신뢰를 기반으로 목돈을 보다 효과적으로 마련하고 활용하는 금융 방식이죠. 2.... ',
   'bloggername': '아임인 공식 블로그',
   'bloggerlink': 'blog.naver.com/flyfirst0101',
   'postdate': '20250309'},
  {'title': '서울<b>핀테크</b>랩, ‘<b>핀테크</b> 스타트업을 위한 정부지원사업·R&amp;D... ',
   'link': 'https://blog.naver.com/venturesquare_/223727540072',
   'description': '3부에서는 사전 신청한 <b>핀테크</b> 기업들을 대상으로 연사들과의 <b>1</b>:<b>1</b> 멘토링이 진행되었으며, 각 기업에 맞춘 정부지원사업에 대한 맞춤형 조언과 지원 방안이 논의됐다. 서희동 센터장은 “이번 컨퍼런스가... ',
   'bloggername': 'VentureSquare',
   'bloggerlink': 'blog.naver.com/venturesquare_',
   'postdate': '20250116'},
  {'title': '<b>핀테크</b> 뜻, 종류와 기업은?',
   'link': 'https://blog.naver.com/kubkun/223672721826',
   'description': '✅ 핀테크의 흐름 과거 <b>핀테크 1</b>.0과 2.0의 경우 기존 금융회사가 흐름을 주도하였다면, 최근 핀테크 3.... 대표하는 핀테크 기업 5곳은? 1) 카카오페이 카카오톡과 연동된 모바일 결제 및 금융서비스를 지원하는... ',
   'bloggername': '직장인 경제노트',
   'bloggerlink': 'blog.naver.com/kubkun',
   'postdate': '20241125'},
  {'title': '<b>핀테크</b> 서비스 소개 유익한 팁',
   'link': 'https://blog.naver.com/wdnwhtfure3/223793872195',
   'description': '&quot;<b>1</b>. <b>핀테크</b> 서비스의 현황과 필요성&quot; 최근 통계 자료에 따르면, 2023년 전 세계 <b>핀테크</b> 시장 규모는 약 <b>1</b>,600억 달러에 달하며, 2027년까지 연평균 25% 성장할 것으로 예상됩니다. 이는 금융업계에 큰 변화를... ',
   'bloggername': 'wdnwhtfure3님의블로그',
   'bloggerlink': 'blog.naver.com/wdnwhtfure3',
   'postdate': '20250312'},
  {'title': '[4/14까지][서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고... ',
   'link': 'https://blog.naver.com/ilsinbc/223800254706',
   'description': '기술 [서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고(서울형 R&amp;D 지원사업) 소관부처·지자체 : 서울특별시 사업수행기관 : 서울경제진흥원 신청기간 : 2025.03.25 ~ 2025.04.14 사업개요 2025년 <b>핀테크</b>... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250318'},
  {'title': '[기자단 뉴스] 원자재 가격 상승에 따른 <b>핀테크</b> 기업의 기회',
   'link': 'https://blog.naver.com/koreafintech/223293854875',
   'description': '출처: 무료 사진 사이트(pixabay) <b>1</b>. <b>핀테크</b>의 기회①: 센트비 등 해외송금 및 결제 기업 첫 번째로는 바로 해외송금 및 결제 서비스를 출시한 기업들입니다. 이 기업들은 수출입이 주로 이뤄지는 기업들을 겨냥해... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20231215'},
  {'title': 'K-<b>핀테크</b> 글로벌화 지원',
   'link': 'https://blog.naver.com/blogfsc/223751332542',
   'description': '지원계획 <b>1</b>. 정부와 금융회사가 연계하여 <b>핀테크</b> 기업의 해외 진출을 본격적으로 지원합니다. 해외 현지 보육, 투자IR 실시, 박람회에 K-Fintech관 개설 등 2. 코리아 <b>핀테크</b> 위크(11월 개최 예정)가... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20250207'},
  {'title': '공인인증서 대체까지 | 금융거래, 인터넷뱅킹, 공동인증서, <b>핀테크</b>',
   'link': 'https://blog.naver.com/ssg8654/223775988479',
   'description': '<b>1</b>. 금융인증서, 공인인증서와 무엇이 다른가요 간편하게 비교해보세요! 금융인증서 사용 완벽 가이드| 간편 로그인부터 공인인증서 대체까지 | 금융거래, 인터넷뱅킹, 공동인증서, <b>핀테크</b> 금융인증서... ',
   'bloggername': '플카소',
   'bloggerlink': 'blog.naver.com/ssg8654',
   'postdate': '20250227'},
  {'title': '[기업 분석] 누 홀딩스, 베일리 기포드가 주목하는 <b>핀테크</b> 기업',
   'link': 'https://blog.naver.com/chod46/223445773881',
   'description': '경험 있고 능숙한 경영진 <b>1</b>) <b>핀테크</b> 분야의 전문가 : 누 홀딩스의 경영진은 <b>핀테크</b> 분야에서 오랜 경험을 가진 전문가들로 구성되어 있으며, 시장 트렌드를 잘 파악하고 있습니다. 2) 뛰어난 실행력 : 혁신적인... ',
   'bloggername': '쩡쓰의 재테크 공부방',
   'bloggerlink': 'blog.naver.com/chod46',
   'postdate': '20240523'},
  {'title': 'Effects <b>핀테크</b>의 부정적 결과, 시냅스의 파산과... ',
   'link': 'https://blog.naver.com/chagall-kim/223808195031',
   'description': '발전하는 <b>핀테크</b> 산업 <b>1</b>. The collapse of fintech Synapse has exposed vulnerabilities in the banking-as-a-service model, leaving over 100,000 Americans unable to access their funds. <b>핀테크</b> 기업... ',
   'bloggername': '김샤갈 블로그',
   'bloggerlink': 'blog.naver.com/chagall-kim',
   'postdate': '20250325'},
  {'title': 'B2B <b>핀테크</b> 리더 웹케시그룹 공식 홈페이지 한눈에 보기',
   'link': 'https://blog.naver.com/webcashgroup/223767428095',
   'description': '대한민국 No.<b>1</b> B2B <b>핀테크</b> &amp; SaaS 전문 기업 웹케시그룹의 브랜드 아이덴티티를 살리면서 직관적인 UX/UI 디자인을 적용해 사용자가 필요한 정보를 쉽게 찾을 수 있도록 구성되어 있죠. 메인 화면에서 가장 눈에... ',
   'bloggername': '웹케시그룹 공식 블로그',
   'bloggerlink': 'blog.naver.com/webcashgroup',
   'postdate': '20250220'},
  {'title': '<b>핀테크</b> 뜻 의미 기술적 발전 경제 전망',
   'link': 'https://blog.naver.com/goldmyth/223493612882',
   'description': "<b>1</b>. <b>핀테크</b> 뜻 2. <b>핀테크</b> 유래 3. <b>핀테크</b> 전망 4. 기술적 발전이 경제에 미칠 영향 5. 결론 <b>핀테크</b> 뜻 <b>핀테크</b>(FinTech)의 뜻과 의미 <b>핀테크</b>(FinTech)는 '금융(Finance)'과 '기술(Technology)'의 합성어로, 첨단 기술을 금융... ",
   'bloggername': '경제인간',
   'bloggerlink': 'blog.naver.com/goldmyth',
   'postdate': '20240627'},
  {'title': '<b>핀테크</b> 테크핀, 차이점과 미래 전망',
   'link': 'https://blog.naver.com/kimshzeus/223801982283',
   'description': '<b>1</b>. <b>핀테크</b>와 테크핀, 뭐가 다를까? 디지털 금융 혁신이 가속화되면서 핀케트와 테크핀이 주목받고 있다고 전해졌습니다. 두 개념음 비슷해 보이지만 근본적인 차이가 있다고 덧붙였습니다. <b>핀테크</b>(FinTech)... ',
   'bloggername': '재테크 공략집✨️ 돈이 스스로 일하게 만드는 방법',
   'bloggerlink': 'blog.naver.com/kimshzeus',
   'postdate': '20250319'},
  {'title': '왜 지금 <b>핀테크</b>인가',
   'link': 'https://blog.naver.com/acastaredu/223710462111',
   'description': '커리큘럼 소개  이 과정의 커리큘럼은 다음과 같이 구성되어 있습니다: <b>1</b>. <b>핀테크</b>의 기본 이해 <b>핀테크</b>의 정의와 역사 기존 금융 시스템과의 차이점 분석 2. 주요 기술과 활용 사례 블록체인과 디지털 결제의 혁신... ',
   'bloggername': 'Your HRD partner 아카스타',
   'bloggerlink': 'blog.naver.com/acastaredu',
   'postdate': '20250102'},
  {'title': '<b>핀테크</b>와 핵심 트렌드',
   'link': 'https://blog.naver.com/dearz-/223809638725',
   'description': '우리나라는 포지티브 방식의 법체계와 개별 금융업법에서 금융규제의 요건을 엄격하게 정하고 있어 유연 제도 운영 어려움 2. 추진 전략 <b>1</b>) <b>핀테크</b> 활성화 촉진 2) 성숙한 <b>핀테크</b> 분야에 대한 상시감시 강화',
   'bloggername': 'dear u',
   'bloggerlink': 'blog.naver.com/dearz-',
   'postdate': '20250325'},
  {'title': '<b>핀테크</b>',
   'link': 'https://blog.naver.com/geunyang_chl_4/223813964030',
   'description': '<b>1</b>. <b>핀테크</b>, 금융의 룰을 다시 쓰다 **<b>핀테크</b>(Fintech)**는 ‘금융(Finance)’과 ‘기술(Technology)’의 합성어로, 디지털 기술을 활용해 기존 금융 서비스를 혁신하는 산업을 말합니다. 간편결제, 인터넷은행... ',
   'bloggername': 'geunyang_chl_4님의 블로그',
   'bloggerlink': 'blog.naver.com/geunyang_chl_4',
   'postdate': '20250329'},
  {'title': '[금융규제 샌드박스] <b>핀테크</b> 종합 지원실 OPEN',
   'link': 'https://blog.naver.com/koreafintech/223092600816',
   'description': '상담신청 https://fintech.or.kr/ 접속 → 기업회원 가입 → 금융혁신지원플랫폼(상단메뉴) → <b>핀테크</b> 상담신청 상담 유형 분류 절차 연계 상담신청내용을 바탕으로 유형 분류 일반상담 : <b>1</b>.<b>핀테크</b>기업... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20230503'},
  {'title': "공유까지…디지털금융 경쟁력 키우는 '서울 <b>핀테크</b> 위크' 개막",
   'link': 'https://blog.naver.com/economyseoul/223222110244',
   'description': '한국 <b>핀테크1</b>호 유니콘기업 (주)비바리퍼블리카 이승건 대표 &quot;핀테크는 어떻게 사회적 효용을 만드는가&quot; ▲제2회 피노베이션챌린지 어워즈▲ _27:1 경쟁률 끝에 선발된 유망핀테크 기업 6개 중 상위 3개... ',
   'bloggername': '서코노미',
   'bloggerlink': 'blog.naver.com/economyseoul',
   'postdate': '20230926'},
  {'title': 'K-<b>핀테크</b> 글로벌화를 통한 성장(Scale-up) 지원',
   'link': 'https://blog.naver.com/blogfsc/223749886170',
   'description': '해외 박람회(싱가포르, 홍콩 등)와 일정을 연계하고, 해외 <b>핀테크</b> 기업 참가 및 국가관 추가 등 글로벌존을 확대한다. 또한, 전시장 규모를 확장(<b>1</b>.6배)하고, AI 등 글로벌 트렌드를 경험할 수 있도록 하여... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20250206'},
  {'title': '2025 토스 대규모 경력채용 | <b>핀테크</b> No.1에서 커리어 성장... ',
   'link': 'https://blog.naver.com/kim_pro-/223816110029',
   'description': '<b>핀테크</b> 업계 커리어를 꿈꾸신다면 지금이 기회!  (직군별 상세 모집 공고 확인 가능) <b>1</b>. 토스, 어떤 기업인가요? 토스는 토스뱅크, 토스증권, 토스페이먼츠, 토스인슈어런스 등 계열사를 보유한 국내 대표... ',
   'bloggername': '김프로의 지식공유방',
   'bloggerlink': 'blog.naver.com/kim_pro-',
   'postdate': '20250331'},
  {'title': '올라 선정산에 생긴 일(올라<b>핀테크 1</b>월 뉴스 모음)',
   'link': 'https://blog.naver.com/allrafintech/223007807865',
   'description': '서비스 런칭 이후 <b>1</b>,500억 원 돌파까지 1년 반의 시간이 걸린 걸 생각하면 올라 선정산을 날이 갈수록... 올라<b>핀테크</b> 올라, 롯데온 선정산 출시 롯데ON 선정산 서비스 출시 지난 19일에는 롯데그룹 통합 온라인몰... ',
   'bloggername': '올라핀테크 공식블로그',
   'bloggerlink': 'blog.naver.com/allrafintech',
   'postdate': '20230207'},
  {'title': '분식회계? <b>핀테크</b>에서는 어떻게?',
   'link': 'https://blog.naver.com/happykdic/222392505388',
   'description': '(1) 가공매출액 계상 가공매출액이란 제품을 제조하지 않았음에도 불구하고 허위로 만들어진... 핀테크 회사 분식 회계 사례 - 와이어카드 독일의 <b>핀테크 1</b>위 기업으로 떠오르던 와이어카드는 1999년... ',
   'bloggername': '예금보험공사 블로그',
   'bloggerlink': 'blog.naver.com/happykdic',
   'postdate': '20210610'},
  {'title': '[<b>핀테크</b>] <b>1</b>. 금융과 IT의 결합 … 핀테크(Fintech)',
   'link': 'https://blog.naver.com/direa0609/220257463603',
   'description': '2015년의 기술 - <b>핀테크 1</b>. 금융과 IT의 결합 … 핀테크(Fintech) 2015년 핫 키워드 중 하나인 ‘핀테크(Fintech)’. 핀테크(Fintech)는 금융(Financial)과 기술(Technology)의 합성어로 오프라인 중심의 전통적... ',
   'bloggername': '연계, 데이터 기반 Enterprise S/W 기업',
   'bloggerlink': 'blog.naver.com/direa0609',
   'postdate': '20150130'},
  {'title': '핑거 : 스크래핑 기술로 <b>핀테크</b> 산업 리드',
   'link': 'https://blog.naver.com/mndmarketing/220801931432',
   'description': "윤태진의 아이라인업에서 우리나라 <b>핀테크 1</b>세대 기업을 찾아가 보았어요 :) 영등포에 위치한 오늘의 기업! 핀테크 사업과 함께 분야별 많은 계열사를 운영하고 있는 '핑거'입니다. 핑거는 2000년 설립되어... ",
   'bloggername': '주식회사 애드트리즈/대구교육영상/대구홍보영상',
   'bloggerlink': 'blog.naver.com/mndmarketing',
   'postdate': '20160901'},
  {'title': '[미국주식] 폭발적인 성장률의 미국 <b>핀테크</b>기업 스퀘어(SQ) 분석',
   'link': 'https://blog.naver.com/kgu3405/222124723456',
   'description': '잭 도시는 이 부분에 착안하여 국내 카카오뱅크(페이) 등 핀테크와 유사한 사업을 시작합니다.... 48% (그냥저냥) - Current Ratio(MRQ) : 1.7 (현금성 좋음) - Debt to Equity(MRQ) : 137.84% (적정) 정리하면... <b>핀테크 1</b>등... ',
   'bloggername': '멍멍짱구 작업실',
   'bloggerlink': 'blog.naver.com/kgu3405',
   'postdate': '20201023'},
  {'title': '<b>핀테크 1</b>위를 넘어 은행업계 도장깨러 다니는 차임',
   'link': 'https://blog.naver.com/88nsb/222208702529',
   'description': '<b>핀테크</b>에 대한 이슈는 여전히 계속되고 있습니다. 한국에서는 인터넷 은행 이슈로 토스, K 뱅크... 한편, 미국 <b>핀테크</b>는 전통 은행도 긴장을 할정도로 파격적인데요. 차임 이야기입니다. 미국은 한국 은행과... ',
   'bloggername': '투 머취 마켓',
   'bloggerlink': 'blog.naver.com/88nsb',
   'postdate': '20210115'},
  {'title': '[국회의원 민병두] <b>핀테크</b>를 넘어 테크핀이 온다 (페북글)',
   'link': 'https://blog.naver.com/byungdusi/221521504055',
   'description': '은행이 기술을 보조수단으로 사용하는 핀테크가 아니라, 기술이 금융을 주도하는 시대가 올 수 있다.<b>핀테크 1</b>위국가 중국을 보면 미래가 보인다.기존의 금산분리를 넘어선 융합에... ',
   'bloggername': '혁신디자이너',
   'bloggerlink': 'blog.naver.com/byungdusi',
   'postdate': '20190424'},
  {'title': '[슬기로운 <b>핀테크</b> 생활] # 8편... 포인트도 적립하는 <b>핀테크</b>!',
   'link': 'https://blog.naver.com/koreafintech/223509421687',
   'description': '그린 <b>핀테크</b>의 장점 <b>1</b>. 기후 변화 완화 탄소배출 감소로 대기 중의 오염 물질을 줄여 삶의 질을 높이고 환경 친화적인 세상을 만듭니다. 2. 지속 가능한 생활 습관 형성 간편하게 실천 가능하며, 접근성이... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20240711'},
  {'title': '겨냥한 한국 <b>핀테크</b>, 이커머스 스타트업의 블루오션 인도네시아!',
   'link': 'https://blog.naver.com/cufspr/222660222432',
   'description': '인도네시아 진출 유망 사업군 1. <b>핀테크 1</b>) 핀테크란? 핀테크란 금융(Fincance)과 기술(Tech)이 결합된 플랫폼 서비스입니다. 금융과 IT 정보기술, 서로 다른 분야가 융합해 금융산업에 새로운 바람을 불러일으키고... ',
   'bloggername': '사이버한국외국어대학교',
   'bloggerlink': 'blog.naver.com/cufspr',
   'postdate': '20220301'},
  {'title': '<b>핀테크</b>와 인공지능, 금융의 미래를 열다. 코리아 <b>핀테크</b>... ',
   'link': 'https://blog.naver.com/blogfsc/223526275714',
   'description': '<b>1</b>. <b>핀테크</b>와 인공지능, 금융의 미래를 열다. 8월 27일(화) 14:20~ 세션 <b>1</b>: 글로벌 토크콘서트 생성형 AI 기술에 따른 <b>핀테크</b> 산업의 우수 사례와 향후 전망을 제시하고, AI 금융과 <b>핀테크</b> 글로벌... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20240726'},
  {'title': '2015.01.30 <b>핀테크</b> 2) 해외사례 분석',
   'link': 'https://blog.naver.com/taeun21/220257035052',

In [ ]:
payload

In [ ]:
headers

네이버 검색 API를 이용해서 책을 검색하고 결과를 데이터프레임으로 만드세요
* 검색어는 input()을 이용해서 입력받은 값을 이용하세요.

In [ ]:
import requests
import pandas as pd

In [ ]:
bookurl = "https://openapi.naver.com/v1/search/book.json"
bookname = input("책이름을 검색하세요: ")

payload = {'query': bookname, 'display' : 100, 'start': 1, 'sort':"sim" }
headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
r = requests.get(bookurl, params=payload, headers = headers)
data = r.json()
data

In [ ]:
result2 = {}
for item in data['items'] :
    for key, value in item.items():
        result2.setdefault(key, []).append(value)
df2 = pd.DataFrame(result2)
df2

In [ ]:
result2 = {}
for item in data['items'] :
    for key, value in item.items():
        result2.setdefault(key, []).append(value)
df2 = pd.DataFrame(result2)
df2

* 풀이

In [53]:
import requests
import pandas as pd
# pandas 에 넣어서 표로 나오게 하려면 딕셔너리 형태로 넣어야 함.

In [54]:
def json_unpack(data):
    result = {}
    for item in data['items'] :
        for key, value in item.items():
            result.setdefault(key, []).append(value)
    df = pd.DataFrame(result)
    return df

In [57]:
keyword = input("키워드를 입력해 주세요: ")

키워드를 입력해 주세요: 핀테크

In [58]:

url = "https://openapi.naver.com/v1/search/book.json"
headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
params  = dict(query=keyword, display = 100, start = 1, sort = "sim")
r = requests.get(url, params=params, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()

print("전체데이터 검색 수 :", data['total'], "검색할 페이지수:", (int(data['total'])//100)+1)

https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체데이터 검색 수 : 106 검색할 페이지수: 2

In [59]:
result_df = json_unpack(data)
result_df

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,핀테크,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324383...,한석주,11400,커뮤니케이션북스,20151101,9791130441436,디지털 기술의 발달은 금융의 모든 것을 바꾸고 있다. 기술 기반의 스타트업들과 비금...
1,핀테크 (IT와 금융이 만나는 새로운 세상),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325064...,강창호,0,한빛미디어,20150605,9788968482007,금융과 기술로 혁신하는 핀테크 시장을 선점하라!\n\n상시 연결된 디지털 세상에서 ...
2,핀테크 4.0 (핀테크 혁명과 금융의 미래),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_520007...,김종현,17100,한국금융연수원,20241216,9788928782284,본서에서는 세계 최초로 핀테크 산업의 발전을 4단계로 구분하여 설명하는 [핀테크 4...
3,핀테크와 법 (제3판),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324417...,강현구^유주선^이성남,19800,씨아이알,20201112,9791156109020,핀테크의 영역과 그에 대한 법률문제의 간격을 \n어떻게 좁힐 수 있을 것인가\n\n...
4,핀테크 전쟁 (세계 금융 시장의 거대한 트렌드 | 새로운 돈의 시대가 온다),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324666...,브렛 킹,13500,예문,20150612,9788956592503,"다가오는 미래, 달라지는 금융의 패러다임을 한 권으로 읽는다!\n\n핀테크란 금융을..."
...,...,...,...,...,...,...,...,...,...
95,"2025 4차산업 AI기업·스타트업 주소록 (3D프린터, IOT, VR, 가상현실,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_538071...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20250221,9791172342869,"4차산업 AI기업·스타트업 주소록을 분야별, 지역별로 22,696건, IT기업 상세..."
96,핀테크 산업의 국내외 시장동향과 관련 서비스 현황 및 기술/활용사례 분석,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324893...,좋은정보사,306000,좋은정보사,20180614,9788998586409,국내 핀테크 산업은 해외 업체들에 뒤지지않는 경쟁력과 아이디어를 가지고 있음에도 불...
97,핀테크(FinTech)산업 동향전망과 정보보호산업 기술현황 실태분석,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,지식산업정보원 R&D정보센터,288000,지식산업정보원,20150325,9788994111032,핀테크 및 보안 관련 산업의 국내외 최신 동향을 분석하고 글로벌 시장 선점을 위한 ...
98,스마트 금융 시대를 선도하는 핀테크 관련 신사업전략 모색을 위한 종합 분석,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324559...,IRS Global 편집부,315000,아이알에스글로벌,20150401,9788998207250,"이 책은 ‘2014년 모바일(간편)결제’에 이은 두 번째 핀테크 관련 보고서로, 국..."
99,IoT기반 근거리 무선통신 핀테크 산업 현황과 무선전력 전송 및 무선충전 기술개발 동향,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324975...,TF정보분석실,279000,트렌드포커스,20150709,9791195558117,IoT는 작년에 이어 올해에도 ICT 시장을 뜨겁게 달구는 키워드 중 하나입니다.\...

In [60]:
data['total']

106

In [ ]:
r = requests.get(url, params=params, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
data
result_df = json_unpack(data)
result_df

In [ ]:
result = {}
for item in data['items'] :
    for key, value in item.items():
        result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

# 네이버 API로 검색한 결과 최대한 가져오기
* 1회 네이버 서버에 요청
* 응답해서 total 찾아서 display로 나누어 총 반복할 페이지 산출
* 반복문 작성 및 종료 조건 설정
* 1페이지 결과를 데이터 프레임으로 만들고 리스트에 append
* 반복이 끝난 후 리스트에 aapend 된 데이터 프레임을 1개로 합치기

In [ ]:
import requests
import pandas as pd

In [ ]:
search = input("키워드를 입력해 주세요: ")

In [ ]:
url = "https://openapi.naver.com/v1/search/book.json"
headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
params  = dict(query=keyword, display = 100, start = 1, sort = "sim")
r = requests.get(url, params=params, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()

print("전체데이터 검색 수 :", data['total'], "검색할 페이지수:", (int(data['total'])//100)+1)

In [ ]:

df_list = []

for page in range(1, max_pages + 1):
    start = (page - 1) * display + 1
    if start > total_results:
        for item in data['items'] :
            for key, value in item.items():
                result = {}
                result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

In [ ]:
total_results = data['total']
display = 100
max_pages = (total_results // display) + 1

In [ ]:
df_list = []

for page in range(1, max_pages + 1):
    start = (page - 1) * display + 1  # 시작 인덱스 계산
    if start > total_results:  # 종료 조건 (total보다 큰 start는 의미 없음)
        break

In [ ]:
print(df_list)

In [ ]:
payload['start'] = start
response = requests.get(bookurl, params=payload, headers=headers)
page_data = response.json()

In [ ]:
df_l = pd.DataFrame(df_list)
df_l

In [ ]:
def json_unpack(data):
    result = {}
    for item in data['items'] :
        for key, value in item.items():
            result.setdefault(key, []).append(value)
    df = pd.DataFrame(result)
    return df

# 풀이 1. while

In [ ]:
import requests
import pandas as pd

In [ ]:
keyword = input("검색 키워드를 입력하세요")

In [ ]:
all_data2 = []
start = 1
while True:
    url = "https://openapi.naver.com/v1/search/book.json"
    headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
    params  = dict(query=keyword, display = 100, start = start, sort = "sim")
    r = requests.get(url, params=params, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data['total']
    total_pages = (int(data['total'])//100)+1
    print("전체데이터 검색 수 :", n_data, "검색할 페이지수:", total_pages)
    result_df = json_unpack(data)
    all_data2.append(result_df)
    if start == 1000 :
        break
    elif start < 901 :
        start += 100
    elif start == 901:
        start += 99

In [ ]:
len(all_data2)

In [ ]:
final_result2 = pd.concat(all_data2)
final_result2 = final_result2.reset_index(drop=True)
final_result2

In [ ]:
final_result2.to_csv("네이버검색_책_파이썬.csv", encoding="utf-8-sig", index=False)

In [ ]:
url = "https://openapi.naver.com/v1/search/book.json"
headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
params  = dict(query=keyword, display = 100, start = 1000, sort = "sim")
r = requests.get(url, params=params, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
print("전체데이터 검색 수 :", data['total'], "검색할 페이지수:", (int(data['total'])//100)+1)
result_df = json_unpack(data)
result_df

# 풀이 2. for

In [ ]:
all_data = []

In [ ]:

url = "https://openapi.naver.com/v1/search/book.json"
headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
params  = dict(query=keyword, display = 100, start = 1, sort = "sim")
r = requests.get(url, params=params, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
n_data = data['total']
total_pages = (int(data['total'])//100)+1

print("전체데이터 검색 수 :", n_data, "검색할 페이지수:", total_pages)

result_df = json_unpack(data)
all_data.append(result_df)

In [ ]:
start = 101
for page in range(total_pages) :
    print(f"{page+1} {total_pages} 수집중" , end="\r")
    url = "https://openapi.naver.com/v1/search/book.json"
    headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
    params  = dict(query=keyword, display = 100, start = start, sort = "sim")
    r = requests.get(url, params=params, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data['total']
    total_pages = (int(data['total'])//100)+1
#     print("전체데이터 검색 수 :", n_data, "검색할 페이지수:", total_pages)
    result_df = json_unpack(data)
    all_data.append(result_df)
    if start == 1000:
        break
    elif start < 900 :
        start += 100
        # elif 는 조건을 만족하면 다른 elif 문은 실행 안함.
    elif start == 901 :
        start += 99

In [ ]:
len(all_data)

In [ ]:
final_result = pd.concat(all_data)
final_result = final_result.reset_index(drop=True) # 각 테이블마다 번호가 인덱싱 되어 있는걸 합친 테이블에 다시 인덱싱하기
final_result

# 뉴스, 블로그, 책 한번에 저장하기

In [61]:
all_data3 = []
start = 1
for category in ["blog", "news", "book"]:
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym","X-Naver-Client-Secret" : "46NsuGC17a"}
        params  = dict(query=keyword, display = 100, start = 1000, sort = "sim")
        r = requests.get(url, params=params, headers=headers)
        print(r.url)
        print(r.status_code)
        data = r.json()
        n_data = data['total']
        total_pages = (int(data['total'])//100)+1
        print("전체데이터 검색 수 :", n_data, "검색할 페이지수:", total_pages)
        result_df = json_unpack(data)
        all_data3.append(result_df)
        if start == 1000 :
            break
        elif start < 901 :
            start += 100
        elif start == 901:
            start += 99
final_result3 = pd.concat(all_data3)
final_result3 = final_result3.reset_index(drop=True)
final_result3

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 456179 검색할 페이지수: 4562
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 498193 검색할 페이지수: 4982
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체데이터 검색 수 : 106 검색할 페이지수: 2

,title,link,description,bloggername,bloggerlink,postdate,originallink,pubDate
0,제2회 ｢금융회사-<b>핀테크</b>기업 상호만남(Meet-Up)｣ 행사 개최,https://blog.naver.com/blogfsc/223399382531,- 지정대리인·위탁테스트 제도 활성화를 위해 금융회사-<b>핀테크</b>기업 간 협...,금융위원회 공식 블로그,blog.naver.com/blogfsc,20240329,NaN,NaN
1,"금융당국, <b>핀테크</b> 우수기업 K-Fintech 30 선정",https://blog.naver.com/happykdic/223271903101,"오늘 제가 소개할 주제는 ‘금융당국, <b>핀테크</b> 우수기업K-Fintech ...",예금보험공사 블로그,blog.naver.com/happykdic,20231122,NaN,NaN
2,당신의 지갑 속 혁명: <b>핀테크</b>가 바꾸는 금융의 미래,https://blog.naver.com/housingk07r/223785252660,"당신의 지갑 속 혁명: <b>핀테크</b>가 바꾸는 금융의 미래 몇 년 전, 지갑을...",새미로로,blog.naver.com/housingk07r,20250306,NaN,NaN
3,<b>핀테크</b>란 무엇인가?,https://blog.naver.com/consultant712/223801138183,<b>핀테크</b>(FinTech)는 금융(Finance)과 기술(Technolog...,consultant712님의 블로그,blog.naver.com/consultant712,20250318,NaN,NaN
4,스테이블코인과 <b>핀테크</b> 기업의 역할: 미래를 선도하는 두 축,https://blog.naver.com/hzfo7fzm76vkr/223786343178,오늘은 금융 기술의 혁신이 가져온 새로운 변화 중에서도 특히 스테이블코인과 <b>핀...,하나의 기억,blog.naver.com/hzfo7fzm76vkr,20250311,NaN,NaN
...,...,...,...,...,...,...,...,...
1195,"아이쿠카, 수원중부경찰서와 아동 실종 예방 '지문 사전등록 캠페인' 진...",https://n.news.naver.com/mnews/article/008/000...,키즈 <b>핀테크</b> 플랫폼 아이쿠카(대표 방남진)가 수원중부경찰서(서장 총경 ...,NaN,NaN,NaN,http://news.mt.co.kr/mtview.php?no=20250314131...,"Tue, 18 Mar 2025 17:07:00 +0900"
1196,"헥토파이낸셜, 무인 유통매장 관리 솔루션 '오더인' 출시",https://www.smartfn.co.kr/news/articleView.htm...,<b>핀테크</b> 기업 헥토파이낸셜이 무인 아이스크림 매장 등 무인 유통매장 운영...,NaN,NaN,NaN,https://www.smartfn.co.kr/news/articleView.htm...,"Tue, 18 Mar 2025 09:36:00 +0900"
1197,"우리금융, 금융권 최초 블록체인 스타트업 육성에 본격화 '디노랩 B센터...",https://www.eroun.net/news/articleView.html?id...,"부산시는 블록체인 규제자유특구로 사업 연계 가능성 확대블록체인, <b>핀테크</b>...",NaN,NaN,NaN,https://www.eroun.net/news/articleView.html?id...,"Fri, 14 Mar 2025 11:18:00 +0900"
1198,"업비트 송치형 회장, 가상자산 이상거래 신고센터 운영...“건전하고 투...",https://www.socialvalue.kr/news/view/106557491...,블록체인 및 <b>핀테크</b> 전문기업 두나무(대표 이석우)는 업비트 이상거래 신...,NaN,NaN,NaN,https://www.socialvalue.kr/news/view/106557491...,"Mon, 24 Mar 2025 10:20:00 +0900"
1199,<b>핀테크</b>·TCB 8개사 CEO “AI 활용 확대로 신용평가 고도화 투자 ...,http://www.fntimes.com/html/view.php?ud=202503...,<b>핀테크</b>사와 신용조회사 CEO들이 AI 활용에 가장 중점을 둔 분야로 신...,NaN,NaN,NaN,http://www.fntimes.com/html/view.php?ud=202503...,"Tue, 04 Mar 2025 00:02:00 +0900"

In [63]:
test = pd.DataFrame(final_result3)
test

,title,link,description,bloggername,bloggerlink,postdate,originallink,pubDate
0,제2회 ｢금융회사-<b>핀테크</b>기업 상호만남(Meet-Up)｣ 행사 개최,https://blog.naver.com/blogfsc/223399382531,- 지정대리인·위탁테스트 제도 활성화를 위해 금융회사-<b>핀테크</b>기업 간 협...,금융위원회 공식 블로그,blog.naver.com/blogfsc,20240329,NaN,NaN
1,"금융당국, <b>핀테크</b> 우수기업 K-Fintech 30 선정",https://blog.naver.com/happykdic/223271903101,"오늘 제가 소개할 주제는 ‘금융당국, <b>핀테크</b> 우수기업K-Fintech ...",예금보험공사 블로그,blog.naver.com/happykdic,20231122,NaN,NaN
2,당신의 지갑 속 혁명: <b>핀테크</b>가 바꾸는 금융의 미래,https://blog.naver.com/housingk07r/223785252660,"당신의 지갑 속 혁명: <b>핀테크</b>가 바꾸는 금융의 미래 몇 년 전, 지갑을...",새미로로,blog.naver.com/housingk07r,20250306,NaN,NaN
3,<b>핀테크</b>란 무엇인가?,https://blog.naver.com/consultant712/223801138183,<b>핀테크</b>(FinTech)는 금융(Finance)과 기술(Technolog...,consultant712님의 블로그,blog.naver.com/consultant712,20250318,NaN,NaN
4,스테이블코인과 <b>핀테크</b> 기업의 역할: 미래를 선도하는 두 축,https://blog.naver.com/hzfo7fzm76vkr/223786343178,오늘은 금융 기술의 혁신이 가져온 새로운 변화 중에서도 특히 스테이블코인과 <b>핀...,하나의 기억,blog.naver.com/hzfo7fzm76vkr,20250311,NaN,NaN
...,...,...,...,...,...,...,...,...
1195,"아이쿠카, 수원중부경찰서와 아동 실종 예방 '지문 사전등록 캠페인' 진...",https://n.news.naver.com/mnews/article/008/000...,키즈 <b>핀테크</b> 플랫폼 아이쿠카(대표 방남진)가 수원중부경찰서(서장 총경 ...,NaN,NaN,NaN,http://news.mt.co.kr/mtview.php?no=20250314131...,"Tue, 18 Mar 2025 17:07:00 +0900"
1196,"헥토파이낸셜, 무인 유통매장 관리 솔루션 '오더인' 출시",https://www.smartfn.co.kr/news/articleView.htm...,<b>핀테크</b> 기업 헥토파이낸셜이 무인 아이스크림 매장 등 무인 유통매장 운영...,NaN,NaN,NaN,https://www.smartfn.co.kr/news/articleView.htm...,"Tue, 18 Mar 2025 09:36:00 +0900"
1197,"우리금융, 금융권 최초 블록체인 스타트업 육성에 본격화 '디노랩 B센터...",https://www.eroun.net/news/articleView.html?id...,"부산시는 블록체인 규제자유특구로 사업 연계 가능성 확대블록체인, <b>핀테크</b>...",NaN,NaN,NaN,https://www.eroun.net/news/articleView.html?id...,"Fri, 14 Mar 2025 11:18:00 +0900"
1198,"업비트 송치형 회장, 가상자산 이상거래 신고센터 운영...“건전하고 투...",https://www.socialvalue.kr/news/view/106557491...,블록체인 및 <b>핀테크</b> 전문기업 두나무(대표 이석우)는 업비트 이상거래 신...,NaN,NaN,NaN,https://www.socialvalue.kr/news/view/106557491...,"Mon, 24 Mar 2025 10:20:00 +0900"
1199,<b>핀테크</b>·TCB 8개사 CEO “AI 활용 확대로 신용평가 고도화 투자 ...,http://www.fntimes.com/html/view.php?ud=202503...,<b>핀테크</b>사와 신용조회사 CEO들이 AI 활용에 가장 중점을 둔 분야로 신...,NaN,NaN,NaN,http://www.fntimes.com/html/view.php?ud=202503...,"Tue, 04 Mar 2025 00:02:00 +0900"

# 블로그, 뉴스 책, 데이터 각각 저장하기

In [130]:
import requests
import time
keyword = input("검색할 키워드를 입력해 주세요 :")
response_blog=[]
response_news = []
response_book = []

for category in ["blog", "news", "book"]:
    response_result = []
    page = 1
    start_num2 = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym",
                   "X-Naver-Client-Secret" : "46NsuGC17a"}
        params  = dict(query=keyword, display = 100, start = start_num2, sort = "sim")

        r = requests.get(url, params=params, headers=headers)
        print(r.url, end="\r")
        print(r.status_code, end="\r")
        response = r.json()
        total_pages = (response['total']//100)+1

        if category == 'blog':
            response_blog.append(response)
        elif category == 'news' :
            response_news.append(response)
        elif category == 'book' :
            response_book.append(response)

        if start_num2 == 1000 :
            break
        elif start_num2 < 901 :
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99

        if page < total_pages:
            page += 1
        else :
            break
        time.sleep(0.2)
r1=pd.DataFrame(response)
r1

검색할 키워드를 입력해 주세요 :인공지능

,lastBuildDate,total,start,display,items
0,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,{'title': '미래 인공지능으로 황제재벌기 1 (보랑빛노을 현대 판타지 장편소...
1,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,"{'title': '인공지능 시대와 초등사회과 교육 (초등교사와 학부모를 위한)',..."
2,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,{'title': '인공지능이 바꾸는 미래 비즈니스 (4차 산업혁명 시대의 기업 경...
3,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,{'title': '인공지능 머디봇을 이긴 짱뚱어들 (국립생태원 제2회 생태동화 공...
4,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,{'title': '인공지능을 넘어서는 인간의 강점 (인간의 통찰력과 인공지능의 비...
...,...,...,...,...,...
95,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,"{'title': '브리태니커 만화 백과 51: 인공지능', 'link': 'htt..."
96,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,"{'title': '4차 산업혁명과 인공지능 영어교육 (제2판)', 'link': ..."
97,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,"{'title': '인공지능과 법률 서비스 분야의 혁신', 'link': 'http..."
98,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,"{'title': 'AI의 도전 (인공지능의 위협과 공존 그리고 기회)', 'lin..."
99,"Tue, 01 Apr 2025 14:30:34 +0900",2202,1000,100,"{'title': '인공지능 산업분야 주식투자 가이드', 'link': 'https..."

In [120]:
import requests
import time
keyword = input("검색할 키워드를 입력해 주세요 :")

def naver_search(category):
    response_result = []
    page = 1
    start_num2 = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        headers = {"X-Naver-Client-Id": "TaVTw3HnrpVGJDDGj3ym",
                   "X-Naver-Client-Secret" : "46NsuGC17a"}
        params  = dict(query=keyword, display = 100, start = start_num2, sort = "sim")

        r = requests.get(url, params=params, headers=headers)
        response = r.json()
        total_pages = (response['total']//100)+1
        response_result=totalpages.append(response)
        
        if start_num2 == 1000 :
            break
        elif start_num2 < 901 :
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99

        if page < total_pages:
            page += 1
        else :
            break
        time.sleep(0.2)
        
    return response_result

검색할 키워드를 입력해 주세요 :인공지능

In [121]:
df = pd.DataFrame(response_result)
df

NameError: name 'response_result' is not defined

In [92]:
import time
keyword = input("검색할 키워드를 입력해 주세요: ")
for category in ["blog", "news", "book"] :
    naver_search_result = naver_search(category)
    print(f"{category}_search_result:{len(naver_search_result)}")

검색할 키워드를 입력해 주세요: 인공지능
blog_search_result:0r.com/v1/search/blog.json?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&display=100&start=1000&sort=sim
news_search_result:0r.com/v1/search/news.json?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&display=100&start=1000&sort=sim
book_search_result:0r.com/v1/search/book.json?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&display=100&start=1000&sort=sim

In [93]:
len(naver_search_result)

0

In [65]:
import pandas as pd

In [104]:
def json_unpack(all_data):
    final_result={}
    for page in all_data :
        for items in page['items'][:1]:
            for key, value in item.items():
                final_result.setdefault(key, []).append(value)

    a = pd.DataFrame(final_result)
    return a

In [79]:
for jsons, cat in zip([response_blog,response_news, response_book], ["blog","news","book"]) :
    unpack_result = json_unpack(jsons)
    unpack_result.to_csv(f"naver_[cat]_result.csv", encoding="utf-8", index=False)

# 3개 카테고리 수집 코드를 함수화하기

In [102]:
a

,title,link,description,bloggername,bloggerlink,postdate
0,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
1,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
2,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
3,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
4,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
5,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
6,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
7,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
8,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
9,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112
10,"<b>핀테크</b> 뜻, 예시, 성공적인 사례 알아보기",https://blog.naver.com/haseobang83/223657527445,<b>1</b>. <b>핀테크</b> 뜻 <b>핀테크</b> 뜻부터 살펴볼게요. <...,더하임(The HEIM),blog.naver.com/haseobang83,20241112