# xml : html 처럼 태그 기반으로 자료를 저장한 포멧
* xml parser를 통해서 str을 xml로 변환하는 자겁이 필요
* xml로 변환이 되면 태그 기반으로 자료를 찾아 정리
* 태그에서 자료를 추출할 때는 beautifulsoup 이라는 라이브러리를 이용

In [1]:
import os
import requests
import json
import pandas as pd

In [2]:
def b_unpack(response) :
    b_list = {}
    for item in bank_info :
        for key, value in item.items() :
            b_list.setdefault(key, []).append(value)
    df = pd.DataFrame(b_list)
    return df

In [9]:
url = "http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
ServiceKey = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D"
ServiceKey_d = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7/i3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r+OytZGorS2lwOw=="
payload = {"serviceKey" : ServiceKey_d,
           "pageNo": 1,
           "numOfRows": 20,
           "dataType" : "json"}

r = requests.get(url, params=payload)
print(r.url, end = "\r")
print(r.status_code, end = "\r")
response=r.json()
final_result=b_unpack(response)
final_result

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111

In [4]:
bank_info = response['body']['items']

In [7]:
page = 1
b_result = []


while True:
    url = "http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
    ServiceKey = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D"
    ServiceKey_d = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7/i3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r+OytZGorS2lwOw=="
    payload = {"serviceKey" : ServiceKey_d,
               "pageNo": page,
               "numOfRows": 10,
               "dataType" : "json"}

    r = requests.get(url, params=payload)
    print(r.url, end = "\r")
    print(r.status_code, end = "\r")
    response=r.json()

    total_pages = (response['body']['totalCount']//10) +1
    print(f"{page}/{total_pages} 수집중: ", end="\r")
    b_result.append(b_unpack(response))
    

    if page < total_pages :
        page += 1
    else :
        break

result = pd.concat(b_result)
total_result = result.reset_index(drop=True)
total_result
# total_result.to_csv("은행대출금리정보.csv", encoding="utf-8-sig", index=False)

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
11,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
12,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
13,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
14,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
15,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
16,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
17,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
18,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
19,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111

* 풀이

In [ ]:
url = "http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
ServiceKey = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D"
ServiceKey_d = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7/i3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r+OytZGorS2lwOw=="
payload = {"serviceKey" : ServiceKey_d,
           "pageNo": page,
           "numOfRows": 10,
           "dataType" : "json"}

r = requests.get(url, params=payload)
print(r.url, end = "\r")
print(r.status_code, end = "\r")

In [18]:
url = "http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
ServiceKey = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D"
ServiceKey_d = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7/i3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r+OytZGorS2lwOw=="
payload = {"serviceKey" : ServiceKey_d,
           "pageNo": 1,
           "numOfRows": 10,
           "dataType" : "xml"}

r = requests.get(url, params=payload)
print(r.url, end = "\r")
print(r.status_code, end = "\r")
response=r.text
response

'<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>10</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item></items></body></response>'

* xml로 데이터를 받으면 처음에는 단순 문자열로 받게된다
* 문자열을 xml 문서로 변환해야 함
* beautifulsoup을 이용해 변환
* beautifulsoup의 메서드인 select, select_one을 이용해 css 셀렉터 기반으로 데이터가 위치한 태그를 찾아서 내용 추출

# BeautifulSoup
* https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 참고
* pip install beautifulsoup4
* from bs4 import BeautifulSoup
* find, find_all 함수: xml, html에서 태그기반으로 내용을 찾음
* select, select_one 함수 : xml, html에서 css selector 기반으로 내용을 찾음
* find_all, select는 해당태그나 css selector를 가진 부분을 모두 찾아서 리스트로 반환하는 함수
* find_all, select_one은 여러 태그나 css selector 중에서 가장 먼저 나오는 태그/selector를 한개만 찾아줌
* 찾아온 태그 .name : 태그 이름 반환
* 찾아온 태그 .text,.strint: 태그안쪽의 텍스트 반환

In [39]:
from bs4 import BeautifulSoup as bs

In [19]:
soup = bs(response, 'xml')
soup.select_one("resultCode")

In [20]:
soup

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>10</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item></items></body></response>

In [21]:
items = soup.select_one('items')
item = items.select("item")

In [22]:
for tag in items.select_one("item"):
    print(tag.name)

bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter

In [23]:
items = soup.select_one('items')
bssYmdStart_list = items.select("bssYmdStart")
interest4_1_list = items.select("interest4_1")
interest3_2_list= items.select("interest3_2")
interest4_2_list= items.select("interest4_2")
interest2_1_list= items.select("interest2_1")
interest1_2_list= items.select("nterest1_2")
interest3_1_list= items.select("interest3_1")
interest2_2_list= items.select("interest2_1")
interest1_1_list= items.select("interest1_1")
bssYmdEnd_list= items.select("bssYmdEnd")
organId_list= items.select("organId")
callCenter_list= items.select("callCenter")

In [24]:
tag_list = [bssYmdStart_list, interest4_1_list, interest3_2_list, interest4_2_list, interest2_1_list,
            interest1_2_list, interest3_1_list, interest2_2_list, interest1_1_list, bssYmdEnd_list, organId_list, callCenter_list]

In [25]:
result={}
for lists in tag_list:
    for item in lists:
        result.setdefault(item.name, []).append(item.text)
result

{'bssYmdStart': ['20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310'],
 'interest4_1': ['0',
  '0',
  '0',
  '4.89',
  '0',
  '4.26',
  '4.64',
  '3.5',
  '3.38',
  '4.18'],
 'interest3_2': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest4_2': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest2_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest3_1': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'interest1_1': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'],
 'bssYmdEnd': ['20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316'],
 'organId': ['산업은행',
  '제주은행',
  'SC은행',
  '전북은행',
  '수협은행',
  '우리은행',
  '경남은행',
  '카카오뱅크',
  '아이엠뱅크',
  '하나은행'],
 'callCenter': ['1588-1500',
  '1588-0079',
  '1588-1599',
  '1588-4477',
  '1588-1515',
  '1599-5000',
  '1588-8585',
  '1599-3333',
  '1588-5050',
  '1599-1111']}

In [26]:
final_df = pd.DataFrame(result)
final_df

ValueError: All arrays must be of the same length

In [27]:
for item_value in item:
    for tag in item_value:
df = pd.DataFrame(result)
result

IndentationError: expected an indented block (3033021835.py, line 3)

# 반복문으로 태그 자동 추출하기

In [28]:
soup.select("*")

[<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>10</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item></items></body></response>,
 <header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header>,
 <resultCode>00</resultCode>,
 <resultMsg>정상</resultMsg>,
 <body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>10</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item></items></body>,
 <pageNo>1</pageNo>,
 <totalCount>18</totalCount>,
 <numOfRows>10</numOfRows>,
 <items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item></items>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>0</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>산업은행</organId>,
 <callCenter>1588-1500</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>0</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>제주은행</organId>,
 <callCenter>1588-0079</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>0</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>SC은행</organId>,
 <callCenter>1588-1599</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>4.89</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>전북은행</organId>,
 <callCenter>1588-4477</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>0</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>수협은행</organId>,
 <callCenter>1588-1515</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>4.26</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>우리은행</organId>,
 <callCenter>1599-5000</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>4.64</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>경남은행</organId>,
 <callCenter>1588-8585</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>3.5</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>카카오뱅크</organId>,
 <callCenter>1599-3333</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>3.38</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>아이엠뱅크</organId>,
 <callCenter>1588-5050</callCenter>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item>,
 <bssYmdStart>20250310</bssYmdStart>,
 <interest4_1>4.18</interest4_1>,
 <interest3_2>0</interest3_2>,
 <interest4_2>0</interest4_2>,
 <interest2_1>0</interest2_1>,
 <interest1_2>0</interest1_2>,
 <interest3_1>0</interest3_1>,
 <interest2_2>0</interest2_2>,
 <interest1_1>0</interest1_1>,
 <bssYmdEnd>20250316</bssYmdEnd>,
 <organId>하나은행</organId>,
 <callCenter>1599-1111</callCenter>]

In [29]:
result = {}
for item in soup.select("items"):
    for tags in item:
        for tag in tags:
            result.setdefault(tag.name, []).append(tag.text)
result
df = pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111

In [71]:
for tag in soup.select("item")[0]:
    for key in tag:
        print(key)

20250310
0
0
0
0
0
0
0
0
20250316
산업은행
1588-1500

# xml에 있는 모든 key 추출하기

In [80]:
tag_names = []
for items in soup.select("item"):
    for item in items:
        tag_names.append(item.name)
tag_names

['bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter']

# 집합자료형 set : 중복 없는 데이터 집합 만들기

In [76]:
tags = set(tag_names)
tags

{'body',
 'bssYmdEnd',
 'bssYmdStart',
 'callCenter',
 'header',
 'interest1_1',
 'interest1_2',
 'interest2_1',
 'interest2_2',
 'interest3_1',
 'interest3_2',
 'interest4_1',
 'interest4_2',
 'item',
 'items',
 'numOfRows',
 'organId',
 'pageNo',
 'response',
 'resultCode',
 'resultMsg',
 'totalCount'}

# 대출상품 자료 추출

In [163]:
f_soup.select("*")

[<response>
 <header>
 <resultCode>00</resultCode>
 <resultMsg>NORMAL SERVICE.</resultMsg>
 </header>
 <body>
 <numOfRows>1</numOfRows>
 <pageNo>1</pageNo>
 <totalCount>4741</totalCount>
 <items>
 <item>
 <basYm>202503</basYm>
 <snq>1</snq>
 <finPrdNm>새희망홀씨Ⅱ</finPrdNm>
 <lnLmt>3500만원</lnLmt>
 <irtCtg>변동금리</irtCtg>
 <irt>은행별 상이</irt>
 <maxTotLnTrm>은행별 상이</maxTotLnTrm>
 <maxDfrmTrm>-</maxDfrmTrm>
 <maxRdptTrm>-</maxRdptTrm>
 <rdptMthd>원(리)금균등분할상환</rdptMthd>
 <usge>생계</usge>
 <trgt>근로자</trgt>
 <instCtg>시중은행</instCtg>
 <ofrInstNm>14개 취급은행</ofrInstNm>
 <rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
 <suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>
 <age>없음</age>
 <incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>
 <rsdArea>-</rsdArea>
 <crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>
 <anin>-</anin>
 <housHoldCnt>-</housHoldCnt>
 <housAr>-</housAr>
 <lnTgtHous>-</lnTgtHous>
 <rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>
 <grnInst>-</grnInst>
 <jnMthd>14개 취급은행 신청방법 문의</jnMthd>
 <rpymdCfe>-</rpymdCfe>
 <lnIcdcst>-</lnIcdcst>
 <ovItrYr>-</ovItrYr>
 <prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>
 <etcRefSbjc>-</etcRefSbjc>
 <hdlInst>취급 은행(14개)</hdlInst>
 <cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>
 <rltSite>취급은행 홈페이지</rltSite>
 <tgtFltr>근로자</tgtFltr>
 <hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>
 <prdExisYn>Y</prdExisYn>
 <cv19Rfrc>-</cv19Rfrc>
 <prdCtg>1</prdCtg>
 <prdNm>대출상품</prdNm>
 <cv19SuprCtg>-</cv19SuprCtg>
 <cv19SuprCtn>-</cv19SuprCtn>
 <cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
 <mgmDln>상시</mgmDln>
 <prdCtg2>-</prdCtg2>
 <fileWrtDt>202504010700</fileWrtDt>
 </item>
 </items>
 </body>
 </response>,
 <header>
 <resultCode>00</resultCode>
 <resultMsg>NORMAL SERVICE.</resultMsg>
 </header>,
 <resultCode>00</resultCode>,
 <resultMsg>NORMAL SERVICE.</resultMsg>,
 <body>
 <numOfRows>1</numOfRows>
 <pageNo>1</pageNo>
 <totalCount>4741</totalCount>
 <items>
 <item>
 <basYm>202503</basYm>
 <snq>1</snq>
 <finPrdNm>새희망홀씨Ⅱ</finPrdNm>
 <lnLmt>3500만원</lnLmt>
 <irtCtg>변동금리</irtCtg>
 <irt>은행별 상이</irt>
 <maxTotLnTrm>은행별 상이</maxTotLnTrm>
 <maxDfrmTrm>-</maxDfrmTrm>
 <maxRdptTrm>-</maxRdptTrm>
 <rdptMthd>원(리)금균등분할상환</rdptMthd>
 <usge>생계</usge>
 <trgt>근로자</trgt>
 <instCtg>시중은행</instCtg>
 <ofrInstNm>14개 취급은행</ofrInstNm>
 <rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
 <suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>
 <age>없음</age>
 <incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>
 <rsdArea>-</rsdArea>
 <crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>
 <anin>-</anin>
 <housHoldCnt>-</housHoldCnt>
 <housAr>-</housAr>
 <lnTgtHous>-</lnTgtHous>
 <rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>
 <grnInst>-</grnInst>
 <jnMthd>14개 취급은행 신청방법 문의</jnMthd>
 <rpymdCfe>-</rpymdCfe>
 <lnIcdcst>-</lnIcdcst>
 <ovItrYr>-</ovItrYr>
 <prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>
 <etcRefSbjc>-</etcRefSbjc>
 <hdlInst>취급 은행(14개)</hdlInst>
 <cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>
 <rltSite>취급은행 홈페이지</rltSite>
 <tgtFltr>근로자</tgtFltr>
 <hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>
 <prdExisYn>Y</prdExisYn>
 <cv19Rfrc>-</cv19Rfrc>
 <prdCtg>1</prdCtg>
 <prdNm>대출상품</prdNm>
 <cv19SuprCtg>-</cv19SuprCtg>
 <cv19SuprCtn>-</cv19SuprCtn>
 <cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
 <mgmDln>상시</mgmDln>
 <prdCtg2>-</prdCtg2>
 <fileWrtDt>202504010700</fileWrtDt>
 </item>
 </items>
 </body>,
 <numOfRows>1</numOfRows>,
 <pageNo>1</pageNo>,
 <totalCount>4741</totalCount>,
 <items>
 <item>
 <basYm>202503</basYm>
 <snq>1</snq>
 <finPrdNm>새희망홀씨Ⅱ</finPrdNm>
 <lnLmt>3500만원</lnLmt>
 <irtCtg>변동금리</irtCtg>
 <irt>은행별 상이</irt>
 <maxTotLnTrm>은행별 상이</maxTotLnTrm>
 <maxDfrmTrm>-</maxDfrmTrm>
 <maxRdptTrm>-</maxRdptTrm>
 <rdptMthd>원(리)금균등분할상환</rdptMthd>
 <usge>생계</usge>
 <trgt>근로자</trgt>
 <instCtg>시중은행</instCtg>
 <ofrInstNm>14개 취급은행</ofrInstNm>
 <rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
 <suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>
 <age>없음</age>
 <incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>
 <rsdArea>-</rsdArea>
 <crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>
 <anin>-</anin>
 <housHoldCnt>-</housHoldCnt>
 <housAr>-</housAr>
 <lnTgtHous>-</lnTgtHous>
 <rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>
 <grnInst>-</grnInst>
 <jnMthd>14개 취급은행 신청방법 문의</jnMthd>
 <rpymdCfe>-</rpymdCfe>
 <lnIcdcst>-</lnIcdcst>
 <ovItrYr>-</ovItrYr>
 <prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>
 <etcRefSbjc>-</etcRefSbjc>
 <hdlInst>취급 은행(14개)</hdlInst>
 <cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>
 <rltSite>취급은행 홈페이지</rltSite>
 <tgtFltr>근로자</tgtFltr>
 <hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>
 <prdExisYn>Y</prdExisYn>
 <cv19Rfrc>-</cv19Rfrc>
 <prdCtg>1</prdCtg>
 <prdNm>대출상품</prdNm>
 <cv19SuprCtg>-</cv19SuprCtg>
 <cv19SuprCtn>-</cv19SuprCtn>
 <cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
 <mgmDln>상시</mgmDln>
 <prdCtg2>-</prdCtg2>
 <fileWrtDt>202504010700</fileWrtDt>
 </item>
 </items>,
 <item>
 <basYm>202503</basYm>
 <snq>1</snq>
 <finPrdNm>새희망홀씨Ⅱ</finPrdNm>
 <lnLmt>3500만원</lnLmt>
 <irtCtg>변동금리</irtCtg>
 <irt>은행별 상이</irt>
 <maxTotLnTrm>은행별 상이</maxTotLnTrm>
 <maxDfrmTrm>-</maxDfrmTrm>
 <maxRdptTrm>-</maxRdptTrm>
 <rdptMthd>원(리)금균등분할상환</rdptMthd>
 <usge>생계</usge>
 <trgt>근로자</trgt>
 <instCtg>시중은행</instCtg>
 <ofrInstNm>14개 취급은행</ofrInstNm>
 <rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
 <suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>
 <age>없음</age>
 <incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>
 <rsdArea>-</rsdArea>
 <crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>
 <anin>-</anin>
 <housHoldCnt>-</housHoldCnt>
 <housAr>-</housAr>
 <lnTgtHous>-</lnTgtHous>
 <rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>
 <grnInst>-</grnInst>
 <jnMthd>14개 취급은행 신청방법 문의</jnMthd>
 <rpymdCfe>-</rpymdCfe>
 <lnIcdcst>-</lnIcdcst>
 <ovItrYr>-</ovItrYr>
 <prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>
 <etcRefSbjc>-</etcRefSbjc>
 <hdlInst>취급 은행(14개)</hdlInst>
 <cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>
 <rltSite>취급은행 홈페이지</rltSite>
 <tgtFltr>근로자</tgtFltr>
 <hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>
 <prdExisYn>Y</prdExisYn>
 <cv19Rfrc>-</cv19Rfrc>
 <prdCtg>1</prdCtg>
 <prdNm>대출상품</prdNm>
 <cv19SuprCtg>-</cv19SuprCtg>
 <cv19SuprCtn>-</cv19SuprCtn>
 <cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
 <mgmDln>상시</mgmDln>
 <prdCtg2>-</prdCtg2>
 <fileWrtDt>202504010700</fileWrtDt>
 </item>,
 <basYm>202503</basYm>,
 <snq>1</snq>,
 <finPrdNm>새희망홀씨Ⅱ</finPrdNm>,
 <lnLmt>3500만원</lnLmt>,
 <irtCtg>변동금리</irtCtg>,
 <irt>은행별 상이</irt>,
 <maxTotLnTrm>은행별 상이</maxTotLnTrm>,
 <maxDfrmTrm>-</maxDfrmTrm>,
 <maxRdptTrm>-</maxRdptTrm>,
 <rdptMthd>원(리)금균등분할상환</rdptMthd>,
 <usge>생계</usge>,
 <trgt>근로자</trgt>,
 <instCtg>시중은행</instCtg>,
 <ofrInstNm>14개 취급은행</ofrInstNm>,
 <rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>,
 <suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>,
 <age>없음</age>,
 <incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>,
 <rsdArea>-</rsdArea>,
 <crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>,
 <anin>-</anin>,
 <housHoldCnt>-</housHoldCnt>,
 <housAr>-</housAr>,
 <lnTgtHous>-</lnTgtHous>,
 <rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>,
 <grnInst>-</grnInst>,
 <jnMthd>14개 취급은행 신청방법 문의</jnMthd>,
 <rpymdCfe>-</rpymdCfe>,
 <lnIcdcst>-</lnIcdcst>,
 <ovItrYr>-</ovItrYr>,
 <prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>,
 <etcRefSbjc>-</etcRefSbjc>,
 <hdlInst>취급 은행(14개)</hdlInst>,
 <cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>,
 <rltSite>취급은행 홈페이지</rltSite>,
 <tgtFltr>근로자</tgtFltr>,
 <hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>,
 <prdExisYn>Y</prdExisYn>,
 <cv19Rfrc>-</cv19Rfrc>,
 <prdCtg>1</prdCtg>,
 <prdNm>대출상품</prdNm>,
 <cv19SuprCtg>-</cv19SuprCtg>,
 <cv19SuprCtn>-</cv19SuprCtn>,
 <cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>,
 <mgmDln>상시</mgmDln>,
 <prdCtg2>-</prdCtg2>,
 <fileWrtDt>202504010700</fileWrtDt>]

In [168]:
fresult = {}
for item in f_soup.select("item"):
    for tags in item:
        for tag in tags:
            print(tag)
            fresult.setdefault(tag.name, []).append(tag.text)
# fresult
# df = pd.DataFrame(fresult)
# df

202503


1


새희망홀씨Ⅱ


3500만원


변동금리


은행별 상이


은행별 상이


-


-


원(리)금균등분할상환


생계


근로자


시중은행


14개 취급은행


전국


연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하


없음


연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)


-


신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자


-


-


-


-


취급은행 콜센터, 서민금융콜센터 (국번없이)1397


-


14개 취급은행 신청방법 문의


-


-


-


성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)


-


취급 은행(14개)


취급은행 콜센터, 서민금융콜센터 (국번없이)1397


취급은행 홈페이지


근로자


취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)


Y


-


1


대출상품


-


-


-


상시


-


202504010700

In [162]:
f_soup = bs(f_response, 'xml')
f_soup.select_one("resultCode")
f_soup

<?xml version="1.0" encoding="utf-8"?>
<response>
<header>
<resultCode>00</resultCode>
<resultMsg>NORMAL SERVICE.</resultMsg>
</header>
<body>
<numOfRows>1</numOfRows>
<pageNo>1</pageNo>
<totalCount>4741</totalCount>
<items>
<item>
<basYm>202503</basYm>
<snq>1</snq>
<finPrdNm>새희망홀씨Ⅱ</finPrdNm>
<lnLmt>3500만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>은행별 상이</irt>
<maxTotLnTrm>은행별 상이</maxTotLnTrm>
<maxDfrmTrm>-</maxDfrmTrm>
<maxRdptTrm>-</maxRdptTrm>
<rdptMthd>원(리)금균등분할상환</rdptMthd>
<usge>생계</usge>
<trgt>근로자</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>14개 취급은행</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>
<age>없음</age>
<incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>
<rsdArea>-</rsdArea>
<crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>
<grnInst>-</grnInst>
<jnMthd>14개 취급은행 신청방법 문의</jnMthd>
<rpymdCfe>-</rpymdCfe>
<lnIcdcst>-</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>
<etcRefSbjc>-</etcRefSbjc>
<hdlInst>취급 은행(14개)</hdlInst>
<cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>
<rltSite>취급은행 홈페이지</rltSite>
<tgtFltr>근로자</tgtFltr>
<hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
</items>
</body>
</response>

In [157]:
url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
ServiceKey = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D"
ServiceKey_d = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7/i3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r+OytZGorS2lwOw=="
payload = {"serviceKey" : ServiceKey_d,
           "pageNo": 1,
           "numOfRows": 1,
           "resultType" : "xml"}

r2 = requests.get(url, params=payload)
print(r2, end = "\r")
print(r2.status_code, end = "\r")
f_response=r2.text
f_response

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<response>\n    <header>\n        <resultCode>00</resultCode>\n        <resultMsg>NORMAL SERVICE.</resultMsg>\n    </header>\n    <body>\n        <numOfRows>1</numOfRows>\n        <pageNo>1</pageNo>\n        <totalCount>4741</totalCount>\n        <items>\n            <item>\n                <basYm>202503</basYm>\n                <snq>1</snq>\n                <finPrdNm>새희망홀씨Ⅱ</finPrdNm>\n                <lnLmt>3500만원</lnLmt>\n                <irtCtg>변동금리</irtCtg>\n                <irt>은행별 상이</irt>\n                <maxTotLnTrm>은행별 상이</maxTotLnTrm>\n                <maxDfrmTrm>-</maxDfrmTrm>\n                <maxRdptTrm>-</maxRdptTrm>\n                <rdptMthd>원(리)금균등분할상환</rdptMthd>\n                <usge>생계</usge>\n                <trgt>근로자</trgt>\n                <instCtg>시중은행</instCtg>\n                <ofrInstNm>14개 취급은행</ofrInstNm>\n                <rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>\n                <suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>\n                <age>없음</age>\n                <incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>\n                <rsdArea>-</rsdArea>\n                <crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>\n                <anin>-</anin>\n                <housHoldCnt>-</housHoldCnt>\n                <housAr>-</housAr>\n                <lnTgtHous>-</lnTgtHous>\n                <rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>\n                <grnInst>-</grnInst>\n                <jnMthd>14개 취급은행 신청방법 문의</jnMthd>\n                <rpymdCfe>-</rpymdCfe>\n                <lnIcdcst>-</lnIcdcst>\n                <ovItrYr>-</ovItrYr>\n                <prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>\n                <etcRefSbjc>-</etcRefSbjc>\n                <hdlInst>취급 은행(14개)</hdlInst>\n                <cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>\n                <rltSite>취급은행 홈페이지</rltSite>\n                <tgtFltr>근로자</tgtFltr>\n                <hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>\n                <prdExisYn>Y</prdExisYn>\n                <cv19Rfrc>-</cv19Rfrc>\n                <prdCtg>1</prdCtg>\n                <prdNm>대출상품</prdNm>\n                <cv19SuprCtg>-</cv19SuprCtg>\n                <cv19SuprCtn>-</cv19SuprCtn>\n                <cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>\n                <mgmDln>상시</mgmDln>\n                <prdCtg2>-</prdCtg2>\n                <fileWrtDt>202504010700</fileWrtDt>\n            </item>\n        </items>\n    </body>\n</response>\n'

In [145]:
result = {}
for item in soup.select("items"):
    for tags in item:
        for tag in tags:
            result.setdefault(tag.name, []).append(tag.text)
result
df = pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111

In [170]:
f_result = {}
for item2 in f_soup.select("item"):
    for tags2 in item2:
        if tags2.name == None :
            continue
        else:
            f_result.setdefault(tag2.name, []).append(tag.text)
f_result
# f_df = pd.DataFrame(f_result)
# f_df

AttributeError: 'str' object has no attribute 'name'

In [50]:
f_soup.name

'[document]'

In [146]:
f_result = {}
for item2 in f_soup.select("items"):
    for tags2 in item2.find_all() :
        f_result.setdefault(tags2.name, []).append(tags2.text)
        
f_result
f_df = pd.DataFrame(f_result)
f_df

Empty DataFrame
Columns: []
Index: []

In [150]:
f_names = []
for items in f_soup.select("*"):
    for fitem in items:
        f_names.append(fitem.name)
f_names

[]