In [1]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [7]:
url = "https://kind.krx.co.kr/corpgeneral/corpList.do"
payload = dict(method="searchCorpList", pageIndex=1, currentPageSize=15, orderMode=3, orderStat="D", searchType=13, fiscalYearEnd="all", location="all")

In [8]:
r = requests.post(url, data=payload)
print(r.status_code)
soup = bs(r.content, 'lxml')
soup

200

<html><body><section class="scrarea type-00">
<table class="list type-00 tmt30" summary="회사명, 업종, 주요제품, 상장일, 결산월, 대표자명, 홈페이지, 지역">
<caption>목록</caption>
<colgroup>
<col width="*"/>
<col width="15%"/>
<col width="20%"/>
<col width="11%"/>
<col width="8%"/>
<col width="10%"/>
<col width="8%"/>
<col width="12%"/>
</colgroup>
<thead>
<tr class="first" id="title-contents">
</tr>
</thead>
<tbody>
<tr class="first">
<td class="first" title="한국피아이엠(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44890'); return false;" title="한국피아이엠"> 한국피아이엠</a> </td>
<td class="textOverflow" title="자동차 신품 부품 제조업">자동차 신품 부품 제조업</td>
<td class="textOverflow" title="내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)">내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)</td>
<td class="txc">2025-04-04</td>
<td class="txc">12월</td>
<td class="txc" title="송준호">송준호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.pimkorea.com" target="_blank" title="http://www.pimkorea.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대구광역시</td>
</tr>
<tr>
<td class="first" title="(주)에이유브랜즈"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48107'); return false;" title="에이유브랜즈"> 에이유브랜즈</a> </td>
<td class="textOverflow" title="섬유, 의복, 신발 및 가죽제품 소매업">섬유, 의복, 신발 및 가죽제품 소매업</td>
<td class="textOverflow" title="레인부츠, 스니커즈, 겨울화, 패션잡화 등">레인부츠, 스니커즈, 겨울화, 패션잡화 등</td>
<td class="txc">2025-04-03</td>
<td class="txc">12월</td>
<td class="txc" title="김지훈">김지훈</td>
<td class="txc">
<a class="btn ico homepage" href="http://aubrandz.irpage.co.kr" target="_blank" title="http://aubrandz.irpage.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="우양에이치씨(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('10197'); return false;" title="우양에이치씨"> 우양에이치씨</a> </td>
<td class="textOverflow" title="구조용 금속제품, 탱크 및 증기발생기 제조업">구조용 금속제품, 탱크 및 증기발생기 제조업</td>
<td class="textOverflow" title="화공 플랜트, 에너지 플랜트">화공 플랜트, 에너지 플랜트</td>
<td class="txc">2025-03-28</td>
<td class="txc">12월</td>
<td class="txc" title="김진태">김진태</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.wooyang.co.kr" target="_blank" title="http://www.wooyang.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)더즌"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46286'); return false;" title="더즌"> 더즌</a> </td>
<td class="textOverflow" title="전기 통신업">전기 통신업</td>
<td class="textOverflow" title="디지털뱅킹 솔루션(B2B 금융 서비스)">디지털뱅킹 솔루션(B2B 금융 서비스)</td>
<td class="txc">2025-03-24</td>
<td class="txc">12월</td>
<td class="txc" title="조철한">조철한</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dozn.co.kr/" target="_blank" title="http://www.dozn.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)심플랫폼"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44453'); return false;" title="심플랫폼"> 심플랫폼</a> </td>
<td class="textOverflow" title="소프트웨어 개발 및 공급업">소프트웨어 개발 및 공급업</td>
<td class="textOverflow" title="NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)">NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)</td>
<td class="txc">2025-03-21</td>
<td class="txc">12월</td>
<td class="txc" title="임대근, 강태신">임대근..</td>
<td class="txc">
<a class="btn ico homepage" href="http://simplatform.com/" target="_blank" title="http://simplatform.com/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="주식회사 티엑스알로보틱스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48481'); return false;" title="티엑스알로보틱스"> 티엑스알로보틱스</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="물류자동화, 로봇자동화, AMR/AGV">물류자동화, 로봇자동화, AMR/AGV</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="엄인섭">엄인섭</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.txr.kr" target="_blank" title="http://www.txr.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)한텍"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('09807'); return false;" title="한텍"> 한텍</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="열교환기 등 화공기기, 저장용 탱크">열교환기 등 화공기기, 저장용 탱크</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김강식">김강식</td>
<td class="txc">
<a class="btn ico homepage" href="http://hantechltd.com" target="_blank" title="http://hantechltd.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">울산광역시</td>
</tr>
<tr>
<td class="first" title="한화플러스제5호기업인수목적(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('49839'); return false;" title="한화플러스제5호스팩"> 한화플러스제5호스팩</a> </td>
<td class="textOverflow" title="금융 지원 서비스업">금융 지원 서비스업</td>
<td class="textOverflow" title="-">-</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김광후">김광후</td>
<td class="txc">
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)씨케이솔루션"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48037'); return false;" title="씨케이솔루션"> 씨케이솔루션</a> </td>
<td class="textOverflow" title="건축기술, 엔지니어링 및 관련 기술 서비스업">건축기술, 엔지니어링 및 관련 기술 서비스업</td>
<td class="textOverflow" title="드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업">드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업</td>
<td class="txc">2025-03-17</td>
<td class="txc">12월</td>
<td class="txc" title="김유곤, 안근표 (공동 대표이사)">김유곤..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.cksolution.co.kr/" target="_blank" title="http://www.cksolution.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="서울보증보험(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('03121'); return false;" title="서울보증보험"> 서울보증보험</a> </td>
<td class="textOverflow" title="보험업">보험업</td>
<td class="textOverflow" title="보증보험, 신용보험 등">보증보험, 신용보험 등</td>
<td class="txc">2025-03-14</td>
<td class="txc">12월</td>
<td class="txc" title="이명순">이명순</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.sgic.co.kr" target="_blank" title="http://www.sgic.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)에스엠씨지"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46087'); return false;" title="에스엠씨지"> 에스엠씨지</a> </td>
<td class="textOverflow" title="유리 및 유리제품 제조업">유리 및 유리제품 제조업</td>
<td class="textOverflow" title="화장품 유리용기">화장품 유리용기</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="최승호">최승호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.somangglass.co.kr" target="_blank" title="http://www.somangglass.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="엠디바이스 주식회사"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('22659'); return false;" title="엠디바이스"> 엠디바이스</a> </td>
<td class="textOverflow" title="전자부품 제조업">전자부품 제조업</td>
<td class="textOverflow" title="반도체기억장치">반도체기억장치</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="조호경">조호경</td>
<td class="txc">
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="대진첨단소재(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('39397'); return false;" title="대진첨단소재"> 대진첨단소재</a> </td>
<td class="textOverflow" title="플라스틱제품 제조업">플라스틱제품 제조업</td>
<td class="textOverflow" title="이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름">이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름</td>
<td class="txc">2025-03-06</td>
<td class="txc">12월</td>
<td class="txc" title="유성준, 장현주">유성준..</td>
<td class="txc">
<a class="btn ico homepage" href="http://daejin2019.com" target="_blank" title="http://daejin2019.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)에르코스 농업회사법인"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('43557'); return false;" title="에르코스"> 에르코스</a> </td>
<td class="textOverflow" title="도시락 및 식사용 조리식품 제조업">도시락 및 식사용 조리식품 제조업</td>
<td class="textOverflow" title="영유아식, 고령친화식품, 식물기반 대체식품">영유아식, 고령친화식품, 식물기반 대체식품</td>
<td class="txc">2025-02-28</td>
<td class="txc">12월</td>
<td class="txc" title="김슬기">김슬기</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ercohs.com" target="_blank" title="http://www.ercohs.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대전광역시</td>
</tr>
<tr>
<td class="first" title="(주)엘케이켐"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48950'); return false;" title="엘케이켐"> 엘케이켐</a> </td>
<td class="textOverflow" title="기타 화학제품 제조업">기타 화학제품 제조업</td>
<td class="textOverflow" title="반도체 소재(CP, PCP, DIS) 등">반도체 소재(CP, PCP, DIS) 등</td>
<td class="txc">2025-02-25</td>
<td class="txc">12월</td>
<td class="txc" title="이창엽">이창엽</td>
<td class="txc">
<a class="btn ico homepage" href="http://lkchem.co.kr" target="_blank" title="http://lkchem.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청남도</td>
</tr>
</tbody>
</table>
</section>
<!-- 페이징 START -->
<section class="paging-group">
<div class="paging type-00"><a class="pprev" href="#prevPage10" onclick="return false;"><span>이전10개 페이지</span></a><a class="prev" href="#prevPage" onclick="return false;"><span>이전 페이지</span></a>
<a class="active" href="#page_link_1" onclick="return false;">1</a><a href="#page_link_2" onclick="fnPageGo('2');return false;">2</a><a href="#page_link_3" onclick="fnPageGo('3');return false;">3</a><a href="#page_link_4" onclick="fnPageGo('4');return false;">4</a><a href="#page_link_5" onclick="fnPageGo('5');return false;">5</a><a href="#page_link_6" onclick="fnPageGo('6');return false;">6</a><a href="#page_link_7" onclick="fnPageGo('7');return false;">7</a><a href="#page_link_8" onclick="fnPageGo('8');return false;">8</a><a href="#page_link_9" onclick="fnPageGo('9');return false;">9</a><a href="#page_link_10" onclick="fnPageGo('10');return false;">10</a>
<a class="next" href="#nextPage" onclick="fnPageGo('2');return false;"><span>다음 페이지</span></a><a class="nnext" href="#nextPage10" onclick="fnPageGo('11');return false;"><span>다음10개 페이지</span></a></div><div class="info type-00">
전체 <em>2,761</em>건 : <strong>1</strong>/185
<select id="currentPageSize" name="currentPageSize">
<option selected="selected" value="15">15건</option>
<option value="30">30건</option>
<option value="50">50건</option>
<option value="100">100건</option>
</select>  <a class="btn-sprite btn-go vmiddle" href="#" onclick="fnSearch1();return false;" title="GO"><span>GO</span></a>
</div>
</section>
<!-- 페이징 END -->
<script type="text/JavaScript">
$(document).ready(function(){
	fn_InitTitle("회사명,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역", "true,false,false,true,false,false,false,false");
});
</script></body></html>

In [164]:
com_list = soup.select("tbody > tr")

In [129]:
key_list = ["회사명", "업종", "주요제품", "상장일", "결산월", "대표자명", "홈페이지", "지역"]

In [130]:
key_list

['회사명', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역']

In [83]:
time.sleep(5)
print(com_list)

[<tr class="first">
<td class="first" title="한국피아이엠(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44890'); return false;" title="한국피아이엠"> 한국피아이엠</a> </td>
<td class="textOverflow" title="자동차 신품 부품 제조업">자동차 신품 부품 제조업</td>
<td class="textOverflow" title="내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)">내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)</td>
<td class="txc">2025-04-04</td>
<td class="txc">12월</td>
<td class="txc" title="송준호">송준호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.pimkorea.com" target="_blank" title="http://www.pimkorea.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대구광역시</td>
</tr>, <tr>
<td class="first" title="(주)에이유브랜즈"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48107'); return false;" title="에이유브랜즈"> 에이유브랜즈</a> </td>
<td class="textOverflow" title="섬유, 의복, 신발 및 가죽제품 소매업">섬유, 의복, 신발 및 가죽제품 소매업</td>
<td class="textOverflow" title="레인부츠, 스니커즈, 겨울화, 패션잡화 등">레인부츠, 스니커즈, 겨울화, 패션잡화 등</td>
<td class="txc">2025-04-03</td>
<td class="txc">12월</td>
<td class="txc" title="김지훈">김지훈</td>
<td class="txc">
<a class="btn ico homepage" href="http://aubrandz.irpage.co.kr" target="_blank" title="http://aubrandz.irpage.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>, <tr>
<td class="first" title="우양에이치씨(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('10197'); return false;" title="우양에이치씨"> 우양에이치씨</a> </td>
<td class="textOverflow" title="구조용 금속제품, 탱크 및 증기발생기 제조업">구조용 금속제품, 탱크 및 증기발생기 제조업</td>
<td class="textOverflow" title="화공 플랜트, 에너지 플랜트">화공 플랜트, 에너지 플랜트</td>
<td class="txc">2025-03-28</td>
<td class="txc">12월</td>
<td class="txc" title="김진태">김진태</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.wooyang.co.kr" target="_blank" title="http://www.wooyang.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>, <tr>
<td class="first" title="(주)더즌"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46286'); return false;" title="더즌"> 더즌</a> </td>
<td class="textOverflow" title="전기 통신업">전기 통신업</td>
<td class="textOverflow" title="디지털뱅킹 솔루션(B2B 금융 서비스)">디지털뱅킹 솔루션(B2B 금융 서비스)</td>
<td class="txc">2025-03-24</td>
<td class="txc">12월</td>
<td class="txc" title="조철한">조철한</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dozn.co.kr/" target="_blank" title="http://www.dozn.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>, <tr>
<td class="first" title="(주)심플랫폼"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44453'); return false;" title="심플랫폼"> 심플랫폼</a> </td>
<td class="textOverflow" title="소프트웨어 개발 및 공급업">소프트웨어 개발 및 공급업</td>
<td class="textOverflow" title="NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)">NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)</td>
<td class="txc">2025-03-21</td>
<td class="txc">12월</td>
<td class="txc" title="임대근, 강태신">임대근..</td>
<td class="txc">
<a class="btn ico homepage" href="http://simplatform.com/" target="_blank" title="http://simplatform.com/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>, <tr>
<td class="first" title="주식회사 티엑스알로보틱스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48481'); return false;" title="티엑스알로보틱스"> 티엑스알로보틱스</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="물류자동화, 로봇자동화, AMR/AGV">물류자동화, 로봇자동화, AMR/AGV</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="엄인섭">엄인섭</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.txr.kr" target="_blank" title="http://www.txr.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>, <tr>
<td class="first" title="(주)한텍"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('09807'); return false;" title="한텍"> 한텍</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="열교환기 등 화공기기, 저장용 탱크">열교환기 등 화공기기, 저장용 탱크</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김강식">김강식</td>
<td class="txc">
<a class="btn ico homepage" href="http://hantechltd.com" target="_blank" title="http://hantechltd.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">울산광역시</td>
</tr>, <tr>
<td class="first" title="한화플러스제5호기업인수목적(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('49839'); return false;" title="한화플러스제5호스팩"> 한화플러스제5호스팩</a> </td>
<td class="textOverflow" title="금융 지원 서비스업">금융 지원 서비스업</td>
<td class="textOverflow" title="-">-</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김광후">김광후</td>
<td class="txc">
</td>
<td class="txc">서울특별시</td>
</tr>, <tr>
<td class="first" title="(주)씨케이솔루션"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48037'); return false;" title="씨케이솔루션"> 씨케이솔루션</a> </td>
<td class="textOverflow" title="건축기술, 엔지니어링 및 관련 기술 서비스업">건축기술, 엔지니어링 및 관련 기술 서비스업</td>
<td class="textOverflow" title="드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업">드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업</td>
<td class="txc">2025-03-17</td>
<td class="txc">12월</td>
<td class="txc" title="김유곤, 안근표 (공동 대표이사)">김유곤..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.cksolution.co.kr/" target="_blank" title="http://www.cksolution.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>, <tr>
<td class="first" title="서울보증보험(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('03121'); return false;" title="서울보증보험"> 서울보증보험</a> </td>
<td class="textOverflow" title="보험업">보험업</td>
<td class="textOverflow" title="보증보험, 신용보험 등">보증보험, 신용보험 등</td>
<td class="txc">2025-03-14</td>
<td class="txc">12월</td>
<td class="txc" title="이명순">이명순</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.sgic.co.kr" target="_blank" title="http://www.sgic.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>, <tr>
<td class="first" title="(주)에스엠씨지"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46087'); return false;" title="에스엠씨지"> 에스엠씨지</a> </td>
<td class="textOverflow" title="유리 및 유리제품 제조업">유리 및 유리제품 제조업</td>
<td class="textOverflow" title="화장품 유리용기">화장품 유리용기</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="최승호">최승호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.somangglass.co.kr" target="_blank" title="http://www.somangglass.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>, <tr>
<td class="first" title="엠디바이스 주식회사"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('22659'); return false;" title="엠디바이스"> 엠디바이스</a> </td>
<td class="textOverflow" title="전자부품 제조업">전자부품 제조업</td>
<td class="textOverflow" title="반도체기억장치">반도체기억장치</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="조호경">조호경</td>
<td class="txc">
</td>
<td class="txc">경기도</td>
</tr>, <tr>
<td class="first" title="대진첨단소재(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('39397'); return false;" title="대진첨단소재"> 대진첨단소재</a> </td>
<td class="textOverflow" title="플라스틱제품 제조업">플라스틱제품 제조업</td>
<td class="textOverflow" title="이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름">이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름</td>
<td class="txc">2025-03-06</td>
<td class="txc">12월</td>
<td class="txc" title="유성준, 장현주">유성준..</td>
<td class="txc">
<a class="btn ico homepage" href="http://daejin2019.com" target="_blank" title="http://daejin2019.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>, <tr>
<td class="first" title="(주)에르코스 농업회사법인"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('43557'); return false;" title="에르코스"> 에르코스</a> </td>
<td class="textOverflow" title="도시락 및 식사용 조리식품 제조업">도시락 및 식사용 조리식품 제조업</td>
<td class="textOverflow" title="영유아식, 고령친화식품, 식물기반 대체식품">영유아식, 고령친화식품, 식물기반 대체식품</td>
<td class="txc">2025-02-28</td>
<td class="txc">12월</td>
<td class="txc" title="김슬기">김슬기</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ercohs.com" target="_blank" title="http://www.ercohs.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대전광역시</td>
</tr>, <tr>
<td class="first" title="(주)엘케이켐"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48950'); return false;" title="엘케이켐"> 엘케이켐</a> </td>
<td class="textOverflow" title="기타 화학제품 제조업">기타 화학제품 제조업</td>
<td class="textOverflow" title="반도체 소재(CP, PCP, DIS) 등">반도체 소재(CP, PCP, DIS) 등</td>
<td class="txc">2025-02-25</td>
<td class="txc">12월</td>
<td class="txc" title="이창엽">이창엽</td>
<td class="txc">
<a class="btn ico homepage" href="http://lkchem.co.kr" target="_blank" title="http://lkchem.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청남도</td>
</tr>]

In [97]:
print(type(i))

<class 'bs4.element.Tag'>

In [111]:
com_list[0].text

'\n  한국피아이엠 \n자동차 신품 부품 제조업\n내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)\n2025-04-04\n12월\n송준호\n\n홈페이지 보기\n\n대구광역시\n'

In [108]:
com_result = {}
for i in com_list :
    time.sleep(5)
    com_result.setdefault("key",[]).append(i.text) 
df = pd.DataFrame(com_result)
df

                                                  key
0   \n  한국피아이엠 \n자동차 신품 부품 제조업\n내연기관 부품(터보차저, DCT변...
1   \n  에이유브랜즈 \n섬유, 의복, 신발 및 가죽제품 소매업\n레인부츠, 스니커즈...
2   \n  우양에이치씨 \n구조용 금속제품, 탱크 및 증기발생기 제조업\n화공 플랜트,...
3   \n  더즌 \n전기 통신업\n디지털뱅킹 솔루션(B2B 금융 서비스)\n2025-0...
4   \n  심플랫폼 \n소프트웨어 개발 및 공급업\nNUBISON AIoT(산업용 데이...
5   \n  티엑스알로보틱스 \n일반 목적용 기계 제조업\n물류자동화, 로봇자동화, AM...
6   \n  한텍 \n일반 목적용 기계 제조업\n열교환기 등 화공기기, 저장용 탱크\n2...
7   \n  한화플러스제5호스팩 \n금융 지원 서비스업\n-\n2025-03-20\n12...
8   \n  씨케이솔루션 \n건축기술, 엔지니어링 및 관련 기술 서비스업\n드라이룸/클린...
9   \n  서울보증보험 \n보험업\n보증보험, 신용보험 등\n2025-03-14\n12...
10  \n  에스엠씨지 \n유리 및 유리제품 제조업\n화장품 유리용기\n2025-03-0...
11  \n  엠디바이스 \n전자부품 제조업\n반도체기억장치\n2025-03-07\n12월...
12  \n  대진첨단소재 \n플라스틱제품 제조업\n이차전지 공정용 대전방지트레이, 대전방...
13  \n  에르코스 \n도시락 및 식사용 조리식품 제조업\n영유아식, 고령친화식품, 식...
14  \n  엘케이켐 \n기타 화학제품 제조업\n반도체 소재(CP, PCP, DIS) 등...

In [131]:
key_list = ["회사명", "업종", "주요제품", "상장일", "결산월", "대표자명", "홈페이지", "지역"]
com_result = {}
for i in com_list:
    time.sleep(5)
    for j in i.contents:
        if j.text == "\n":
            continue
        else:
            com_result.setdefault(key_list, []).setdefault(j)
result = pd.DataFrame(com_result)
result

TypeError: unhashable type: 'list'

In [323]:
com_result = {}
for i in com_list:
    key_index = 0
    for j in i.contents:
        if not j.name :
            continue
        else :
            com_result.setdefault(key_list[key_index],[]).append(j.text)
            key_index+=1
           
    
for key,value in com_result.items():
    print(f"{key} len : {len(value)}")
result = pd.DataFrame(com_result)
result

회사명 len : 15
업종 len : 15
주요제품 len : 15
상장일 len : 15
결산월 len : 15
대표자명 len : 15
홈페이지 len : 15
지역 len : 15

,회사명,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,한국피아이엠,자동차 신품 부품 제조업,"내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행...",2025-04-04,12월,송준호,\n홈페이지 보기\n,대구광역시
1,에이유브랜즈,"섬유, 의복, 신발 및 가죽제품 소매업","레인부츠, 스니커즈, 겨울화, 패션잡화 등",2025-04-03,12월,김지훈,\n홈페이지 보기\n,서울특별시
2,우양에이치씨,"구조용 금속제품, 탱크 및 증기발생기 제조업","화공 플랜트, 에너지 플랜트",2025-03-28,12월,김진태,\n홈페이지 보기\n,경기도
3,더즌,전기 통신업,디지털뱅킹 솔루션(B2B 금융 서비스),2025-03-24,12월,조철한,\n홈페이지 보기\n,서울특별시
4,심플랫폼,소프트웨어 개발 및 공급업,NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영),2025-03-21,12월,임대근..,\n홈페이지 보기\n,서울특별시
5,티엑스알로보틱스,일반 목적용 기계 제조업,"물류자동화, 로봇자동화, AMR/AGV",2025-03-20,12월,엄인섭,\n홈페이지 보기\n,경기도
6,한텍,일반 목적용 기계 제조업,"열교환기 등 화공기기, 저장용 탱크",2025-03-20,12월,김강식,\n홈페이지 보기\n,울산광역시
7,한화플러스제5호스팩,금융 지원 서비스업,-,2025-03-20,12월,김광후,\n,서울특별시
8,씨케이솔루션,"건축기술, 엔지니어링 및 관련 기술 서비스업","드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업",2025-03-17,12월,김유곤..,\n홈페이지 보기\n,경기도
9,서울보증보험,보험업,"보증보험, 신용보험 등",2025-03-14,12월,이명순,\n홈페이지 보기\n,서울특별시
10,에스엠씨지,유리 및 유리제품 제조업,화장품 유리용기,2025-03-07,12월,최승호,\n홈페이지 보기\n,경기도
11,엠디바이스,전자부품 제조업,반도체기억장치,2025-03-07,12월,조호경,\n,경기도
12,대진첨단소재,플라스틱제품 제조업,"이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름",2025-03-06,12월,유성준..,\n홈페이지 보기\n,서울특별시
13,에르코스,도시락 및 식사용 조리식품 제조업,"영유아식, 고령친화식품, 식물기반 대체식품",2025-02-28,12월,김슬기,\n홈페이지 보기\n,대전광역시
14,엘케이켐,기타 화학제품 제조업,"반도체 소재(CP, PCP, DIS) 등",2025-02-25,12월,이창엽,\n홈페이지 보기\n,충청남도

In [328]:
result.to_csv(f"상장기업정보{today}.csv", encoding="utf-8-sig", index=False)

NameError: name 'today' is not defined

In [326]:
df.to_csv(f"상장기업정보")

SyntaxError: EOL while scanning string literal (2346149092.py, line 1)

# 찾을 자료를 1개씩 찾아보기

In [179]:
soup.select("tbody > tr")[0]

<tr class="first">
<td class="first" title="한국피아이엠(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44890'); return false;" title="한국피아이엠"> 한국피아이엠</a> </td>
<td class="textOverflow" title="자동차 신품 부품 제조업">자동차 신품 부품 제조업</td>
<td class="textOverflow" title="내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)">내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)</td>
<td class="txc">2025-04-04</td>
<td class="txc">12월</td>
<td class="txc" title="송준호">송준호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.pimkorea.com" target="_blank" title="http://www.pimkorea.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대구광역시</td>
</tr>

In [180]:
# 업종
soup.select("tbody > tr")[0].select_one("td:nth-child(2)").text

'자동차 신품 부품 제조업'

In [181]:
# 상장일
soup.select("tbody > tr")[0].select_one("td:nth-child(4)").text

'2025-04-04'

In [182]:
# 대표자명
soup.select("tbody > tr")[0].select_one("td:nth-child(6)").text

'송준호'

In [229]:
# 주식종목
soup.select("tbody > tr")[0].select_one("td:nth-child(1)").text

'  한국피아이엠 '

In [184]:
# 지역
soup.select("tbody > tr")[0].select_one("td:nth-child(8)").text

'대구광역시'

In [207]:
# 주요제품
soup.select("tbody > tr")[0].select_one("td:nth-child(3)").text

'내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)'

In [213]:
# 종목코드
soup.select("tbody > tr")[0].select_one("td:nth-child(1)> img")["alt"]

'코스닥'

In [214]:
soup.select("tbody > tr")[0].select_one("td:nth-child(1)> a")["title"]

'한국피아이엠'

In [188]:
# 전체페이지
total_page = int(soup.select_one(".info.type-00 > em").text.replace(",","")) //100 +1

In [191]:
# 컬럼명
columns = soup.select_one("table")["summary"].split(",")
columns.insert(0, "주식종목")

In [193]:
columns.insert(2,"종목코드")
columns

['주식종목',
 '회사명',
 '종목코드',
 ' 업종',
 ' 주요제품',
 ' 상장일',
 ' 결산월',
 ' 대표자명',
 ' 홈페이지',
 ' 지역']

# 수집한 자료를 DB에 저장하기

In [332]:
from sqlalchemy import create_engine, text
import pymysql
pymysql.install_as_MySQLdb()

* sqlalchemy의 create_engine을 이용해서 mysql 서버에 접속<br>
engine = create_engine("mysql+pymysql://<userid>:<password>>@ip주소:<post>/데이터베이스이름)

In [334]:
# localhost = 127.0.0.1
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
# engine.connect : create_engine에 있는 정보로 db 접속
conn = engine.connect()

OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'stock_info'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [335]:
# 데이터프레임을 db에 저장하기
# 데이터프레임.to_sql("테이블명")
df.to_sql(f"stock_company_info_", con=conn, if_exists = 'replace', index=False )
conn.close()

NameError: name 'conn' is not defined

# 판다스의 read_html 이용해서 table 자료 한번에 가져오기

In [337]:
pd.read_html(soup.select_one("table").text)

C:\Users\1\AppData\Local\Temp\ipykernel_22000\1418197036.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(soup.select_one("table").text)

FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?